### ISSUE TITLE
[Question] How to configure docker-compse file to redirect a page to another ?

### ISSUE THREAD

**Issue by Kazebayashi** [SteveLTN/https-portal#102]
Hi
I would like to add a redirection from an old url to the new url.
`/old.page` to `https://www.new.domain-name.com`
How can I add this redirection to nginx through the docker-compose file?

Thanks for your help!

**Comment by SteveLTN** [comment]
Hi,

Unfortunately it is not possible right now. I do have an idea about how to implement, but I haven't got time to implement it. I think the easiest way for you now it to use a custom nginx config file.

**Comment by SteveLTN** [comment]
Hi, as version 1.2.0 is released, you can add redirections now. See [the document](https://github.com/SteveLTN/https-portal#redirections).

**Comment by Kazebayashi** [comment]
Thanks!!
