### ISSUE TITLE
LetsEncrypt agreement error

### ISSUE THREAD

**Issue by DannyJo** [SteveLTN/https-portal#104]
The following error is now presented when asking for a production certificate as of November 15th 2017

`https-portal_1    | ValueError: Error registering: 400 {
https-portal_1    |   "type": "urn:acme:error:malformed",
https-portal_1    |   "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]",
https-portal_1    |   "status": 400
https-portal_1    | `

It looks like the acme script at https://raw.githubusercontent.com/diafygi/acme-tiny/19b274cf38544ad9ccc69aa140969c30c4e0d8fd/acme_tiny.py should cope with this but the current version of the script included in the latest docker image has a hard coded url to the August 1st 2016 agreement. I suspect a new image needs to be built and pushed to docker hub with the latest "acme_tiny" script.

**Comment by sbrendtro** [comment]
I was literally about to post the same issue.  Certainly a show-stopper for me, as I was just setting this up for the first time and it won't grab any new certs.

**Comment by SteveLTN** [comment]
A [pull-request](https://github.com/SteveLTN/https-portal/pull/103) was merged earlier today. I'm running a series of tests. A new release is coming soon.

**Comment by DannyJo** [comment]
Excellent, props for the fast action taken on this 👍

**Comment by gdbjohnson** [comment]
Is this an issue that affects production currently?  Or only latest pulls?

**Comment by SteveLTN** [comment]
It affects production sites when renewing certificates.

**Comment by SteveLTN** [comment]
Version 1.2.0 is being built on DockerHub now. You should be able to pull it down in a new minutes. (You can use :1, :1.2 or :1.2.0 tag)

**Comment by DannyJo** [comment]
Works great, thanks 👍

**Comment by billimek** [comment]
@SteveLTN is the intent to eventually tag the `latest` images with this change as well?  I've been hitting against `latest` all-along and wondering if I need to change.
