### ISSUE TITLE
Redirection makes directories for vhosts

### ISSUE THREAD

**Issue by wiserain** [SteveLTN/https-portal#105]
I found a redirection feature is updated and tried to use but it makes new dir together with welcome html page in the same way for virtual host. Is it necessary and expected behavior?

**Comment by SteveLTN** [comment]
That can be considered as a bug. I'll fix it later.

**Comment by SteveLTN** [comment]
v1.2.1 fixed it! That folder was unnecessary. I didn't check whether if has redirection when generating this folder.

**Comment by wiserain** [comment]
@SteveLTN It works well. Thanks your immediate feedback!!
