### ISSUE TITLE
Error registering: 400

### ISSUE THREAD

**Issue by SzymonFortuna** [SteveLTN/https-portal#106]
Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]

**Comment by SzymonFortuna** [comment]
https-portal_1  | 2017/11/16 14:23:10 [reconfig]: Traceback (most recent call last):
https-portal_1  | 2017/11/16 14:23:10 [reconfig]:   File "/bin/acme_tiny", line 198, in <module>
https-portal_1  | 2017/11/16 14:23:10 [reconfig]:     main(sys.argv[1:])
https-portal_1  | 2017/11/16 14:23:10 [reconfig]:   File "/bin/acme_tiny", line 194, in main
https-portal_1  | 2017/11/16 14:23:10 [reconfig]:     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
https-portal_1  | 2017/11/16 14:23:10 [reconfig]:   File "/bin/acme_tiny", line 92, in get_crt
https-portal_1  | 2017/11/16 14:23:10 [reconfig]:     raise ValueError("Error registering: {0} {1}".format(code, result))
https-portal_1  | 2017/11/16 14:23:10 [reconfig]: ValueError: Error registering: 400 {
https-portal_1  | 2017/11/16 14:23:10 [reconfig]:   "type": "urn:acme:error:malformed",
https-portal_1  | 2017/11/16 14:23:10 [reconfig]:   "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]",
https-portal_1  | 2017/11/16 14:23:10 [reconfig]:   "status": 400
https-portal_1  | 2017/11/16 14:23:10 [reconfig]: }

**Comment by SteveLTN** [comment]
HI, the latest release of yesterday v1.2.0 solved this. Just update the image :-)
