### ISSUE TITLE
[ Question ] 0 Downtime

### ISSUE THREAD

**Issue by Spitrip** [SteveLTN/https-portal#109]
Hello there,

I have fully configured my service for https-portal, unique issue i'am currently having is next use case:

I have "app1" => "app1.domain" and "app2" => "app2.domain" running through the https-portal. 

So far so good. Everything is perfect. I can access app1.domain and I can access app2.domain after deploying both apps.

**The problem:**

- On next day I added some one feature to app1.
- I stop my service, which is app1, build it and start it.

**Result:**
403 Forbidden on page of app1
403 Forbidden on page of app2

**Analysis:**
The 403 error is coming derived from IP change by docker.

**This is my config for https-portal:**

`version: '2' `
`services:  `
`  https-portal:`
`    image: steveltn/https-portal:1`
`    ports:`
`      - '80:80'`
`      - '443:443'`
`    volumes:`
`      - ./configs:/etc/nginx/conf.d/:rw`
`      - ./nginx-conf-default:/var/lib/nginx-conf/:rw`
`      - /data/ssl_certs:/var/lib/https-portal:rw`
`      - /var/run/docker.sock:/var/run/docker.sock:ro`
`    network_mode: 'bridge'`
`    environment:`
`      STAGE: "staging"`
`      WEBSOCKET: "true"`
`      RESOLVER: "127.0.0.11 ipv6=off valid=30s"`
`      DYNAMIC_UPSTREAM: "true"`

**This is example of my frontend config, which is similar of any app im running:**
`version: '2'`
`services:`
`  app1-frontend:`
`    container_name: app1-frontend`
`    build:`
`      context: "./app1-frontend"`
`    environment:`
`      - VIRTUAL_HOST=app1.domain`
`    depends_on:`
`      - app1-backend`
`    network_mode: "bridge"`

Hope there is a good solution for my problem and thanks in advance for your time!
Igors Sigalovs

**Comment by SteveLTN** [comment]
Hi!

I see you are using automatic container discovery to configure your upstreams. As far as I can see from the code, an update on any containers should trigger an Nginx reload. I don't know why, will have a look in the weekend. 

I can see you also used DYNAMIC_UPSTREAM. Does the upstream info get updated on RESOLVER?

**Comment by SteveLTN** [comment]
I tried it, works well for me. Is it possible that your app is blocking the request?

**Comment by Spitrip** [comment]
Sorry for not answering for so long, having tons of work to do lately. I'am really new to docker, so bear with me. Where do I see the info about resolver, some example perhaps? 

I have custom configuration files for each docker-compose file. Could that be the issue? 

What do you mean by blocking the request?

Thanks in advance.

**Comment by Spitrip** [comment]
I think i found the issue.
Basically i changed my enviroment STAGE: "staging" to STAGE: 'production' <- it started working flawlessly. 

Can you confirm from where the issue comes? If its from staging, just test the staging value? If it is working as expected then it even might be problem with the way i wrap variable and docker version messes something?

OS: Ubuntu 16.04
Docker Version 17.10.0-CE, build f4ffd25
docker-compose version 1.17.1, build 6d101fb

I will try to see this weekend if it is possible to recreate the problem again.

**Comment by SteveLTN** [comment]
Hi, I just tried it out on staging. Can't reproduce the problem. You can tap into the container by running `docker-compose exec https-portal bash`, and run the renew job: `/etc/cron.weekly/renew_certs`.
