### ISSUE TITLE
Is it possibile to use this Docker image on a VPS?

### ISSUE THREAD

**Issue by ticketapp** [SteveLTN/https-portal#11]
I'm trying to make this Docker image on my VPS. I followed the prerequisites (I have Docker installed, the ports 80 and 443 are available and my domain name resolves to my machine (I could access it by http://claude.wtf).

I just copied the docker-copose.yml file:

https-portal:
  image: steveltn/https-portal
ports:
  - '80:80'
  - '443:443'
environment:
  DOMAINS: 'example.com'
  PRODUCTION: 'true'

And I changed the example.com by claude.wtf.
When I run the command docker-compose up -d, I don't have any errors, all seems to work well:

Name                 Command   State                  Ports                   
--------------------------------------------------------------------------------
root_https-portal_1   /init     Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp 

But if I try to access https://claude.wtf/ with curl I get this error: Failed to connect to claude.wtf port 443: Connection refused.

In order to avoid this error, I have done:

iptables -A INPUT -p tcp -m tcp --sport 443 -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT 

And I don't seem to have any firewall activated since sudo ufw status verbose gives Status: inactive.

What could I have forgotten, or what am I doing wrong?
Thanks for your responses ;)

**Comment by SteveLTN** [comment]
Hi, you can try `docker-compose up` first, without `-d`, this will display all infos. Can you show me the output there?

And you can perhaps also try to access 443 port from your VPS, to see if it responds.

**Comment by ticketapp** [comment]
Thanks for your response, I'm brand new to Docker so  I never gave a thought to not using the -d option... The only errors that seem to output are: 
ValueError: Wrote file to /var/www/challenges/ktiu9PeSWE1dz87lOIlHgW0MXjywjpc1wRNYsF5aMGE, but couldn't download http://claude.wtf/.well-known/acme-challenge/ktiu9PeSWE1dz87lOIlHgW0MXjywjpc1wRNYsF5aMGE
Failed to obtain certs for claude.wtf

**Comment by ticketapp** [comment]
I finally managed to make it work with inter alia some iptables commands. I tried a lot of things so I'm not exactly sure of what worked. Anyway thanks for your help ;)

**Comment by SteveLTN** [comment]
The error message you had is because Let's Encrypt wants to verify you own the domain, so we will put some files under a specific path. Apparently Let's Encrypt failed to obtain that file, probably it's because port 80 is not accessible.

Glad that you figured that out. I'm closing this issue.

**Comment by ticketapp** [comment]
Hi, I have set several server hosted on Digital Ocean with your https solution and it worked well, thanks for that! But now, I'm trying to reset it on a OVH VPS and I get exactly the same error than before, to know :  ValueError: Wrote file to /var/www/default/challenges/zuPRHbc3PojPI98UzYaDJe48Zanjp6b0eG_Yomw-U_0, but couldn't download http://ceze-canoe.com/.well-known/acme-challenge/zuPRHbc3PojPI98UzYaDJe48Zanjp6b0eG_Yomw-U_0.

After hours of trying a lot of commands, I don't find any solution, so I come back here. Do you have any idea about what can I do in order to make it work?

**Comment by SteveLTN** [comment]
Is the DNS set correctly? And the servers port 80 is open to public?

**Comment by ticketapp** [comment]
Thanks for your response. Yes the DNS is set correctly. The command nmap -sT -O localhost does not show a line with port 80, so I think that indeed the port 80 is not open to public but the command iptables -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT does not change anything, do you maybe know what can I do?

**Comment by SteveLTN** [comment]
Is there any firewall settings from your server provider? I know AWS has
this security group thingy.

**Comment by ticketapp** [comment]
sudo ufw status verbose gives Status: inactive so I don't think so.

**Comment by SteveLTN** [comment]
It's not necessary available in the system. It could be another layer
before the system, that the OS is not aware of.

**Comment by ticketapp** [comment]
Ok, do you know how can I know it?

**Comment by SteveLTN** [comment]
I don't. Usually you have a config page on your bps management web page, if
it has one?

**Comment by ticketapp** [comment]
Ah ok, so it does not come from this, since I tried to make it work on a similar VPS (in January when I first post my issue here) configuring only by ssh. I think that I'm going to use a Digital Ocean server since I have no idea of how I managed to make it work. Thanks for the time you took!

**Comment by SteveLTN** [comment]
No worries.
