### ISSUE TITLE
[Question] How can I https the origin and the subdomain?

### ISSUE THREAD

**Issue by dc232** [SteveLTN/https-portal#112]
Hi I have an origin domain as vinsonjewellers.com and a subdomain as www.vinsonjewellers.com
I was wondering if I use the code below would I then get https on both 
vinsonjewellers.com and  www.vinsonjewellers.com?

https-portal:
  # ...
  environment:
    STAGE: production
    DOMAINS: 'vinsonjewellers.com => www.vinsonjewellers.com' 

I was also wondering if its possible to create a wildcard certificate using this docker container?

**Comment by SteveLTN** [comment]
No. `DOMAINS: 'vinsonjewellers.com => www.vinsonjewellers.com'` will only https vinsonjewellers.com and www.vinsonjewellers.com will not be managed by HTTPS-PORTAL in this case.

You can do  `DOMAINS: 'vinsonjewellers.com => www.vinsonjewellers.com', www.vinsonjewellers.com -> <your upstream>` to get certificates for both vinsonjewellers.com and www.vinsonjewellers.com.

Let's Encrypt doesn't support wildcard certficates yet. https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html

**Comment by Bessonov** [comment]
I think the proper way would be to allow get certs on the fly like in https://github.com/GUI/lua-resty-auto-ssl. I can imagine to use nginx`s [server_name](http://nginx.org/en/docs/http/server_names.html) syntax for that:
1. Exact domain name: "example.com" -> get cert on start like now
2. (Optional, but special): ".example.com" -> get cert only for example.com on start
3. All others matches try to get on the fly.

By matches I mean only if request match given regular expression like "^(?<user>.+)\.example\.com$" or wildcard "*.example.com".

Or, well, get all certs on the fly.

What do you think about it, @SteveLTN?

**Comment by SteveLTN** [comment]
I’m afraid it is too easy to hit let’s encrypt rate limit this way. Anyway
wildcard support of LE should come soon. I’d say we see how to utilize that
after.

**Comment by Bessonov** [comment]
> I’m afraid it is too easy to hit let’s encrypt rate limit this way.

Yeah, and because of that I suggest to request certs only for matching locations :)

> Anyway wildcard support of LE should come soon. I’d say we see how to utilize that

Agree :+1:
