### ISSUE TITLE
ip not found (in logs)

### ISSUE THREAD

**Issue by gdbjohnson** [SteveLTN/https-portal#113]
Hey Steve,

I'm noticing this error in the startup logs:

https-portal_1  | [cont-init.d] 10-setup: executing...
https-portal_1  | sh: 1: /sbin/ip: not found

When I enter the container, the ip command doesn't seem to be installed: "which ip" returns nothing.

Not sure if this is important or not, but an easy fix would be to put it into the image.

**Comment by gdbjohnson** [comment]
nvm... looks like you have it in your Dockerfile.  Maybe I need to repull mine...

**Comment by gdbjohnson** [comment]
ok, I see what happened.  I have it specified in my compose file to version 1.2, which i expected to be updated to the latest subversion 1.2.3.  This must have been an existing issue in 1.2.0.

Using "latest" fixed the issue.

**Comment by SteveLTN** [comment]
Yeah, I do remember fixing it before. It was once removed from the base image I use. 1.2 should be linked to 1.2.3 when I update it. If you just pull the latest 1.2 it would also work.
