### ISSUE TITLE
file size upload limit introduced by https-portal?

### ISSUE THREAD

**Issue by digitalwannabe** [SteveLTN/https-portal#115]
hey,

thanks @SteveLTN for this tool, very convenient!

We're using it with a synology nas and running into problems, but can't figure out where they are coming from:

When accessing our nas in win explorer/mac finder via webDAV(http over port 1233, https over 1234),, either via our own dns server at https://nas.mydomain.com:1234 or via a dns service at eg https://mydomain.synology.me:1234, everything works as expected.
However, when we set up https portal to handle certificates (doing nas.mydomain.com -> http://dockerhost:1233), we can mount https://nas.mydomain.com in explorer/finder, but we are not able to upload any file larger than ~1Mb, with an error saying file size exceeds the limit.

Now to my understanding- no web pro- there is nothing in https-portal which could cause this....but maybe someone has an idea where the problem could be coming from? As the only thing we are changing is switching from our own dns server and handling our certificates manually to using https portal, it's got to have something to do with it. Switched it back and forth to confirm.

Any hints much appreciated! Thank you

**Comment by SteveLTN** [comment]
Hi,

Unfortunately it is exactly HTTPS-PORTAL causing this issue :-(

Check out [this section](https://github.com/SteveLTN/https-portal#configure-nginx-through-environment-variables) in the documentation, the variable `CLIENT_MAX_BODY_SIZE` controls the single request limit of Nginx. The default value is 1M. Change it by adding another environment variable, set it to a large enough value should solve your problem.

**Comment by SteveLTN** [comment]
Ah, maybe `0` is even better because it disables file size checking completely.

**Comment by digitalwannabe** [comment]
hi, thanks for the quick response! I have actually tried setting this very high already, but to no effect...will try to set it to 0 and report back! thanks

**Comment by digitalwannabe** [comment]
Works! Great, thank you! Maybe there's a bug when setting a specific size limit, only tried a high value of ~8000MB though....but setting it to 0 is fine for me! thanks a lot

**Comment by SteveLTN** [comment]
It should be 8000M without B. But glad to hear it works!

**Comment by digitalwannabe** [comment]
ah, only put the value 8000 in...understood, thanks!

**Comment by iCUE-Solutions** [comment]
@petrk94 

did you ever figure out in what file the setting needs to end? I logged into the running https-portal container, edited ALL nginx.conf files I could find and also the once that are created per domain, RESTARTED the container BUT no effect?

**Comment by jeverling** [comment]
Hi, the value should go into your `docker-compose.yml` file, e.g.

```
    CLIENT_MAX_BODY_SIZE: 2000M
```
