### ISSUE TITLE
Mitigations for Existing TLS-SNI Users

### ISSUE THREAD

**Issue by dachary** [SteveLTN/https-portal#117]
Hi,

Is https-portal impacted by this breaking change ?

https://community.letsencrypt.org/t/2018-01-11-update-regarding-acme-tls-sni-and-shared-hosting-infrastructure/50188

Thank in advance for your reply

**Comment by SteveLTN** [comment]
Hi!

Not that I know of! If you found it not working, open this issue again. It's more of my upstream tool, acme-tiny.py, so I would update acme-tiny if someone reports it not working.
