### ISSUE TITLE
Two apps sharing their SSL cert

### ISSUE THREAD

**Issue by gdbjohnson** [SteveLTN/https-portal#119]
Hey Steve et al,

Not sure if this has come up already, but is there an easy way for two apps to share their SSL cert?  I want to do a 301 from one app to the other, but I'm getting a security warning because the certificate is different between the two apps.

 I was playing with the idea of exposing the certificates folder, and manually creating the cert for the two apps here, but I'm not sure if that will confuse https-portal.  Any tips on the best way to achieve this?

Greg

**Comment by SteveLTN** [comment]
What do you mean by "two apps sharing the same certificate"? If they are on two domains, they will have one certificate each.

**Comment by gdbjohnson** [comment]
I have two applications on the same domain.  

Loosely described, it is:
1) example.com -> static html website in it's own docker container
2) blog.example.com -> a wp application

Each of the above are on their own SSL cert based on the portal's normal process.

Now I'm migrating blog.example.com to be example.com/blog, because of an SEO requirement.

On blog.example.com, I wrote a 301 to example.com/blog, but I'm getting a chrome error because the SSL changed, but realistically, it's the same domain.  It's a terrible user experience that can be avoided if both applications use the same SSL cert.

**Comment by SteveLTN** [comment]
No, it doesn't work this way.

301 redirection simply tells the browser to visit another URL. Then the browser checks the certificate again. 

Chrome wouldn't complain if you have `example.com/blog` using `example.com` cert, and `blog.example.com` using `blog.example.com` cert. 

Which URL do you want your WP site to be on? `https://example.com/blog` or `https://blog.example.com`?

**Comment by SteveLTN** [comment]
If you do a 301 from `blog.example.com` to `example.com/blog`, it is like this:

Chrome go to `https://blog.example.com`, verify the cert of `blog.example.com`, then it sees a 301 redirection. Then you will see the Chrome address bar changes to `https://example.com/blog`. Then Chrome verifies the cert for `example.com`, just as if you typed `https//example.com/blog` in the address bar by yourself.

**Comment by gdbjohnson** [comment]
Yes it mostly works as you describe, but it "fails" on the first time you do it because chrome presents a scary warning that the certificate is different, preventing a seamless experience.  This article describes it a bit.

http://www.jasonsamuel.com/2011/03/07/how-to-properly-use-ssl-redirects-without-getting-certificate-error-messages/

If both the domain and subdomain share their certificate, then there is no warning, which is what I am trying to achieve. 

Wondering what you think would be the best way?

**Comment by SteveLTN** [comment]
> If both the domain and subdomain share their certificate, then there is no warning, which is what I am trying to achieve.

That's not how it works. If both the domain and subdomain share their certificate, and for Let's Encrypt a certificate only matches one domain, you'll see a warning on at least one of them. `example.com` and `blog.example.com` are two different domains hence they **SHOULD HAVE DIFFERENT CERTIFICATES**.

Now, to do so, just configure the environment to do the redirection:
```
environment:
  DOMAINS: 'blog.example.com => example.com/blog, example.com -> <YOUR UPSTREAM>'
```

**Comment by SteveLTN** [comment]
>  but I'm getting a security warning because the certificate is different between the two apps.

You don't get a warning when two apps have different certificates. You get a warning when the domain written in the certificate is different from the one your try to visit.

**Comment by gdbjohnson** [comment]
Let's encrypt supports multiple domains for a cert... not that I've ever done it.
https://community.letsencrypt.org/t/host-multiple-domains-with-a-single-certificate/20917

I will try setting the DOMAINS environment var as you suggest above to see if that creates the redirection that I am looking to achieve without the ssl warning...

**Comment by SteveLTN** [comment]
You are right. LE supports SAN certificate. But HTTPS-PORTAL doesn't because it requires complex configuration, and the purpose of HTTPS-PORTAL is to avoid complex configuration.

Remember, we are talking about two apps now. 

1. Your blog, which is Wordpress, running under `example.com/blog`. You need to configure your WP to do so.
2. A redirection app, running under `blog.example.com`. HTTPS-PORTAL has built-in support for it. Just use `blog.example.com => example.com/blog`.

Each app needs its own certificate. 

Good luck!

**Comment by gdbjohnson** [comment]
ok.. I guess what I'm reading is that I don't even need the redirection
that I'm trying to do.  I didn't understand what your arrow syntax did...
I'll give that a try and let you know how it goes.

**Comment by gdbjohnson** [comment]
What are the outputted nginx config rules using the above syntax, and to what file?
Ie: `blog.example.com => example.com/blog`?

I assume that it would write any rules to `example.com.ssl.config`, but I didn't see it.  I'm also using the Container Discovery method, so perhaps this is conflicting?

**Comment by SteveLTN** [comment]
It would be written to blog.example.com.ssl.config.  It is simply an 301
redirection to example.com/blog.

You are configuring blog.example.com to do a 301 redirection here.
Example.com does not need to know the existence of the redirection at all.

**Comment by n006** [comment]
I think I am running into a similar problem. 
Chrome says: NET::ERR_CERT_COMMON_NAME_INVALID
What am I doing wrong, my domains part looks as follows:


    DOMAINS: 
        'example.com => www.example.com,
        www.example.com -> http://wordpress,
        gitlab.example.com -> http://gitlab,
        data.example.com -> http://owncloud,
        analyse.example.com -> http://piwik,
        stuff.example.com,

        example2.com => www.example2.com,
        www.example2.com -> http://wordpress2,

        example3.com => www.example3.com,
        www.example3.com,

        example4.com => www.example4.com,
        www.example4.com'


Thank you, you're doing a great job Steve.
Paul

**Comment by SteveLTN** [comment]
@n006 I don't see any issues on your DOMAINS config. Can you reduce the number of domains and try to narrow down the issue? Can you also try to visit each domain you listed, and see the abnormality of the faulty certificate from Chrome dev tools?

For rate limiting, I think we'll have a better way to handle it when Let's Encrypt's wildcard certs are ready.

@gdbjohnson @n006 I set up a sample config:

```yaml
    environment:
      DOMAINS: 'test.steveltn.me, 
        foo.steveltn.me => bar.steveltn.me, 

        bar.steveltn.me'
      STAGE: production
```

**Comment by n006** [comment]
I've reduced it to this

```
   DOMAINS: 
    'example.com => www.example.com,
    www.example.com -> http://wordpress,

    example2.com => www.example2.com,
    www.example2.com -> http://wordpress2,

    example3.com => www.example3.com,
    www.example3.com,

    example4.com => www.example4.com,
    www.example4.com'
```
For example3.com chrome says

> This webpage is not available
> _ERR_SPDY_PROTOCOL_ERROR_

example2.com redirects to www.example2.com and chrome says:

>  NET::ERR_CERT_COMMON_NAME_INVALID
> 
>  This server could not prove that it is www.example.com; its security certificate is from 
>  example2.com. This may be caused by a misconfiguration or an attacker intercepting 
>  your connection.

That is what I get for all other domains as well.


Could also be I am running into quota issues.

**Comment by SteveLTN** [comment]
@n006 That is weird. You are redirected to www.example2.com but it serves the certificate of example2.com? What does the Chrome address bar say? What does Chrome certificate inspector say about the certificate?

**Comment by n006** [comment]
Ok I've tried a lot and got everything up and running in staging. (There was a linking and db fuckup) But, as soon as I switch to production things just do not work anymore. I'll wait for a week to ensure quota issues are not the problem and will write as soon as I got more infos. Thank you so far.

**Comment by SteveLTN** [comment]
Don’t forget to put environment variable force_renew on when necessary. But
that might  make your quota issue more prominent…

**Comment by SteveLTN** [comment]
Since you haven't replied in a long time, I'm closing this issue. Feel free to reopen.
