### ISSUE TITLE
nginx listen port configuration in default template

### ISSUE THREAD

**Issue by hd-deman** [SteveLTN/https-portal#12]
make it more configurable

**Comment by SteveLTN** [comment]
Any more specific suggestions?

**Comment by SteveLTN** [comment]
We do have a plan for that.

But so far Let's Encrypt requires to use port 80 to verify the domain belongs to you, so even if we serve the content from other ports, 80 is still needed by HTTPS-PORTAL.

**Comment by hd-deman** [comment]
yes, of course it's clean. In my case I just want to put it behind aws elb and in some cases I can't use a standard ports.

**Comment by SteveLTN** [comment]
I would like to make it support other ports. However Let's Encrypt doesn't support ports other than 80, so I can't do anything about it.

**Comment by SteveLTN** [comment]
I'm closing the issue for now. Feel free to reopen it.

BTW I just realized if you want to use ELB to proxy port 80, you can have HTTPS-PORTAL running on any other port by saying
```
  ports:
    - "8080:80"
    - "4343:443"
```
in `docker-compose.yml`. But you need to somehow proxy port `80` on your host to your exposed port.
