### ISSUE TITLE
Docker image for 1.2.3

### ISSUE THREAD

**Issue by lucj** [SteveLTN/https-portal#120]
Hello,
I noticed the docker image with tag 1 is newer than the 1.2.0.
Also, will you build an image for 1.2.3 ?
Great tool, thanks a lot.
Luc

**Comment by SteveLTN** [comment]
Yeah, I started a build. But I recommend you to just use 1.2 since the patch version is for bug fixes. You are not supposed to stick to a patch version.

**Comment by lucj** [comment]
ok, got it.
Thanks
