### ISSUE TITLE
Support for Wildcard-Certificates

### ISSUE THREAD

**Issue by aumayr** [SteveLTN/https-portal#122]
@SteveLTN How hard is it to implement support for wildcard certificates, as Let's Encrypt supports them as of yesterday?

Announcement by LE: https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

\CC #112

**Comment by SteveLTN** [comment]
I’m planning.

**Comment by SteveLTN** [comment]
See #123 . I'm closing this now.
