### ISSUE TITLE
2.0 release plan

### ISSUE THREAD

**Issue by SteveLTN** [SteveLTN/https-portal#123]
This is my current plan for 2.0 release:

* Wildcard support
* Look into the possibilities to send emails if things are wrong

**Comment by bhargav3** [comment]
Great project Steve. Thanks!

**Comment by SteveLTN** [comment]
ACME v2 requires to use DNS challenge. That means we need to ask the users to set up the DNS manually. Do you think it's worth it? After all, the project itself is to make certificate signing easy. If you need to add records to DNS, there would be a lot of work, maybe you would want to use LE's own tools for that.

**Comment by wiserain** [comment]
how much is the configuration complicated? multiple steps of manual and interactive user command is necessary for the setup? I don't really need wildcard for now.

**Comment by SteveLTN** [comment]
@wiserain At a point you need to go to your DNS provider to manually set some txt record. The problem is apparently you need to do it every time you renew the certificate. That seems tedious.

**Comment by Chenyao2333** [comment]
How about this [amce.sh/dnsapi](https://github.com/Neilpang/acme.sh/tree/master/dnsapi). I think you can reuse this part. But anyway, I do not really need wildcard at this time.

**Comment by SteveLTN** [comment]
I know this repo. But I think if you have to get your keys from your DNS
provider and configure it in HTTPS-PORTAL, it would already be a bit
complicated. You might just want to manage everything by yourself if you
have already invested so much time in it.
