### ISSUE TITLE
Swarm stack support for automatic discovery

### ISSUE THREAD

**Issue by Olvikolvi** [SteveLTN/https-portal#125]
Is it possible to use automatic container discovery when using swarm mode?
I'am starting services using stack deploy..
`docker stack deploy -c wp.yml wordpress
`
..and if container is not starting in same server where https-portal is nothing happens.
docker.sock output on https-portal node when creating one:
`{"Type":"service","Action":"create","Actor":{"ID":"123123123123","Attributes":{"name":"wordpress"}},"scope":"swarm","time":1521812692,"timeNano":1521812692922990660}
`

**Comment by SteveLTN** [comment]
I'm afraid it is not possible. The underlying library, docker-gen, relies on each Docker's socket on each individual instance, and it doesn't support swarm mode.
