### ISSUE TITLE
My certificate failed to renew with the below error

### ISSUE THREAD

**Issue by shuat** [SteveLTN/https-portal#126]
My certificate did not auto-renew. Also when I tried doing a docker-compose up https-portal I get the following error.

https-portal_1       | fix-attrs.d] applying owners & permissions fixes...
https-portal_1       | [fix-attrs.d] 00-runscripts: applying...
https-portal_1       | [fix-attrs.d] 00-runscripts: exited 0.
https-portal_1       | [fix-attrs.d] done.
https-portal_1       | [cont-init.d] executing container initialization scripts...
https-portal_1       | [cont-init.d] 00-welcome: executing...
https-portal_1       |
https-portal_1       | ========================================
https-portal_1       | HTTPS-PORTAL v1.2.4
https-portal_1       | ========================================
https-portal_1       |
https-portal_1       | [cont-init.d] 00-welcome: exited 0.
https-portal_1       | [cont-init.d] 10-setup: executing...
https-portal_1       | 2018/04/02 01:51:35 [notice] 135#135: signal process started
https-portal_1       | Signing certificates from https://acme-v01.api.letsencrypt.org ...
https-portal_1       | Parsing account key...
https-portal_1       | Parsing CSR...
https-portal_1       | Registering account...
https-portal_1       | Already registered!
https-portal_1       | Verifying *****.com...
https-portal_1       | ******.com verified!
https-portal_1       | Signing certificate...
https-portal_1       | Traceback (most recent call last):
https-portal_1       |   File "/bin/acme_tiny", line 198, in <module>
https-portal_1       |     main(sys.argv[1:])
https-portal_1       |   File "/bin/acme_tiny", line 194, in main
https-portal_1       |     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
https-portal_1       |   File "/bin/acme_tiny", line 161, in get_crt
https-portal_1       |     raise ValueError("Error signing certificate: {0} {1}".format(code, result))
https-portal_1       | ValueError: Error signing certificate: 500 {
https-portal_1       |   "type": "urn:acme:error:serverInternal",
https-portal_1       |   "detail": "Error creating new cert",
https-portal_1       |   "status": 500
https-portal_1       | }

**Comment by SteveLTN** [comment]
Hi, just remember to update https-portal to the latest version. Sometimes they change things a bit :-).

But in this case, it looks like some issues from LE. I'm never seen 500 returned from them.
