### ISSUE TITLE
how to redirect to some port

### ISSUE THREAD

**Issue by ruandao** [SteveLTN/https-portal#127]
i need redirect to some port and then forward to my desktop computer for develop test

**Comment by ruandao** [comment]
i find it:
    DOMAINS: 'example.com -> http://dockerhost:8080'

**Comment by ruandao** [comment]
i accept https://domain/ecard/openid .  the docker log show something inclue
`upstream: "http://172.17.0.1:8080/ecard/openid"` . 
but my server's IP was 172.24.94.14 . 
Was  172.17.0.1 the docker's ip ?

**Comment by SteveLTN** [comment]
Yes.
172.16.0.0 – 172.31.255.255 is reserved for LAN, and Docker uses 172.* to communicate across containers.

**Comment by ruandao** [comment]
thank you!
