### ISSUE TITLE
Error undefined method chained_cert_path

### ISSUE THREAD

**Issue by wiserain** [SteveLTN/https-portal#130]
I think v1.2.5 has some bug, as follows:

```
https         | 2018/04/25 03:11:38 [notice] 152#152: signal process started
https         | (erb):6:in `get': undefined method `chained_cert_path' for #<Domain:0x0055c6c8fc7198> (NoMethodError)
https         |         from /usr/lib/ruby/2.3.0/erb.rb:864:in `eval'
https         |         from /usr/lib/ruby/2.3.0/erb.rb:864:in `result'
https         |         from /opt/certs_manager/lib/erb_binding.rb:24:in `compile'
https         |         from /opt/certs_manager/lib/nginx.rb:47:in `compiled_domain_config'
https         |         from /opt/certs_manager/lib/nginx.rb:20:in `block in config_ssl'
https         |         from /opt/certs_manager/lib/nginx.rb:19:in `open'
https         |         from /opt/certs_manager/lib/nginx.rb:19:in `config_ssl'
https         |         from /opt/certs_manager/certs_manager.rb:65:in `block (2 levels) in ensure_signed'
https         |         from /opt/certs_manager/certs_manager.rb:51:in `each'
https         |         from /opt/certs_manager/certs_manager.rb:51:in `block in ensure_signed'
https         |         from /opt/certs_manager/certs_manager.rb:75:in `block in with_lock'
https         |         from /opt/certs_manager/certs_manager.rb:73:in `open'
https         |         from /opt/certs_manager/certs_manager.rb:73:in `with_lock'
https         |         from /opt/certs_manager/certs_manager.rb:50:in `ensure_signed'
https         |         from /opt/certs_manager/certs_manager.rb:19:in `setup'
https         |         from /etc/cont-init.d/20-setup:4:in `<main>'
https         | [cont-init.d] 20-setup: exited 1.
```

If this is only for me, can you give advice for troubleshooting?

**Comment by SteveLTN** [comment]
Hi,

My bad. In 1.2.5, I deleted `chained_cert_path` because LE will chain the path by itself, so there is no need to chain by us. However I should make it fallback nicely incase you already have a generated file. I'll fix it very soon.

Sorry for the inconvenience.

**Comment by SteveLTN** [comment]
Hi, 1.2.6 is being built on Dockerhub now. Will be available soon.

**Comment by wiserain** [comment]
Thanks for your quick response. I will update ```chained_cert_path``` in my custom ```nginx-conf/*.conf.erb``` files as advised.

**Comment by mkonersmann** [comment]
As long as the new version is not available in the hub, you can use a one-liner as workaround:
`find . -name *.ssl.conf.erb -exec sed -i.bak 's/chained_cert_path/signed_cert_path/g' {} \;`

**Comment by SteveLTN** [comment]
Dockerhub is somehow stuck :-(. Just use 1.2.4 for now.

**Comment by wiserain** [comment]
Um... I don't know how to deal with this, one of my nginx.conf depends on chained cert. 
```
[warn] 239#239: "ssl_stapling" ignored, issuer certificate not found for certificate "/var/lib/https-portal/my.website.com/production/signed.crt"
```

**Comment by SteveLTN** [comment]
@wiserain Have you pulled 1.2.6? In 1.2.6, `chained_cert_path` falls back to `signed_cert_path`, it should just work like before.

**Comment by wiserain** [comment]
@SteveLTN I have OCSP stapling enabled in one of my nginx.conf, which requires full certificates chain to be available to the server. However, as you explained, the latest 1.2.6 doens't seem to provide chained certs, and that's why I have the above warning. I am looking for workarounds now :)

**Comment by SteveLTN** [comment]
@wiserain According to [ACME-tiny](https://github.com/diafygi/acme-tiny#step-6-setup-an-auto-renew-cronjob), ACME v2 would include the chained certificate as its result. If you find that is not the case, let me know.

**Comment by wiserain** [comment]
@SteveLTN Yes, right. After forced renewing, I checked ```signed.crt``` includes contents of ```intermediate.pem``` in it, formerly ```chained.pem``` available for OCSP stapling. Thanks for the tips!

**Comment by SteveLTN** [comment]
Great!
