### ISSUE TITLE
Multiple apps on same domain

### ISSUE THREAD

**Issue by htafolla** [SteveLTN/https-portal#134]
I am having trouble setting up multiple apps on the same domain.  I am looking to setup Wordpress as one app and then have Express as a second app for API calls when the location is "/api". 
https-portal:
      ...
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - STAGE=${STAGE} 
      #- DOMAINS=examples.com -> http://wordpress # not needed according to docs
wordpress:
      ...
      environment:
      VIRTUAL_HOST: example.com
express:
     ...
      environment:
      VIRTUAL_HOST: example.com

Is this possible? Or do I need to do my own proxying in the default.ssl.conf.erb?

**Comment by SteveLTN** [comment]
Unfortunately you can't do this without providing your own Nginx config. Please check the document t o see how to do that.
