### ISSUE TITLE
Site is now untrusted in some browsers and apps

### ISSUE THREAD

**Issue by njgage** [SteveLTN/https-portal#136]
The SSL verification on our api server is flagging an issue with a missing/broken intermediate/chain certificate. No changes have been made to the docker-compose.yml file for 12mths+ and it seems to be a recent problem. I can see in the https-portal commits that a few changes have been made related to chaining so wondering if this is an issue.

I get the following output running: echo | openssl s_client -connect api.littlescribe.com:443 -servername api.littlescribe.com 2>/dev/null | awk '/Certificate chain/,/---/'

Certificate chain
 0 s:/CN=api.littlescribe.com
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3

This seems to suggest a missing certificate and is consistent with: https://www.sslshopper.com/ssl-checker.html#hostname=api.littlescribe.com (see screenshot below).

In /var/lib/https-portal/api.littlescribe.com/production/ I have 4 files: chained.pem, domain.csr, domain.key and signed.crt. Chained.pem contains the content of signed.crt plus /var/lib/https-portal/intermediate.pem (signed.crt first and then intermediate.pem).

Any ideas how to fix up the missing cert from the chain?

Thanks,
Nick

![image](https://user-images.githubusercontent.com/3724600/40771588-19be25f8-6501-11e8-9da4-8e5896a238b7.png)

**Comment by njgage** [comment]
Hi, thanks for looking at this so quick. I just thought I'd let you know I
had to do a force renew even after pulling 1.2.9 but after the renew it did
then fix the issue.

Cheers,
Nick

**Comment by SteveLTN** [comment]
Thanks for the follow-up!
