### ISSUE TITLE
Question: How to do a redirect from "www.mydomain.com" to "mydomain.com"?

### ISSUE THREAD

**Issue by brainlid** [SteveLTN/https-portal#137]
Following the "Redirections" section of the README, I'm currently trying this:

```
      DOMAINS: 'mydomain.com -> http://wordpress, www.mydomain.com => mydomain.com'
```

I don't want "http://www.mydomain.com" to work. I would like it to redirect to "http://mydomain.com".

I get this in the docker logs...

```
Found domains: www.mydomain.com
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying www.mydomain.com...
Traceback (most recent call last):
  File "/bin/acme_tiny", line 197, in <module>
    main(sys.argv[1:])
  File "/bin/acme_tiny", line 193, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "/bin/acme_tiny", line 149, in get_crt
    raise ValueError("Challenge did not pass for {0}: {1}".format(domain, authorization))
[...]
================================================================================
Failed to sign www.mydomain.com, is DNS set up properly?
================================================================================
Failed to obtain certs for www.mydomain.com
2018/06/05 00:59:14 [notice] 163#163: signal process started
[cont-init.d] 20-setup: exited 0.
[cont-init.d] 30-set-docker-gen-status: executing... 
[cont-init.d] 30-set-docker-gen-status: exited 0.
[cont-init.d] done.
[services.d] starting services
```

It works fine when I just have ```DOMAINS: 'mydomain.com -> http://wordpress'```

Am I just doing it wrong? Currently `https://www.mydomain.com` doesn't resolve or display.

Any help or tips you can provide are greatly appreciated!

**Comment by brainlid** [comment]
Sorry. Worked it out on my end. DNS issues.

**Comment by Harti** [comment]
@brainlid "DNS issues" doesn't help me troubleshoot *what* may be wrong with my DNS configuration. Mind elaborating? Thanks!

**Comment by brainlid** [comment]
It was totally on my side. Your side was fine! Thanks for following up.

**Comment by Harti** [comment]
I'm not the repo maintainer. I'm another developer stuck with this message and want to know what you did to fix it.

**Comment by brainlid** [comment]
@Harti Ah! Didn't pay attention. 

My issue was I needed to set up "www" in my DNS settings where my domain had the nameservers configured. I needed to create an "A" record with the "www".domain.com setup that was an alias to my non-www domain. At least that's what I did in AWS' Route53. I believe the alias feature there is not standard and a feature of Route53 tho. Uncertain.

Hope that helps!

**Comment by SteveLTN** [comment]
Would you like to share your current configuration and DNS setup?

**Comment by Harti** [comment]
Found the culprit: `* 1800 IN CAA 0 issue "letsencrypt.org."`

Even though I believe that might be a useful DNS entry to have in general (or at least the Internet told me that), after removing it, the certificate got signed properly.

@SteveLTN thank you so much for creating this repository, and for offering assitance when someone's server is burning! You can't believe how much I raged at nginx-proxy's setup and yours *just works*.
The only issue I'm still having revolves around a dockerized mail server with a webmail frontend using its own certificate, but I'll figure it out eventually (or ask the community if not).

**Comment by brainlid** [comment]
Here is part of my `docker-compose.yml` file. This brings up a self-hosted wordpress site.

```yaml
version: '3.3'

services:
  https-portal:
    container_name: ${CONTAINER_HTTPS_PORTAL}
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - wordpress
    depends_on:
      - wordpress
    restart: unless-stopped
    environment:
      # Forward wordpress.example.com to the WordPress container.
      # You can set up multiple domains at once. (comma separated)
      # NOTE: redirections are done using "=>"
      DOMAINS: 'mydomain.com -> http://wordpress, www.mydomain.com => mydomain.com'

      # Using staging server by default, for there is a rate limit on production.
      # Set to 'production' to use Let's Encrypt production server.
      STAGE: 'production'
      # FORCE_RENEW: 'true'
      # Changes the file upload size allowed in nginx
      CLIENT_MAX_BODY_SIZE: 100M
```
DNS: by AWS Route53

Name | Type | Value
---------|--------|---------
www.mydomain.com. | A | ALIAS mydomain.com.
