### ISSUE TITLE
Container found by container discovery are not using production server for certificate

### ISSUE THREAD

**Issue by lidonis** [SteveLTN/https-portal#14]
I always have a certificate form staging api when a container is discovered.
`Signing certificates from https://acme-staging.api.letsencrypt.org`

**Comment by SteveLTN** [comment]
Even with environment variable `PRODUCTION=true` ?

**Comment by lidonis** [comment]
Sorry, i forgot to mention that i have `PRODUCTION=true`

I have something like this

```javascript
https-portal:
  image: steveltn/https-portal
  ports:
    - '80:80'
    - '443:443'
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
  restart: always
  environment:
    DOMAINS: 'example.com'
    PRODUCTION: 'true'
```

```javascript
wordpress:
  image: wordpress
  links:
    - db:mysql
  environment:
    VIRTUAL_HOST: blog.example.com
    VIRTUAL_PORT: '80'

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: '<a secure password>'
```

**Comment by lidonis** [comment]
I think i fixed the problem when i removed the old volume of the https-portal container but i can't be sure because i have exceeded the rate limit for production certificate.

**Comment by SteveLTN** [comment]
That's strange.

See [here](https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/opt/certs_manager/models/domain.rb#L26-L32), the staging certs will be stored in a different place. 

Anyway, feel free to reopen the issue if you encounter further problems.

**Comment by SteveLTN** [comment]
Hi, this is indeed a bug. Thank you for point it out, and sorry for this.

It is fixed in [this commit](https://github.com/SteveLTN/https-portal/commit/3016fbb0d40970c8b82756738fdd8cc9ce8f9bc4). Please pull the latest branch.

**Comment by lidonis** [comment]
I ma glad you were able to fix it.
Thank you for your work. You saved me a lot of time by sharing it.

**Comment by SteveLTN** [comment]
No problem.
