### ISSUE TITLE
Best way to integrate Hugo static site with oauth2_proxy into this container's setup?

### ISSUE THREAD

**Issue by shah** [SteveLTN/https-portal#141]
Hi @SteveLTN this looks like a great setup. I was looking to run a Hugo static site with oauth2_proxy setup with your container configuration. Is there any documentation or discussion about how that might be possible? Thanks!

**Comment by SteveLTN** [comment]
Sorry, I'm not familiar with either Hugo or oauth2_proxy. You might want to start with Hugo documentation?

**Comment by shah** [comment]
Thanks, @SteveLTN -- the real question is about [oauth2_proxy](https://github.com/bitly/oauth2_proxy) (a "reverse proxy that provides authentication with Google, Github or other provider"). Hugo is just a static site generator which creates HTML so it's just a normal nginx site. 

We've gotten oauth2_proxy to wrap a static site in an nginx VM but I was curious if you suggested a particulate approach for a container based setup.

**Comment by SteveLTN** [comment]
Not really, just putting oauth2_proxy in a Docker container would probably work?

**Comment by shah** [comment]
Agreed @SteveLTN I'll give that a shot. thanks.
