### ISSUE TITLE
Doesn't work on http sites with basic-auth

### ISSUE THREAD

**Issue by RonieGSS** [SteveLTN/https-portal#142]
Good Day @SteveLTN ,

I'm trying to redirect the site http://example.com (with basic-auth) to https://example.com but I keep on getting the following error:

 ``` u'error': {u'status': 403, u'type': u'urn:ietf:params:acme:error:unauthorized', u'detail': u'Invalid response from http://example.com/.well-known/acme-challenge/```

http://example.com requires basic authentication to pass through

I'm not really knowledgeable about Let's Encrypt but is there a way to convert an already authenticated http site to https?

I tried your basic-auth before, something like: `DOMAINS: 'foo:bar'@example.com -> http://example.com` but throws this error ` HTPASSWD: cannot create file /var/lib/https-portal/example.com/production/htaccess`

**Comment by SteveLTN** [comment]
Hi, how do you configure basic auth?

The correct way to configure basic auth is to do `DOMAINS: foo:bar@example.com -> YOUR_UPSTREAM'. 

You have an extra `'` before `@`, and your upstream is the same as your server domain.

**Comment by RonieGSS** [comment]
@SteveLTN Oh I'm sorry with the way I wrote it... it's actually like this `DOMAINS: foo:bar@example.com -> example.com`, it was throwing this kind of error `HTPASSWD: cannot create file /var/lib/https-portal/example.com/production/htaccess` ... so what I did to fix this was execute `docker exec -it "container_name" bash` then

```
cd /var/lib/https-portal/example.com/production/htaccess
htpasswd -c htaccess foo
```

then just entered the password `bar` when prompted twice

**Comment by SteveLTN** [comment]
But you did `example.com -> example.com`. You cannot set the upstream to itself, can you?

**Comment by RonieGSS** [comment]
@SteveLTN Actually it worked but I got the idea thanks

**Comment by wiserain** [comment]
Doesn't it work if domain has no upstream, e.g., vhosts?

**Comment by SteveLTN** [comment]
@wiserain Should still work. Probably doesn't work with automatic discovery.

**Comment by RonieGSS** [comment]
@SteveLTN Does this work now without using docker exec? Doesn't it throw this error anymore? 
```HTPASSWD: cannot create file /var/lib/https-portal/example.com/production/htaccess```

**Comment by wiserain** [comment]
@SteveLTN In my test, it doesn't work properly. I can watch log line of "Adding password blah blah ..." and see htaccess file created, but target is still accessible with no password. My ENV for DOMAINS is
```
DOMAINS=sub1.domain.com, id:passwd@sub2.domain.com, sub3.domain.com, ...
```
Is there something I missed?

**Comment by SteveLTN** [comment]
@wiserain Maybe, or maybe I made a mistake :-) Will have a look later.

**Comment by SteveLTN** [comment]
@wiserain I tried the same thing and it works for me. Is it possible that your browser remembers the username and password? Could you try with an incognito window?

**Comment by SteveLTN** [comment]
@RonieGSS OK. Stupid me. I didn't prepare the directory before trying to generate `htaccess` file. I never found it out because when I test myself, it's usually not the first time it's run, so it saves the folder from last run. Fixed and will be release in 1.4.0 soon.

**Comment by RonieGSS** [comment]
@SteveLTN Awesome man thanks, I'll wait for that release

**Comment by wiserain** [comment]
I was also stupid. I was overriding nginx configurations by bind mounting ```nginx-conf``` folder, and it hasn't been updated for a while. After adding code blocks related to basic_auth, it is now working as expected!
