### ISSUE TITLE
Multiple swarm replicas

### ISSUE THREAD

**Issue by simonp22** [SteveLTN/https-portal#143]
Hi, 
Thankyou for your work on this project.
Is there a way to get NGINX in this project to handle SSL termination as well as load balancing across a number of container replicas using swarm?

I would imagine the docker-compose config needs to be something like this but I cannot get it to work. Any ideas?

```version: '3.4'
services:
  website:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:9565
    deploy:
      replicas: 5
  https-portal:
    image: steveltn/https-portal:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - website
    restart: always
    environment:
      DOMAINS: "example.com -> http://website:9565"
      PRODUCTION: 'true'```

**Comment by SteveLTN** [comment]
Not that I know of. If swarm automatically load balances among several `website` containers, I believe it would work. Otherwise I don't think it works this way.

**Comment by simonp22** [comment]
Looks like it could be done quite easily, I might have a go at forking this repo and giving it a go. According to this source https://www.sep.com/sep-blog/2017/02/28/load-balancing-with-nginx-and-docker/  the following nginx.conf should work

``` 
http {
    sendfile on;
 
    upstream app_servers {
        server example_app_1:5000;
        server example_app_2:5000;
        server example_app_3:5000;
        server example_app_4:5000;
    }
 
    server {
        listen 80;
 
        location / {
            proxy_pass         http://app_servers;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }
    }
}```

**Comment by SteveLTN** [comment]
That's an interesting idea. How do you plan to configure it in the ENV?

**Comment by simonp22** [comment]
Maybe a new operator in the DOMAINS env? 
For example `DOMAINS: "example.com --> http://website:9565"` Note the double --

The idea is to have a setup as shown in https://docs.docker.com/engine/swarm/images/ingress-lb.png

but with Nginx performing LetsEncrypt SSL termination and loadbalancing in place of HAProxy

**Comment by simonp22** [comment]
This could make the https-portal project a very powerful tool

**Comment by SteveLTN** [comment]
I guess the only uncertainty is how to get the IP addresses from Docker Swarm. One we get a list of IPs, it's easy to put them into the Nginx configure. 

Please give it a shot. I would be happy to merge it :-)

Thank you!

**Comment by simonp22** [comment]
Having some trouble with some of the code, where in the container is nginx storing the conf file when it starts?

**Comment by SteveLTN** [comment]
Are you looking for these two files?

https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/var/lib/nginx-conf/default.conf.erb
https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/var/lib/nginx-conf/default.ssl.conf.erb

**Comment by SteveLTN** [comment]
And look at this section:
https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/opt/certs_manager/lib/nginx.rb#L2-L8

**Comment by simonp22** [comment]
Exactly what I was looking for, thanks. Will give this a go over the next day or so

**Comment by SteveLTN** [comment]
Closing this for now. Feel free to reopen :-)
