### ISSUE TITLE
Hybrid Setup with Non-Dockerized Apps

### ISSUE THREAD

**Issue by thomas126** [SteveLTN/https-portal#145]
Hi guys,
i am using mailcow and struggling to set it up with https_portal. I tried it directly but it didn't work. So I made it available at Dockerhost at port 8080. When accessing the ip:8080 I reach the site. While setting the container up with this value: "DOMAINS: 'mail.example.com -> http://dockerhost:8080'" I am frankly not able to access the site via the domain. It results in an 502 error.

**Comment by SteveLTN** [comment]
Could you first try `DOMAINS: 'mail.example.com` without the upstream, to make sure https listening is working?

**Comment by thomas126** [comment]
What do you exactly mean by that? How should I set it up? I got another site running Wordpress docker fine with https_portal...

**Comment by SteveLTN** [comment]
Well, in order to debug it, you need to know which step failed. I suggest
you disconnect your application to test. If you can see the welcome page,
you know the problem is between https-portal and your upsteam. If you don’t
see a welcome page but still get a 502, you know it’s https-portal failing
to receive requests.

**Comment by thomas126** [comment]
Okay so i just put into Domain: Mail.domain.de

Still an 502 error...

**Comment by SteveLTN** [comment]
The DNS is not set up for mail.domain.de .

**Comment by thomas126** [comment]
How come so? I have another domain on the same https running just fine. It’s a top level domain though...

**Comment by SteveLTN** [comment]
```
❯ nslookup mail.domain.de                                                                                                       2.5.1 ws-persist-english-proficiency d0bde8e
Server:		192.168.1.1
Address:	192.168.1.1#53

** server can't find mail.domain.de: NXDOMAIN
```

**Comment by thomas126** [comment]
version: '3'
services:
 https-portal:
container_name: https-portal
image: steveltn/https-portal
ports:
- '80:80'
 - '443:443'
restart: always
environment:
STAGE: 'production'
DOMAIN: 'mail.annethomi.de, redirect.me => redirected.com
- /path/nginx/conf.d:/etc/nginx/conf.d/:rw
- /path/nginx/ssl_certs:/var/lib/https-portal:$- /var/run/docker.sock:/var/run/docker.sock:ro
networks:
default:
external:
name: mailcowdockerized_mailcow-network

**Comment by SteveLTN** [comment]
Looks pretty good. Make sure you don't override nginx config files.

Also what does the log say? `docker-compose logs -f https-portal`

**Comment by thomas126** [comment]
When I delete them does the container recreate them?

**Comment by SteveLTN** [comment]
Yes, the container creates "/etc/nginx/conf.d/#{domain.name}.conf" and "/etc/nginx/conf.d/#{domain.name}.ssl.conf" everytime.

**Comment by SteveLTN** [comment]
But if you put any other files in the same folder, Nginx will load them. I think the Nginx log is where you should look at to debug.

**Comment by SteveLTN** [comment]
Closing for being inactive for over two weeks. Feel free to reopen.
