### ISSUE TITLE
Passing command line parameters to Nginx

### ISSUE THREAD

**Issue by harunorimurata** [SteveLTN/https-portal#147]
Hi,
Thank you for your work on this project.

Is there any way to pass command line parameters to nginx?
Now, I'm planning to use `ngx_http_gzip_static_module`, but it requires `--with-http_gzip_static_module` parameter.
https://nginx.org/en/docs/http/ngx_http_gzip_static_module.html

**Comment by SteveLTN** [comment]
Hi,

ATM it is not possible. You can easily modify the code to achieve so, but I would recommend you to do this in your application. 

HTTPS-PORTAL is a proxy that does one thing only, that is to add HTTPS support, and it is meant to work as a blackbox. I'm feeling you are configuring the Nginx inside PORTAL, which breaks the  "do one thing and do it well" philosophy IMO.

With all that said, if you insist, you can simply fork the project, modify [this line](https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/opt/certs_manager/lib/nginx.rb#L27).

Weiyan

**Comment by harunorimurata** [comment]
OK, that's make sense. Thank you:)

**Comment by harunorimurata** [comment]
Hi, Weiyan.
Sorry, I had misunderstanding...
`--with-http_gzip_static_module` is build parameter.
So, `ngx_http_gzip_static_module` is available on this project.

**Comment by SteveLTN** [comment]
OK. Have you checked how to enable it then?

**Comment by harunorimurata** [comment]
I just confirmed the module is contained like the flowing.
```
# docker exec -it https-portal_1 /bin/bash
# 2>&1 nginx -V | tr ' ' '\n' | grep static
--with-http_gzip_static_module
```

It can be enabled with overridding nginx conf files.

**Comment by SteveLTN** [comment]
Good the hear :-)
