### ISSUE TITLE
Subdomains and no other place to put this comment

### ISSUE THREAD

**Issue by vfulco** [SteveLTN/https-portal#15]
Between J. Wilder's and SteveLTN's phenomenal work, this devops noob is standing on the shoulders of giants! Just awesome. 

Separately, be sure all subdomains are recognized by registrar before completing. I had one or two laggards whick borked the rest of the process.

**Comment by vfulco** [comment]
Argh, spoke too soon.  Have pre-existing certs for both www.foo.cn and test.foo.cn. Trying to use this simple docker-compose.yml file (below), subdomain is not found and site reverts to http://foo.cn.  No errors surface and both host container and subdomain containers are running.  What am I missing?  TIA,

https-portal:
  image: steveltn/https-portal-mod
  ports:
    - '80:80'
    - '443:443'
  environment:
    DOMAINS: 'www.foo.cn'
    PRODUCTION: 'true'
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
test:
  image: heddle317/docker-flask-example
  environment:
    # tell HTTPS-PORTAL to set up "example.com"
    VIRTUAL_HOST: 'test.foo.cn'
    VIRTUAL_PROTO: https

**Comment by SteveLTN** [comment]
Err, in any case it should not revert to `http://foo.cn`, it doesn't know the existence of `http://foo.cn` anyway. Did you set the redirection in you DNS?

**Comment by vfulco** [comment]
DNS was set up previously for www, wildcard and all subdomains when I was working on http only config and nginx-proxy.

**Comment by vfulco** [comment]
Removed wildcard and http://foo.cn fron DNS manager, still same results. Hmm...

**Comment by vfulco** [comment]
Mistakenly hit the limit when I manually created certs earlier and then tried to use this process. Still WIP.

**Comment by vfulco** [comment]
Strange, if I start up https-portal, it recognizes www.foo.cn and I get the welcome page.  If I have other containers running and their certs in /etc/letsencrypt/live/, namely red1.foo.cn and test.foo.cn, I get the insecure cert warning saying cert only good for www.foo.cn.

**Comment by vfulco** [comment]
And in the container have the right certs--
/var/lib/https-portal# ls
account.key  dhparam.pem  intermediate.pem  red1.foo.cn	test.foo.cn	www.foo.cn

**Comment by SteveLTN** [comment]
Can you explain your setup? It is hard for me to figure out what your setup looks like.

You have DNS: www.foo.cn, test.foo.cn, red1.foo.cn, red2.foo.cn, four subdomains? Each of them will need a cert from Let's Encrypt.

```
 If I have other containers running and their certs in /etc/letsencrypt/live/
```
What is `/etc/letsencrypt/live/`? And what certs are you putting there? HTTPS-PORTAL doesn't need you to put any certs anywhere.

**Comment by SteveLTN** [comment]
Argh, the insecure certs warning is because it's using Let's Encrypt staging API. That was a bug and is fixed. Please pull the latest HTTPS-PORTAL image by `docker-compose pull`.

I recommend you to try everything without `PRODUCTION='true'`. The rate limit of Let's Encrypt is really tight now since it's in public beta.

**Comment by vfulco** [comment]
Thanks for the timely response.  I made the mistake of creating certs beforehand which were deposited automatically in /etc/letsencrypt/live.  I found out by looking at the certification records on https://crt.sh/ that somehow I have two certs for test.foo.cn and two for red1.foo.cn plus one for www.foo.cn (guessing a combof manual and testing http-portal) and then further attempts now have shut me out for a week.  Seems odd that the system at let's encrypt would let me create two certs with exactly the same terms for each subdomain.  

My setup is www.foo.cn, red1.foo.cn, test.foo.cn, at the DNS.  Oddly I first tried to use the domain name and subdomains on one cert but it wouldn't recognize.  So I set up separate certs (during the manual process) two of which I have since revoked.  

For some reason, I don't have a cert for red1. or test. in HTTPS-PORTAL /var/lib/httpportal even though I suppodely have two sets of each so I don't know where the other certs went. I will pull the latest image and use the staging server until my temp limit is eliminated.

**Comment by vfulco** [comment]
With the new pull and working off the LE staging server, all subdomains are accessible (giving me the insecure cert warning) using a simple flask container.

**Comment by vfulco** [comment]
What am I missing?  I tried a simple docker-compose up and 'production=true' with only www.foo.cn which is setup in DNS, the file is found in/var/lib/http-portal and crt.sh indicates I have two certs for it.  If the cert is legit on LE's records and I have the file in the dir, there should be no need to create a new one?

The error surfaces that I have tried to create too many certs for the naked domain foo.cn but the dir above indicates a file exists. 

<snip>
Registering account...
https-portal_1 | Already registered!
https-portal_1 | Verifying www.foo.cn...
https-portal_1 | www.foo.cn verified!
https-portal_1 | Signing certificate...
https-portal_1 | Traceback (most recent call last):
https-portal_1 |   File "/bin/acme_tiny", line 198, in <module>
https-portal_1 |     main(sys.argv[1:])
https-portal_1 |   File "/bin/acme_tiny", line 194, in main
https-portal_1 |     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
https-portal_1 |   File "/bin/acme_tiny", line 161, in get_crt
https-portal_1 |     raise ValueError("Error signing certificate: {0} {1}".format(code, result))
https-portal_1 | ValueError: Error signing certificate: 429 {"type":"urn:acme:error:rateLimited","detail":"Error creating new cert :: Too many certificates already issued for: foo.cn","status":429}
https-portal_1 | Failed to obtain certs for www.foo.cn

**Comment by SteveLTN** [comment]
HTTPS-PORTAL doesn't use your previously obtained certs, it obtains its own from Let's Encrypt. And it doesn't use anything in `/etc/letsencrypt/live`.

However, HTTPS-PORTAL will store the certs that it obtained in `/var/lib/https-portal`. (https-portal, not http-portal). If you do the trick and put your own certs there, it will just use it.

I don't recommend you do so. Even if you put your own certs in `/var/lib/https-portal`, after three months, the certs will expire. And HTTPS-PORTAL will only get certs for ONLy the subdomain anyway. If you want to obtain the certs by yourself manually and use them in your nginx container, maybe you can use jwilder's https-proxy. HTTPS-PORTAL is really not supposed to work like that.

If you are to use HTTPS-PORTAL to link to your flask container, just forget everything about obtaining certs manually. Use 
```yaml
https-portal:
  image: steveltn/https-portal
  ports:
    - '80:80'
    - '443:443'
  environment:
    DOMAINS: www.foo.cn -> flask:80, test.foo.cn -> flask:80
  links:
    - flask

flask:
  # your flask container
```

Yes, you can obtain two certs for the same subdomain from Let's Encrypt. You just hit the limit that 5 certs for each domain (not subdomain) will be issued each week.Say you obtained 2 certs for www.foo.cn, 2 for test.foo.cn, 1 for foo.cn, that's 5 in total, and Let's Encrypt will say "Too many certificates already issued for: foo.cn".

I guess you can only wait :-(

**Comment by SteveLTN** [comment]
Or if you want to use auto-discovery:

```yaml
https-portal:
  image: steveltn/https-portal
  ports:
    - '80:80'
    - '443:443'

flask:
  ...
  environment:
    VIRTUAL_HOST: test.foo.cn
```

**Comment by vfulco** [comment]
Thanks very much for the detailed followup and illumination of the
pitfalls of moving certs manually. That was going to be my next
attempt today so you are saving me time.  Your code/project
contribution really is phenomenal.  It takes getting familiar with the
LE process to become fully productive but that is outside its scope.
Much appreciated!

-- 
Vince Fulco, CFA, CAIA
612.424.5477 (universal)
186.1694.0908 (mobile in China)
vfulco1@gmail.com
wechat: vfulco
fastmail: vfulco1@fastmail.fm

--
“The bitterest tears shed over graves are for words left unsaid and deeds
left undone.” ~~Harriet Beecher Stowe
--

**Comment by SteveLTN** [comment]
You probably want to tell me what you want to do exactly, so I can try to figure out a way for you.

**Comment by SteveLTN** [comment]
Thanks. The project is actually designed for people who do not know how Let's Encrypt works (and they don't need to know). If you want to play around with LE, [ACME-tiny](https://github.com/diafygi/acme-tiny) is a tiny script to do so, then you can use the certs any way you want. (PORTAL uses acme-tiny internally as well)

**Comment by vfulco** [comment]
Nothing fancy.  I had a great working setup on Amazon EC2 with
nginx-proxy and a few containers running on http.  I was looking for a
way to incorporate the LE functionality so it was one less thing to
think about (https).  Also thinking of using nginx to proxy private
files from S3.

Essentially the setup was one or two client facing Flask oriented
sites, a redis instance, a mongodb instance and back end connectivity
to S3.  I am not a devops guy, just an entrepreneur on a shoestring
budget trying to get a solid website with multiple pieces off the
ground.  Also working from mainland China and AWS doesn't provide
their full suite of services hence a lot of working around things or
extra hurdles. I will get it figured out, no need to bother you with
my project.  Might have a question or two down the road.

On 2/1/16, Weiyan Shao <notifications@github.com> wrote:
> Thanks. The project is actually designed for people who do not know how
> Let's Encrypt works (and they don't need to know). If you want to play
> around with LE, [ACME-tiny](https://github.com/diafygi/acme-tiny) is a tiny
> script to do so, then you can use the certs any way you want. (PORTAL uses
> acme-tiny internally as well)
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/SteveLTN/https-portal/issues/15#issuecomment-177653193


-- 
Vince Fulco, CFA, CAIA
612.424.5477 (universal)
186.1694.0908 (mobile in China)
vfulco1@gmail.com
wechat: vfulco
fastmail: vfulco1@fastmail.fm

--
“The bitterest tears shed over graves are for words left unsaid and deeds
left undone.” ~~Harriet Beecher Stowe
--

**Comment by SteveLTN** [comment]
I was expecting something more about your application setup, like: "two flask containers, one for a.foo.com, the other on b.foo.com. " so I can give my suggestions.

Using https-portal should just be replacing nginx-proxy with some extra env configuration. You don't need to install/use Let's Encrypt client anyway. 

Chinese network is nasty. I'm myself a Chinese, but now living abroad. It's tricky to get a stable connection to S3. We eventually turned to some Chinese storage providers.
