### ISSUE TITLE
Official LetsEncrypt Rate Limit

### ISSUE THREAD

**Issue by deckar01** [SteveLTN/https-portal#150]
The lets-encrypt rate limit is officially documented.

> The main limit is Certificates per Registered Domain, (50 per week).
> We also have a Duplicate Certificate limit of 5 certificates per week.
> ... we have a Renewal Exemption to the Certificates per Registered Domain limit.

https://letsencrypt.org/docs/rate-limits/ would be a better reference for the readme since those discussion are nearly 2 years old and the official docs on rate limiting are updated frequently.

**Comment by SteveLTN** [comment]
Solved in https://github.com/SteveLTN/https-portal/pull/151. Closing.
