### ISSUE TITLE
Can this be used to proxy to any domain on any port? e.g. https://sun.com ?

### ISSUE THREAD

**Issue by bradparks** [SteveLTN/https-portal#156]
Hey! I'd like to use this to make it easy for devs in our company to instantly proxy lots of local dev servers to staging servers on our VPN.

This would mean that I'd like to take 10 different domains, and proxy them to a local dev server, so for example

https://www.staging1.mysite.com -> proxied to localhost:443
https://test.staging1.mysite.com -> proxied to localhost:444
https://ez.staging1.anothersite.com -> proxied to localhost:444

Why would I want to do this? This would allow devs to easily integrate servers running on their localhost with other servers in a staging environment, because many of these servers are hard to setup, and integrating themselves like this makes it easy for them to test their part of our complex integrations.

I currently do this using a vagrant that runs an Apache Load Balancer, with precanned SSL certs, that they can enable/disable by putting an entry in their hosts file. Devs have to import a root certificate first, but after they've done that, all their domains are fully trusted in the browser,

e.g. all they have to do is enable entries in their hosts file, and it works

127.0.0.1 www.staging1.mysite.com
127.0.0.1 test.staging1.mysite.com
127.0.0.1 ez.staging1.anothersite.com

**Comment by SteveLTN** [comment]
Hi! I'm not sure what you want to say in your issue. You described how things work in your company, which I think is great, but does it have any thing to do with HTTPS-PORTAL?

If you want to use HTTPS-PORTAL instead, you have to notice Let's Encrypt needs to verify the ownership of the domain before issuing certificate. That means, `www.staging1.mysite.com`, `test.staging1.mysite.com`, `ez.staging1.anothersite.com` needs to be actually available on the Internet and accessible by Let's Encrypt server. You can't just put the domains in your `hosts` file to obtain a certificate, unfortunately.

**Comment by bradparks** [comment]
Got it - I thought that might be true, but I'm not well versed in how this works - I thought maybe this could be used as a one click https proxy to any domain, using self signed certs possibly with it's own root authority, but I couldn't tell... Now I know! Thanks a ton for your time... much appreciated!
