### ISSUE TITLE
Upgrading to v1.4.2: This server's certificate chain is incomplete.

### ISSUE THREAD

**Issue by darwin** [SteveLTN/https-portal#159]
Just wanted to share some headaches I had when upgrading my existing setup to v1.4.2 (from v1.1.1). The problem was caused by old crt files.

1. During first run it complained about missing files `chained.crt`.
I skimmed through sources and it looked like there should be automatic backward compatible upgrade from `signed.crt` via a symlink. I assumed it didn't work for me for some reason, so I made those symlinks by hand.

2. After restarting the container with v1.4.2 all seemed ok until some Java-based server started failing to do https handshakes. I tested it in chrome and everything looked just fine. It was puzzling at first because I'm no SSL expert. Then I got another report about failing HTTPS from someone showing the issue via https://www.ssllabs.com/ssltest/index.html. The ssllabs test reported: `This server's certificate chain is incomplete.`.

3. I fixed the issue by running the container again with `FORCE_RENEW=true`. After renewal, everything seems to look good.

Not sure if this was described anywhere, but I didn't find any note about this. Just thought sharing it could help someone.

**Comment by SteveLTN** [comment]
Ahh, it's a backward compatibility issue, and it has been biting me forever. In Let's Encrypt's API v2, chaining certificates manually is not necessary anymore. I kept some code for backwards compatibility, but I guess I didn't cover everything. I'll add it in the documentation. Thanks for the reminder!

**Comment by SteveLTN** [comment]
Updated the document. Closing this now.
