### ISSUE TITLE
Chain file from full chain

### ISSUE THREAD

**Issue by viniokil** [SteveLTN/https-portal#163]
For gitlab in docker, need a file chain, which is part of a full chain. In your project, it's file signed.crt. It would be great if the file chain.pem was generated automatically.

I like this project and do not want to create a bicycle to create a single file. After all, I'm just trying to get rid of bicycles in favor of Docker.

**Comment by SteveLTN** [comment]
I'm not sure what a "file chain" is. What do you expect `chain.pem` to be?

Since Let's Encrypt implemented ACME v2, `signed.crt` actually is the full chain. And `chained.crt` is just a symlink to `signed.crt`. Before that, I had to manually chain the certs.
