### ISSUE TITLE
Serve http version while generating / validating certificates

### ISSUE THREAD

**Issue by LorenzHenk** [SteveLTN/https-portal#166]
I'm migrating some pages from an external host to my own server and want to do that with the least possible down time. But because let's encrypt needs you to point your domain to the server, you do have some down time while the certificates are generated/registered/validated. 

To minimize this down time, I propose to serve the endpoints with http while the certificates are processing and automatically changing to https when finished.

**Comment by SteveLTN** [comment]
Interesting idea. I’m traveling right now, will have a look when I come
back home.
