### ISSUE TITLE
Specify email, company name etc when issuing a Let's Encrypt cert

### ISSUE THREAD

**Issue by meglio** [SteveLTN/https-portal#169]
In your README file I couldn't find any documentation re specifying contact email, company name and other certificate meta information that one usually enters when issuing a Let's Encrypt certificate.

Is there any way to do it?

Many thanks.

**Comment by SteveLTN** [comment]
Hi! I’m afraid it is not supported at the moment.

**Comment by SteveLTN** [comment]
Well,  the underlying script https://github.com/diafygi/acme-tiny doesn't support it...
