### ISSUE TITLE
Error message when running "docker-compose up"

### ISSUE THREAD

**Issue by lucj** [SteveLTN/https-portal#17]
Hi, when I run "docker-compose up" using the example compose file:

    https-portal:
      image: steveltn/https-portal
      ports:
        - '80:80'
        - '443:443'
      environment:
        DOMAINS: 'example.com'
        # PRODUCTION: 'true'

I've got the following error

    luc ~/Desktop/https-test $ docker-compose up 
    Creating httpstest_https-portal_1
    Attaching to httpstest_https-portal_1
    https-portal_1 | [fix-attrs.d] applying owners & permissions fixes...
    https-portal_1 | [fix-attrs.d] 00-runscripts: applying...
    https-portal_1 | [fix-attrs.d] 00-runscripts: exited 0.
    https-portal_1 | [fix-attrs.d] done.
    https-portal_1 | [cont-init.d] executing container initialization scripts...
    https-portal_1 | [cont-init.d] 00-setup: executing...
    https-portal_1 | Generating DH parameters, 2048 bit long safe prime, generator 2
    https-portal_1 | This is going to take a long time
    https-portal_1 | ................................................+....................................................................................
    …….
    +.....................................................++*++*
    https-portal_1 | Generating RSA private key, 4096 bit long modulus
    https-portal_1 | ................................................................++
    https-portal_1 | ........................................................................................................++
    https-portal_1 | e is 65537 (0x10001)
    https-portal_1 | 2016/02/08 19:52:54 [notice] 125#125: signal process started
    https-portal_1 | Generating RSA private key, 2048 bit long modulus
    https-portal_1 | ..................................+++
    https-portal_1 | ............................................................+++
    https-portal_1 | e is 65537 (0x10001)
    https-portal_1 | Signing certificates from https://acme-staging.api.letsencrypt.org ...
    https-portal_1 | Parsing account key...
    https-portal_1 | Parsing CSR...
    https-portal_1 | Registering account...
    https-portal_1 | Registered!
    https-portal_1 | Verifying example.com...
    https-portal_1 | Traceback (most recent call last):
    https-portal_1 |   File "/bin/acme_tiny", line 198, in <module>
    https-portal_1 |     main(sys.argv[1:])
    https-portal_1 |   File "/bin/acme_tiny", line 194, in main
    https-portal_1 |     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
    https-portal_1 |   File "/bin/acme_tiny", line 123, in get_crt
    https-portal_1 |     wellknown_path, wellknown_url))
    https-portal_1 | ValueError: Wrote file to /var/www/challenges/UUXuzci_dLfcKuBWsd2GviPaDFOAtJAJHry5WcVSqWs, but couldn't download     http://example.com/.well-known/acme-challenge/UUXuzci_dLfcKuBWsd2GviPaDFOAtJAJHry5WcVSqWs
    https-portal_1 | Failed to obtain certs for example.com
    https-portal_1 | 2016/02/08 19:52:56 [notice] 140#140: signal process started
    https-portal_1 | [cont-init.d] 00-setup: exited 0.
    https-portal_1 | [cont-init.d] 10-set-docker-gen-status: executing...
    https-portal_1 | [cont-init.d] 10-set-docker-gen-status: exited 0.
    https-portal_1 | [cont-init.d] done.
    https-portal_1 | [services.d] starting services
    https-portal_1 | [services.d] done.
    https-portal_1 | Starting crond ...

I've created the docker host with Docker machine with IP 192.168.99.100 and setup my /etc/hosts so example.com is link to this IP.
I can telnet on 192.168.99.100 80 but not on port 443.
Any idea what I'm missing ?

**Comment by SteveLTN** [comment]
Hi, setting up /etc/hosts doesn't work.

Let's Encrypt needs to verify your ownership of the domain, by accessing a given file on your domain. The request is sent by Let's Encrypt server, so you need to actually configure your DNS, not /etc/hosts.

**Comment by lucj** [comment]
Hi, thanks a lot and sorry for this newbie's question then. https-portal is a great stuff.
