### ISSUE TITLE
Connect containers

### ISSUE THREAD

**Issue by thomas126** [SteveLTN/https-portal#170]
Hello there. 
I have two general questions:
1. Is there a way to connect two containers, one https portal in one docker compose file and Wordpress from another one and make it work with a network they both have access to not using the docker socket? Or is it not possible with two seperat compose files?

2. setup itself: do i proxy towards the container name of Wordpress and its port? For example the example.com -> http://containername:portofcontainer

**Comment by thomas126** [comment]
1. yeah so I tried it without giving access to the docker socket and by clearifing the setup in the domain envirement while the web apps shared the same network with https-Portal but for me it did not work out with two compose files. Maybe I missed something not sure.

2. okay so i understood that correctly. I used the container names. Is the port setup correct?

**Comment by SteveLTN** [comment]
1. The `DOMAINS` env just uses host names provided by Docker. As long as the host name is accessible, HTTPS-PORTAL can use it as an upstream. I don't think I know much about docker-compose on this aspect though.

2. Yes. Just like you visit a web page in a browser, such as `http://hostname:8080`.

**Comment by wiserain** [comment]
@SteveLTN This function seems not working suddenly. If my ```nginx.conf``` try to proxy request to the certain container using its name, it gives following error logs:

```
https         | 2018/11/18 08:03:41 Received event start for container 2b629c58f97d
https         | 2018/11/18 08:03:41 Error inspecting container: 71629d048cc0b739b41747f6d1f9f75de62980b3f065abcbf3927eb08119c8f9: No such
 container: 71629d048cc0b739b41747f6d1f9f75de62980b3f065abcbf3927eb08119c8f9
```

I remember it was okay around a week ago with the same setting, but now  it is not. You might have some clues on this issue.

**Comment by SteveLTN** [comment]
Maybe your upgraded your docker and somethings are different? I haven't made any related changes about this recently.

**Comment by wiserain** [comment]
@SteveLTN Solved. It was my stupid mistake.
