### ISSUE TITLE
Where to change docker nginx file upload limit?

### ISSUE THREAD

**Issue by petrk94** [SteveLTN/https-portal#173]
Hello @SteveLTN 
Im facing currently the same issue with Sismics Docs with a upload file size problem referecing to #115 

The problem is, I run it through the docker-composer.yml and I dont know where to change the nginx variable mentioned in #115 to disable the file size check.

Can you help?
Thanks

**Comment by SteveLTN** [comment]
https://github.com/SteveLTN/https-portal#advanced-usage

**Comment by petrk94** [comment]
@SteveLTN 
I already read this part, but it doesnt help in my problem WHERE to write it in.
I have in my home directory a folder, inside this folder I have the docker-compose.yml file.
When I use inside docker-compose up; the docker container starts, but where is the nginx.conf file located? 
Or how I can add the file size parameter to the docker-compose.yml file?

Thanks

**Comment by SteveLTN** [comment]
Put it in **environment variables** in your docker-compose.yml, just near `DOMAINS`.

**Comment by petrk94** [comment]
Thanks, I could solve this issue.
