### ISSUE TITLE
Multiple upstreams on a same domain

### ISSUE THREAD

**Issue by LongJeongS** [SteveLTN/https-portal#174]
I'm trying to set up a multiple upstream on the same domain so that we can proxy root request `/` to `frontend` container and `/api` requests to `backend` container. I know that we have to mount our own nginx conf, and I can't quite figure out how to setup the custom nginx conf erb template, more specifically how to take in a second upstream that would proxy the `/api` requests. 

Right now, I have the custom nginx.conf.erb setup as such 

```
server {
    ...........

    <% if domain.upstream %>
    location / {
        <% if ENV['DYNAMIC_UPSTREAM'] && ENV['DYNAMIC_UPSTREAM'].downcase == 'true' %>
        set $backend <%= domain.upstream %>;
        proxy_pass $backend;
        <% else %>
        proxy_pass <%= domain.upstream %>;
        <% end %>
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        <% if ENV['WEBSOCKET'] && ENV['WEBSOCKET'].downcase == 'true' %>
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 2h;
        <% end %>
    }
    <% end %>

    <% if domain.backendUpstream %>
    location /api {
        <% if ENV['DYNAMIC_UPSTREAM'] && ENV['DYNAMIC_UPSTREAM'].downcase == 'true' %>
        set $backend <%= domain.backendUpstream %>;
        proxy_pass $backend;
        <% else %>
        proxy_pass <%= domain.backendUpstream %>;
        <% end %>
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        <% if ENV['WEBSOCKET'] && ENV['WEBSOCKET'].downcase == 'true' %>
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 2h;
        <% end %>
    }
    <% end %>
}
``` 

How would i pass in the `domain.backendUpstream` to this conf file from the docker-compose setup as an environment variable?

**Comment by SteveLTN** [comment]
If you just want to do it for one domain, pass in your own `<your-domain>ssl.conf.erb`. You can just hardcode both of your upstreams there.

If you insist on having both upstreams set in environment variables, [here](https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/opt/certs_manager/models/domain.rb#L75-L77) is where we provide `domain.upstream` to nginx config files. You can add a similar method below it.

The `DOMAINS` is a comma-separated list, each section represents the config for one domain. You probably want to come up with a good syntax to describe two upstreams for one domain.
