### ISSUE TITLE
Use subjectAlternativeName for Self-signing certificate

### ISSUE THREAD

**Issue by yutadayo** [SteveLTN/https-portal#179]
Hello, @SteveLTN

I am testing in project's local environment
I can access it with a chrome browser.
But `NET::ERR_CERT_COMMON_NAME_INVALID` error is displayed

Using the subjectAltName extension when creating the certificate will resolve the error
https://support.google.com/chrome/a/answer/7391219?hl=en

Can I change the code at the time of certificate creation?

**Comment by SteveLTN** [comment]
Are you testing in local mode? In that case the certificate is self-signed, it is normal to show a invalid certificate.

**Comment by yutadayo** [comment]
Thank you @SteveLTN 

App is running in a local environment.
I only wanted to make sure that no errors occurred in self-signed certificate during my test. understood.

Close the issue.
