### ISSUE TITLE
Chromium redirecting but Firefox is not

### ISSUE THREAD

**Issue by viktorsmari** [SteveLTN/https-portal#180]
**Issue:**
I have this issue where Chromium works fine, it always redirects `https://www.example.com` to `https://example.com`, but Firefox does not! It outputs **Your connection is not secure**

**Config:**
My current config is:
`DOMAINS: example.com -> http://app:3000`

And I have NOT added `www` to my DNS settings. But I have A records with `*` and `@`

I always thought that `www.*` was some kind of magical thing, but I guess it is just a normal CNAME?

**Expected:**
I want all traffic (http://www.example.com, https://www.example.com, http://example.com) to be redirected to the `https://example.com` on all browsers

**Question:**
Do we need to add `www` as a CNAME with our DNS provider, so `https-portal` can use it?
And should I update my config using the `=>` or is there a better way?
I am guessing I should do:
`DOMAINS: www.example.com => example.com, example.com -> http://app:3000`

..but I would like to confirm before I break production :smile: 

**Related:**
I found some answers in issue #140 but it would be nice to maybe add one example to the main README?

**Comment by SteveLTN** [comment]
`www` is no magic. It's just a normal subdomain.

If you want to redirect `www.example.com` to `example.com`, you need to set the DNS for both `example.com` and `www.example.com` to the HTTPS-PORTAL host.
And config:
`DOMAINS: www.example.com => https://example.com, example.com -> http://app:3000`

Try locally if you are not sure.

**Comment by viktorsmari** [comment]
I just tried what you wrote, and that redirected to:
`https://https//example.com/`

Is there a problem with the ':' in the config?

I am using an `.env` file, so in my `docker-compose.yml` I have:
```yaml
environment:
  DOMAINS: "${MY_DOMAIN}"
```

And then in the `.env` file is
`MY_DOMAIN=www.example.com => https://example.com, example.com -> http://app:3000`

**Comment by SteveLTN** [comment]
Hi,

According to [the code](https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/var/lib/nginx-conf/default.ssl.conf.erb#L55) the `https` is automatically added. I have no idea why I would do that. 

Remove the `https` in config then. I'll make a new release to detect whether the target url starts with "http" and add it if needed for backwards compatibility.

**Comment by viktorsmari** [comment]
Thank you for the help and this awesome project!

The redirect now work like I wanted, but I did NOT add the `www` subdomain to my DNS provider :thinking: 

Maybe we can write something in the README to clear things up for people (like me :smile: ). 
I will at least rephrase and reword my issue for search ability.

**Comment by SteveLTN** [comment]
Hmm, you should add `www` though, otherwise how does a browser know where to find `www`? Maybe it is covered by a wildcard in your DNS configuration?

**Comment by viktorsmari** [comment]
Exactly, I already added that info to the original comment, in case someone else will have the same issue.
