### ISSUE TITLE
How to configure it with apache2 service

### ISSUE THREAD

**Issue by engharb** [SteveLTN/https-portal#181]
Hi,

I could not be able to configure it with apache. Where /data/https-portal/vhosts:/var/www/vhosts can not be mount from Mac OS (Does not exist such a file).

Do you have any idea/example how could be the docker-compose file.

**Comment by SteveLTN** [comment]
Sorry, I don't quite understand what you were saying.

How do you wish to use Apache? As an upstream?

**Comment by SteveLTN** [comment]
Could you paste your full docker-compose?

**Comment by engharb** [comment]
@SteveLTN I think i found the problem is that the http://'mywebpage' should be the same as the callable/linked service name. Which was not clear for me from the Documentation!

**Comment by SteveLTN** [comment]
@engharb This is just basic usage of docker-compose. Anyway, I will update the document.
