### ISSUE TITLE
many services on custom ports

### ISSUE THREAD

**Issue by Inkata** [SteveLTN/https-portal#182]
I want https-portal to proxy for many containers on the same internet domain, but on different ports.

That is:

```
http://Service1:5678 <-> [ https-portal magic ] <-> https://example.com:5678
http://Service2:1234 <-> [ https-portal magic ] <-> https://example.com:1234

```
This will allow me to expose more than one service using a single IP address on different ports, with all the wonderful goodness of https-portal :-)

Is this possible?

Thanks!

**Comment by SteveLTN** [comment]
Hi, 

It is possible, but you need to provide your own Nginx configuration file.

Check out [this section](https://github.com/SteveLTN/https-portal#override-nginx-configuration-files).

I imagine you can start by copying [this file](https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/var/lib/nginx-conf/default.ssl.conf.erb), duplicating the server block, change each one's port, and provide the modified file back by a mounted volume.

**Comment by Inkata** [comment]
I was thinking more along the lines of handling this use case while parsing the DOMAINS env 
```
[..]
DOMAINS: "example.com:1234 -> http://container:1234"
[..]
```

**Comment by SteveLTN** [comment]
Sorry, configuring through `DOMAINS` like that is not supported.

**Comment by Inkata** [comment]
Thanks. I'll close this issue now.
