### ISSUE TITLE
Support for HSTS?

### ISSUE THREAD

**Issue by dmuth** [SteveLTN/https-portal#183]
Hi!

After troubleshooting my initial installation some months ago, I've been using https-portal for pretty much all of my production websites, and have had to do absolutely zero maintenance with regards to LetsEncrypt certs.  Things Just Work.  I love it!

So I wanted to ask: is there support for HSTS in https-portal?  I see mention of it in https://github.com/SteveLTN/https-portal/issues/25 but it looks like that wasn't implemented into the main app.

If you're interested in adding in support in a dev branch, I am more than willing to test out said branch. :-)

-- Doug

**Comment by SteveLTN** [comment]
I think I'll probably make it possible as an configuration environment variable.

The tricky thing is HSTS is hard to test. Once you put it on, all visitor will ignore the http site. So if something goes wrong, it's hard to revert. 

I can totally make it configurable, e.g. using an ENV `HSTS_MAX_AGE=31536000`. But probably not enable it by default.

**Comment by dmuth** [comment]
That doesn't at all sound scary to me, because I've been serving up my stuff via HTTPS by default for a few months now.  Hence my willingness to test. :-)

Perhaps add `HSTS_ENABLE=1` to turn it on, with a default max age of something more reasonable, such as 3600 or even 600 seconds.  And a message that's printed out on startup telling the user to increase it to `30d` or similar once they are comfortable with it.

**Comment by SteveLTN** [comment]
I think one variable to control time is enough. I'll take a look in the weekend.

**Comment by SteveLTN** [comment]
Hi, the latest release 1.6.0 should have it. https://github.com/SteveLTN/https-portal#hsts-header

Still building but should be ready in a few minutes.
