### ISSUE TITLE
Disable TLS v1.0 (and v1.1)?

### ISSUE THREAD

**Issue by delfuego** [SteveLTN/https-portal#188]
Is it time for the default SSL config to no longer include TLS v1.0, and potentially v1.1?

TLSv1.0 is [no longer allowed for PCI compliance](https://www.globalsign.com/en/blog/disable-tls-10-and-all-ssl-versions/), and is widely considered to be insecure. Nearly all of the major CDNs have disabled it on their SSL termination endpoints. And then data seems to support that when nearly all of the major SSL/TLS clients implemented TLSv1.1, they also implemented TLSv1.2; there's data out there that shows that [TLSv1.1 is extremely rare in practice](https://community.qualys.com/thread/16565-is-there-a-reason-for-still-having-tlsv11-enabled).

I'm happy to submit a PR if you think that a default disabling of TLSv1.0 and v1.1 is in order.

**Comment by SteveLTN** [comment]
I'll soon release a new version to disable 1.0 and 1.1, enabled 1.3.

**Comment by pleunv** [comment]
Apologies for digging up this issue again.

I'm attempting to run https-portal in conjunction with a Weblate image, through [WeblateOrg/docker-compose](https://github.com/WeblateOrg/docker-compose). Despite it running the latest version, it still seems to let through TLSv1 and TLSv1.1 connections, according to an SSL Labs scan. I'm honestly not sure where the problem lies.

![image](https://user-images.githubusercontent.com/182021/104333970-1836de80-54f2-11eb-8114-0cdc2372b458.png)

Would you happen to have any insight into this, by any chance?

**Comment by SteveLTN** [comment]
Sorry, it was my bad.
Apparently the `ssl_protocols` need to be configured at `http` block-level, not inside each server block.
Released 1.16.1 to fix this. Expect it finish building in a few minutes.

**Comment by pleunv** [comment]
Can confirm this is now fixed. Amazing, thank you!

**Comment by pleunv** [comment]
I'm a little bit curious though, as the nginx docs mention that this can be changed on `server` block level as well:

![image](https://user-images.githubusercontent.com/182021/104428929-55987c00-5585-11eb-9089-7eed0c746360.png)

Is there any particular resource you found regarding this issue? :)

**Comment by SteveLTN** [comment]
From https://serverfault.com/questioans/704376/disable-tls-1-0-in-nginx,

> The problem here is that the Server name indication part of TLS negotiation is done after the connection itself has been negotiated. And the protocol is negotiated during connection negotiation.

And I previously have a "default server" that didn't have the line of TLS protocols. Apparently SNI happens **after** the protocol negotiation, so it will use the SSL protocols of that block. 

I figured a cleaner solution is to just move the protocols part to the root `http` block.
