### ISSUE TITLE
Question: Any way to parallel another set of docker containers without borking original setup?

### ISSUE THREAD

**Issue by weisisheng** [SteveLTN/https-portal#191]
Annoyingly I need a government issued website license for every URL I want in mainland China so I am trying to route as much as possible through subdomains.

I currently want to setup an openEdx portal to create lectures & workshops.  It uses docker-compose for the django core, mysql, etc.  

Can I somehow run each docker compose separately and still allow https-portal to "register" the subdomain or do I need to blend both docker compose files (openEdx + https-portal) into one?

**Comment by SteveLTN** [comment]
> Can I somehow run each docker compose separately and still allow https-portal to "register" the subdomain or do I need to blend both docker compose files (openEdx + https-portal) into one?

I suppose by "register subdomain" you mean to obtain certs for subdomains. In that case you can have openEdx in one docker-compose and HTTPS-PORTAL in another one. You need to figure out how to set the upstream though, meaning what the hostname of openEdx from the HTTPS-PORTAL's point of view.

**Comment by weisisheng** [comment]
Thank you.  I was afraid of that.  I have become spoiled with the drop dead easy design setting up static sites and subdomains using the main (example) docker compose.
