### ISSUE TITLE
Why did you leave out application/json from types to be gzipped

### ISSUE THREAD

**Issue by shuat** [SteveLTN/https-portal#192]
Thanks for all your doing, love your project!!

I want to know why you left out type `application/json` I know that I can create an erb and override your settings. However, doing so will mean I no longer get updates on the Nginx conf file if you update it. Is there any reason it was left this out of the following commit?
https://github.com/SteveLTN/https-portal/commit/3d42453f4cc9e09ec0f07376bdd8c31697e54fa3

**Comment by SteveLTN** [comment]
Oh, I think I googled some recommended settings for gzipping. Apparently for some reason it excluded `application/json`. I will add it back.

**Comment by shuat** [comment]
@SteveLTN Thanks!

**Comment by SteveLTN** [comment]
Release 1.7.1
