### ISSUE TITLE
Connection reset when trying to get to the IP of the container?

### ISSUE THREAD

**Issue by basicallyabidoof** [SteveLTN/https-portal#195]
I built the wordpress, db, and https containers without issue however when I attempt to reach the IP and port for the container I just get: Error Connection Reset.

Attached is the image of my YAML file. https://imgur.com/NfHjnOB

Any idea what could be causing this? I'm definitely a docker newb.

**Comment by SteveLTN** [comment]
You need to visit from the domain `lastname.tech`.

**Comment by basicallyabidoof** [comment]
I previously tried that and was getting an error which I just realized is because the router was forwarding the traffic wrong and I needed to read the prerequisites and have the domains resolved to the router.

Sorry.
