### ISSUE TITLE
Lets Encrypt rate limits update

### ISSUE THREAD

**Issue by emeidell** [SteveLTN/https-portal#199]
On April 15th, 2019 the rate limits were changed. It now appears to be 5 a week and have a [development staging service](https://letsencrypt.org/docs/staging-environment/). That is where all testing is to go. 

Rate limit changes: https://letsencrypt.org/docs/rate-limits/

**Comment by SteveLTN** [comment]
I don't remember what was added after I updated my docs. 5/week is for duplicated certificates. I should probably put that in the document as well.

As for the staging service, we suggest using it from the beginning of the project for testing.  This is well stated in the document.
