### ISSUE TITLE
Host not found in upstream after cert is obtained

### ISSUE THREAD

**Issue by vfulco** [SteveLTN/https-portal#20]
Using latest image, trying to obtain valid certs for subdomains again after verifying against staging server.  Missing something fundamental though.  The docker-compose.yml has both my FQDN 'www.foo.cn' and a separate (sub)-domain 'clients.foo.cn' for https-portal env variables. So far I have been able to obtain certs for both as found in the linked folder on the host.  And I verified that DNS is set up properly.

Simultaneously I launch a docker container with a virtual host of 'clients.foo.cn' with a simple flask app and the error below surfaces and https-portal dies. The flask container was working last week when I first obtained a cert for www.foo.cn. TIA for any assistance.

###
https-portal_1 | 2016/02/11 00:59:26 [emerg] 119#119: host not found in upstream "clients" in /etc/nginx/conf.d/clients.foo.cn.ssl.conf:18

###
here is the abbreviated docker-compose.yml

https-portal:
  image: steveltn/https-portal:latest
  ports:
    - '80:80'
    - '443:443'
  environment:
    DOMAINS: 'www.foo.cn, clients.foo.cn -> http://clients'
    PRODUCTION: 'true'
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /home/ubuntu/foo/foo:/var/lib/https-portal

...
clients:
  image: danriti/docker-flask-nginx
  environment:
    # tell HTTPS-PORTAL to set up "example.com"
    VIRTUAL_HOST: 'clients.foo.cn'
    VIRTUAL_PROTO: https

**Comment by vfulco** [comment]
Actually this is not working against staging server either and not sure what I have done wrong.

**Comment by SteveLTN** [comment]
If you want to use the `clients` alias, then you do container linking.


```yaml
https-portal:
  # ...
  links:
    - clients
  environment:
    DOMAINS: 'www.foo.cn -> http://clients, clients.foo.cn -> http://clients'
```

If you use automatic container discovery, you don't need `DOMAINS`. It will automatically discover it.

**Comment by vfulco** [comment]
Once I got the code sorted out aka hardcoding links and adding alias, this works phenomenally well. Tremendous contribution to the community at large.  My error was thinking auto-discovery would create certs and find them under production settings?  I didn't find that to be the case.

**Comment by SteveLTN** [comment]
auto-discovery would create certs and find your application containers. In that case, you just set up VIRTUAL_HOST in your app container, and don't put the domain in the ENV of portal again (which will override auto-discovery).

**Comment by SteveLTN** [comment]
If you use auto-discovery, you don't need this line at all

`DOMAINS: 'www.foo.cn, clients.foo.cn -> http://clients'`

But if now it's working then it good.
