### ISSUE TITLE
https-portal with verdaccio -> UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by pozitron01** [SteveLTN/https-portal#200]
Hello, I am not sure that I could ask this here but when I use https-portal with verdaccio (in a docker-compose system and server is on DigitalOcean) I get an error from NPM:

UNABLE_TO_GET_ISSUER_CERT_LOCALLY

Full error:
`Unexpected warning for https://npm.mysite.com/: Miscellaneous Warning UNABLE_TO_GET_ISSUER_CERT_LOCALLY: request to https://npm.mysite.com/typescript failed, reason: unable to get local issuer certificate`

Theoretically our site is certified and it works well. I don't know this issue at all and I don't know how to debug it or such things...

Any suggestions?
Thank you.

**Comment by SteveLTN** [comment]
Post your docker-compose file please.

**Comment by pozitron01** [comment]
Thank you for fast answer!

`version: '2'

services:
  verdaccio:
    image: verdaccio/verdaccio:4
    container_name: verdaccio-https
    ports:
      - "4873:4873"
    volumes:
        - "verdaccio-data:/verdaccio/storage"
        - "/home/rancher/verdaccio_config:/verdaccio/conf"
        - "/home/rancher/verdaccio_auth:/verdaccio/htpasswd"
    depends_on: 
        - https-portal
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - verdaccio:verdaccio
    environment:
      DOMAINS: 'npm.mysite.com -> http://verdaccio:4873'
      FORCE_RENEW: 'true'
volumes:
  verdaccio-data:`

**Comment by SteveLTN** [comment]
Looks like you are using staging in your https-portal. NPM might report this as an error?

**Comment by pozitron01** [comment]
Thank you my friend!!! It works with env var:
```
      STAGE: 'production'
```

**Comment by SteveLTN** [comment]
Good to hear! I'm closing the issue. Feel free to reopen if needed.
