### ISSUE TITLE
Prevent certificate renewal

### ISSUE THREAD

**Issue by qlocx** [SteveLTN/https-portal#205]
Is there any way of preventing renewal of certificates if there are any preserved in the container?
I got this:

HTTPS-PORTAL v1.7.2
[cont-init.d] 00-welcome: exited 0.
[cont-init.d] 10-persist-env: executing... 
[cont-init.d] 10-persist-env: exited 0.
[cont-init.d] 20-setup: executing... 
RSA key ok
2019/08/22 11:18:31 [notice] 242#242: signal process started
RSA key ok
Signing certificates from https://acme-v02.api.letsencrypt.org/directory ...
Parsing account key...
Parsing CSR...
Found domains: <domain>
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Traceback (most recent call last):
  File "/bin/acme_tiny", line 198, in <module>
    main(sys.argv[1:])
  File "/bin/acme_tiny", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "/bin/acme_tiny", line 121, in get_crt
    order, _, order_headers = _send_signed_request(directory['newOrder'], order_payload, "Error creating new order")
  File "/bin/acme_tiny", line 60, in _send_signed_request
    return _do_request(url, data=data.encode('utf8'), err_msg=err_msg, depth=depth)
  File "/bin/acme_tiny", line 46, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error creating new order:
Url: https://acme-v02.api.letsencrypt.org/acme/new-order
Data: {"protected": ""}
Response Code: 429
Response: {u'status': 429, u'type': u'urn:ietf:params:acme:error:rateLimited', u'detail': u'Error creating new order :: too many certificates already issued for exact set of domains: <domain>: see https://letsencrypt.org/docs/rate-limits/'}

Even tho there already is a container with an obtained key.
Inspecting container with result:
`"Config"{"Env": [
                "DOMAINS=<domain>-> http://nginx:80",
                "STAGE=production",
                "affinity:container==f75a4fecb2f454476cf008cce73fd5bb0e44f60b097c7f42dca2e11b1d6c1b3e",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NGINX_VERSION=1.17.0",
                "NJS_VERSION=0.3.2",
                "PKG_RELEASE=1~stretch",
                "S6_OVERLAY_VERSION=v1.22.1.0",
                "DOCKER_GEN_VERSION=0.7.4"
            ]
}
`

I need to keep the same certificate until I deliberately renew it.

Thanks

**Comment by SteveLTN** [comment]
Hi, I don't quite get what you mean. HTTPS-PORTAl checks the existing certificates before renewing. It will try to renew it only if it would expire in one month.

> Even tho there already is a container with an obtained key.
But that's another container. Why would HTTPS-PORTAL be aware of something going on in another container?

**Comment by qlocx** [comment]
Can I specify my own certificates in the same manner as https://github.com/SteveLTN/https-portal#share-certificates-with-other-apps ?
Using a shared volume with my own certificates

**Comment by SteveLTN** [comment]
Yes. They need to follow the same names as HTTPS-PORTAL use though. See [here](https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/opt/certs_manager/models/domain.rb).

But I don't recommend that. I would just exclude the domains with your own certificates from the environment variables and provide a custom Nginx configuration according to the document [here](https://github.com/SteveLTN/https-portal#override-nginx-configuration-files). Or just use a normal Nginx Docker image instead.

**Comment by qlocx** [comment]
Thx!
