### ISSUE TITLE
[feature request]  cors suppourt

### ISSUE THREAD

**Issue by foxundermoon** [SteveLTN/https-portal#209]
cors header support
 such as some headers configuration
```
Access-Control-Allow-Origin
```

**Comment by SteveLTN** [comment]
Could be good. I'll be traveling soon, so if anyone wants to send a pull-request it's welcome.

**Comment by SteveLTN** [comment]
I concluded that the configuration varies too much from case to case. If you need to put all CORS configuration in the environment variable, you might as well just do a custom Nginx config. Reinventing Nginx configuration language in environment variable doesn't make much sense to me.
