### ISSUE TITLE
Any recommended way to add a auth_basic_user_file for a site ?

### ISSUE THREAD

**Issue by lucj** [SteveLTN/https-portal#21]
Hi,

First of all, thanks for this great project !
I'd like to add a login/password for a given upstream, is there a recommended way to do this (env var vs new config file) ?
In the last case, how should the default nginx config created by https-portal be updated ?

    server {
        listen       80;
        server_name  domain.tld;
        location / {
           return    301 https://$server_name$request_uri;
        }
        location /.well-known/acme-challenge/ {
            alias /var/www/default/challenges/;
            try_files $uri =404;
        }
    }

**Comment by SteveLTN** [comment]
Check out [this file](https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/var/lib/nginx-conf/default.ssl.conf.erb). I recommend you make your config based on this one.

This is the default nginx config for HTTPS sites. Don't worry about HTTP config since HTTP request will simply be redirected to HTTPS.

You can build a new image from https-portal, and modify `fs_overlay/var/lib/nginx-conf/default.ssl.conf.erb`. or if you just want to add the authentication for `example.com` only, you create a `example.com.ssl.conf.erb` in the same dir as `default.ssl.conf.erb`.

Alternatively, you can mount your config file into `/var/lib/nginx-conf/` at run time. 

Portal will look for `example.com.ssl.conf.erb` first. If it doesn't exist, it will use `default.ssl.conf.erb`.

**Comment by lucj** [comment]
Thanks for your detailed reply.

I've tried your alternative approach: mouting the config file from /var/lib/nginx-conf volume

1. Creation of the volume /var/lib/nginx-conf on the host and mounted it in the container on /var/lib/nginx-conf

2. Copy of the folowing file to the host volume
  - defaut.conf.erb
  - default.ssl.conf.erb
  - nginx.conf.erb
  - domain.tld.ssl.conf.erb
  - .htpasswd

note: In domain.tld.ss.conf.erb file, I've added the auth_basic configuration

    server {
        listen 443 ssl http2;
        server_name <%= domain.name %>;
        ssl on;
        ssl_certificate <%= domain.chained_cert_path %>;
        ssl_certificate_key <%= domain.key_path %>;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        ssl_session_cache shared:SSL:50m;
        ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA;
        ssl_prefer_server_ciphers on;
        ssl_dhparam <%= dhparam_path %>;
        # Add basic authentication
        auth_basic "Restricted";
        auth_basic_user_file /var/lib/nginx-conf/.htpasswd;
        <% if domain.upstream %>
        location / {
            proxy_pass <%= domain.upstream %>;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        <% else %>
        location / {
            root   <%= domain.www_root %>;
            index  index.html;
        }
        <% end %>
    }

When going to http://domain.tld, I'm redirected to https://domain.tld and then I got the prompt for the credential.
That is working fine, thanks. I'll try the other approach for test purposes (creating a new image with the configuration file) but I'd prefer keeping your original image intact.

**Comment by lucj** [comment]
Just rebuilt the image with some additional stuff in ./fs_overlay/var/lib/nginx-conf/ (domain.tld.ssl.conf.erb
, .htpasswd). It's working great. 
Thanks for this great work !

**Comment by SteveLTN** [comment]
You're welcome. Glad to know it's working for you!

**Comment by MasaGon** [comment]
I think it's good idea to include these settings into default templates and to be controllable via environment variables like followed,

https-portal:
  environment:
    DOMAINS: 'example.com -> http://someone #production #basic user:password'

I usually use basic authentication just a few days before launching web site to be reviewed by my clients.

**Comment by SteveLTN** [comment]
@MasaGon 
I think this is more of the upstream applications' job. But if you want it in HTTPS-PORTAL, a pull-request is welcome :-)

**Comment by jeff1985** [comment]
@MasaGon 
also see this fork where basicauth is implemented:
https://github.com/Bessonov/https-portal

**Comment by SteveLTN** [comment]
@jeff1985 @MasaGon Apparently basic-auth is pretty popular. I might have a look in the weekend.

**Comment by SteveLTN** [comment]
@jeff1985 @MasaGon It's up with Release 1.3.0.

Check the documentation for the config syntax :-)

**Comment by jeff1985** [comment]
Hi @SteveLTN ,

I have a use-case where I need to support multiple users with different passwords for the basicauth. How can I do it with your syntax?

**Comment by SteveLTN** [comment]
You can’t. It’s too complicated to shovel into the environment variable I
guess.

**Comment by MasaGon** [comment]
Hi @SteveLTN 

Excellent ! So appreciated !

**Comment by Bessonov** [comment]
@SteveLTN great! But I notice, it uses plain text passwords instead of hashed version. Because I store https-portal configuration in git, it's not a suitable solution for me.
