### ISSUE TITLE
Issue being behind firewall

### ISSUE THREAD

**Issue by pinkynrg** [SteveLTN/https-portal#213]
So I believe the problem is with my company's current firewall setup but I would like to get your opinion before dedicating 10+ hours to solve the unsolvable. 

Currently I have several web services behind the same ip address proxied by a firewall: 
- web1.company.net
- web2.company.net
- web3.company.net
- and so on...

Now, I have ssh access to these VMs only when connected to the company's VPN. 

Whenever I'm connected to the VPN the HTTPS works perfectly (I basically see the closed lock next to the link).

Whenever I disconnect the VPN connection and test the same website I get the following:

<img width="691" alt="Screen Shot 2019-10-25 at 4 10 38 PM" src="https://user-images.githubusercontent.com/1474127/67604763-198bb800-f742-11e9-85d6-cc69d08a95ec.png">

I also tried to check the certificate chains.

When under VPN I get the correct certificate chain:
<img width="978" alt="Screen Shot 2019-10-25 at 4 03 45 PM" src="https://user-images.githubusercontent.com/1474127/67604544-72a71c00-f741-11e9-933c-4a2fa7faccf0.png">

When I'm not connected to the VPN  I believe, I don't get the correct certificate:
<img width="972" alt="Screen Shot 2019-10-25 at 4 03 19 PM" src="https://user-images.githubusercontent.com/1474127/67604598-9f5b3380-f741-11e9-9f5c-7df4790f762b.png">

Any clue?

**Comment by SteveLTN** [comment]
As you said yourself, it looks like your company's firewall is doing something to the HTTPS certificate. I think you should talk to your company's IT support to figure out what the policy is.
