### ISSUE TITLE
nginx proxy Problem

### ISSUE THREAD

**Issue by caglarturkurka** [SteveLTN/https-portal#214]
Hi, I use https portal in my project. Now, I want to make proxy configuration for backend project.

How can I achive 

location /backend {
proxy_pass http://backend-ip:3000
}

**Comment by SteveLTN** [comment]
Please refer to https://github.com/SteveLTN/https-portal#override-nginx-configuration-files. You need to provide your own Nginx config files for this purpose. 
The way I imaged though, you handle your routing in your application level and then use HTTPS-PORTAL to make it support HTTPS.

**Comment by inductor** [comment]
Shall we close this issue?

**Comment by SteveLTN** [comment]
Sure.
