### ISSUE TITLE
README.md update

### ISSUE THREAD

**Issue by linde9821** [SteveLTN/https-portal#222]
In your readme the following image is used 
`image: steveltn/https-portal:1`

I didn't realize i had to update to `latest`

Might be helpful for other beginners if the readme would be updated accordingly.

**Comment by SteveLTN** [comment]
Hi, 1 always points to the latest until 2.0.0 would be released.

**Comment by linde9821** [comment]
Ah alright. 

But today i had some trouble when using 1. The Container would always exited with code 0 directly after starting.

When I changed it to `:latest` it worked just fine

**Comment by inductor** [comment]
@linde9821 Did you try `docker pull steveltn/https-portal:1` ?
If that works this issue has to be closed since it is not a problem of this repo

**Comment by SteveLTN** [comment]
That's weird... I have exactly the same build for `1` and `latest`.
Could it be an older version for `1` is somehow cached by Docker?

![image](https://user-images.githubusercontent.com/508007/79840493-426dcc80-83b6-11ea-93d2-9800ffdf25ce.png)

**Comment by linde9821** [comment]
Hi sorry that i did not respond i somehow missed your answers. Your explanations sound reasonable so that is probably the reason for my issue. Thanks for the support :)
