### ISSUE TITLE
WebSockets and CORS

### ISSUE THREAD

**Issue by stefanvoicila** [SteveLTN/https-portal#228]
After i added " WEBSOCKET: 'true' " the signalR requests of my project are working but the REST HTTP Requests stopped working because of CORS. The inverse is true if I remove the line, signalR stops working (which is to be expected) but the other requests work flawlessly.

This is my docker-compose.yml:

Basically, I've found that every request that has the [Authorize] tag fails on CORS when using the WEBSOCKET: 'true' line in docker-compose.yml

`
version: '2'
services:
  app:
    build:
      context:  ./
      dockerfile: Dockerfile
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    environment:
      DOMAINS: 'myDomain.com -> http://app:80'
      STAGE: 'production'
      WEBSOCKET: 'true'
      CLIENT_MAX_BODY_SIZE: '20M'
`

Also, if I run the project using "dotnet run" everything works as expected, so I think there is a problem with my docker configuration.

Any ideas?

**Comment by SteveLTN** [comment]
I think you probably need to configure your own CORS headers. Take a look at [how to provide your own Nginx config](https://github.com/SteveLTN/https-portal#override-nginx-configuration-files).
