### ISSUE TITLE
Nginx #403 error after static folder/file upload

### ISSUE THREAD

**Issue by vfulco** [SteveLTN/https-portal#23]
Had a perfectly good working test blog (test.foo.cn) using the Lektor static site framework with their example.  Developed another blog model, renders fine on localhost, upload to /vhosts file and getting a #403 error.  The directory has permissions of 755 (sudo chmod 755 -R test*) and the files are all 644 (sudo chmod -R 644 *). I notice the vhost test.foo.cn has user 'ubuntu' and the www.foo.cn has 'root'. Any assistance would be appreciated.

drwxr-xr-x 9 ubuntu ubuntu 4096 Feb 24 01:54 test.foo.cn
drwxr-xr-x 2 root   root   4096 Feb 24 01:40 www.foo.cn

**Comment by SteveLTN** [comment]
Your compose file please?

**Comment by vfulco** [comment]
You will notice I commented out another docker container I was using for a plain vanilla flask site called 'test' prior to uploading the static files. All certs have been created and registered previously including 'test'. I committed a new docker container to version 2.0 when i tested the static file serving functionality.  lektor is designed to be served staticly from S3, etc. Thanks.

#
https-portal:
  image: steveltn/https-portal:2.0
  ports:
    - '80:80'
    - '443:443'
  restart: always
  #links:
    #- test
  environment:
    DOMAINS: 'www.foo.cn, test.foo.cn'
    PRODUCTION: 'true'
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /home/ubuntu/certs/ssl_certs:/var/lib/https-portal
    - /data/https-portal/vhosts:/var/www/vhosts

#test:
#  image: danriti/docker-flask-nginx
#  environment:
#    # tell HTTPS-PORTAL to set up "example.com"
#    VIRTUAL_HOST: 'test.foo.cn'
#    VIRTUAL_PROTO: https
  #volumes:
    #- /home/ubuntu/client_facing_content:/app

**Comment by SteveLTN** [comment]
If you just put static files under `/data/https-portal/vhosts`, they should just be served by PORTAL.

Don't know about your other container. But if you put `VIRTUAL_HOST: 'test.foo.cn'` in your other container, you should remove `test.foo.cn` from `DOMAINS: 'www.foo.cn, test.foo.cn'`.

**Comment by vfulco** [comment]
Hi Steve-  That container was completely commented out when I had the permissioning error aka I was only running PORTAL.  That's what I find so strange since I ran the lektor example blog from the vhosts folder again with the second docker container stopped.

**Comment by SteveLTN** [comment]
Hi, I don't know what Lektor is, but I assume it creates static files? Can you print what's lying under `/data/https-portal/vhosts` ?

**Comment by SteveLTN** [comment]
Oh, and did pull the latest image on your server?

**Comment by vfulco** [comment]
*** Have not pulled the latest image, will do that tomorrow when I have a big chunk of focus time.

Yes, Lektor is a great new static site builder from the prolific author Armin Ronacher of Flask, Jinja2, Werkzeug, etc. fame.  

https://github.com/lektor/lektor

/data/https-portal/vhosts$ ls
test.foo.cn  www.foo.cn

What I find most strange is that is I used the same rsync command to upload the new static file as I did for the example blog supplied by Lektor previously.

The only thing I noticed is that test.foo.cn had user 'ubuntu' while www.foo.cn had user 'root'.  I tried to change permissions to the most liberal on test.* folder and to each file (777,755,644 were attempted) and still no luck.  Then I changed the user for test.foo.cn to root.  Still #403.  

drwxrwxrwx 8 root root 4096 Feb 25 15:05 test.foo.cn
drwxrwxrwx 2 root root 4096 Feb 25 14:55 www.foo.cn

The only thing I could find so far is this article from 2008 complaining about permissioning errors and setting the user to 'site' clears it up.  Haven't tried it yet and seems unlikely given I had the blog running on test.foo.cn already.

http://nicholasorr.com/blog/2008/07/22/nginx-engine-x-what-a-pain-in-the-bum/  

As always, thank you!

**Comment by SteveLTN** [comment]
What is inside `test.foo.cn` and `www.foo.cn` folder? Is there an `index.html`?

**Comment by vfulco** [comment]
There was an index.html in each reflecting the https-portal welcome page.  I thought it was masking the lektor static folders so removed them.  then got the 403.

I may delete the data dir and start fresh, maybe I screwed up permissions within somehow.  Does it sound right to you that the subdomain would have user 'ubuntu' and root domain would have user 'root'?

**Comment by vfulco** [comment]
The mismatch is due to the fact that https-portal sets up ownership for the vhosts as user:group root:root (not saying this is wrong).  EC2 requires you to SSH in as ubuntu@ to rsync.  I tried to change user ownership from root to ubuntu after uploading the required files but that failed.

**Comment by SteveLTN** [comment]
The default homepage is index.html, if you remove it, there will be no homepage to serve. I guess that's why you see 403.

No matter who is the owner of the domain folders, as long as they are readable by the container, I don't think  there will be any problems.

**Comment by vfulco** [comment]
Thx for the additional insight. Should we close the issue because it is isolated to my situ?  Best,

**Comment by vfulco** [comment]
Set user for the various domains/subdomains from 'root' to 'ubuntu' but because Lektor creates the templates in subdomains (templates) I will have to hard code a static link in a new config file.  To my knowledge, aliasing a file from root dir wouldn't work?

**Comment by SteveLTN** [comment]
> Also Lektor creates the templates in subdomains (templates) so I will have to hard code a static link in a new config file.

Sorry, I don't understand what it means.

**Comment by vfulco** [comment]
Apologies, I mis-spoke.  Lektor creates numerous folders one of which is templates which holds the html files and is served locally while one is developing (the other folders are assets, content models).  After building and rsyncing to EC2, the .html files must reside in the templates folder.  I am fairly new to nginx and trying to figure out the best way to re-route to that folder.  When I ask the Lektor group about serving on EC2, they said it was an nginx issue.  I have an index.html like file but it resides in templates not at the root level.

**Comment by vfulco** [comment]
Disregard most of my prior post.  I am changing the user from root to ubuntu in order to rsync.  I was rsyncing the pre-build folder vs. the built files housed in another folder.  So I have an index.html at root level now and all the required files/folders, getting a new error "unable to reach the server" at all.  I have set permissions for 755 for the /data dir recursively.

**Comment by SteveLTN** [comment]
Can you run "docker-compose run --rm nginx-portal bash" to get into the container and see what is listed under "/var/www/vhosts/<your domain>" ?

-- 
Weiyan Shao

On February 29, 2016 at 1:55:03 PM, Vincent C Fulco (notifications@github.com) wrote:

Disregard most of my prior post. I am changing the user from root to ubuntu in order to rsync. I was rsyncing the pre-build folder vs. the built files housed in another folder. So I have an index.html at root level now and all the required files/folders, getting a new error "unable to reach the server" at all. I have set permissions for 755 for the /data dir recursively.

**Comment by vfulco** [comment]
Done.  Eyeballing it, all the files from /data/https-portal/vhosts/test.foo.cn are found in "/var/www/vhosts/test.foo.cn".  Everything seems in order, now I am really stumped.

**Comment by vfulco** [comment]
No idea what solved it but up and running.  Thanks for your time.  Ready to close this if you are.

**Comment by ddulic** [comment]
Reason for me it didn't work is that I didn't have a rwx on other on the files inside /data/https-portal/vhosts, so I am guessing the user of https-portal couldn't read the files.
