### ISSUE TITLE
Nginx error but certification is enabled

### ISSUE THREAD

**Issue by martinshumberto** [SteveLTN/https-portal#230]
I do the installation according to the documentation, it takes a long time to load but from the error 504 gateway time-out, I am receiving this nginx error, only that the certification is generated and is activated, as shown in the print.
When I access the ip number of the application I am pointing the domain at, it normally accesses, what can it be?

Sorry for the bad english

![image](https://user-images.githubusercontent.com/40277280/83691570-caa3dc00-a5c8-11ea-8b34-fc80abecf2ad.png)

--------

![image](https://user-images.githubusercontent.com/40277280/83691534-b7910c00-a5c8-11ea-9f54-57939f136bd0.png)

--------

![image](https://user-images.githubusercontent.com/40277280/83691610-dbece880-a5c8-11ea-8279-a98ffce5a90d.png)

--------

![image](https://user-images.githubusercontent.com/40277280/83692544-99c4a680-a5ca-11ea-8232-38c33a21996b.png)

**Comment by martinshumberto** [comment]
I was setting upstream with the external ip, my mistake.

**Comment by SteveLTN** [comment]
Oh sorry for the late reply. Glad you figured it out!
