### ISSUE TITLE
Log rotation

### ISSUE THREAD

**Issue by kapitanov** [SteveLTN/https-portal#231]
It would be nice to have a built-in log rotation for both access.log and error.log (especially access.log since it tends to grow up). Of course, it's possible to use some external tool (or docker container) for this but I feel it'll be nice to have an integrated tool with (almost) zero configuration.

If maintainers are interested - I have implemented this feature in a fork and I'll be glad to issue a PR.

**Comment by SteveLTN** [comment]
According to [this document](https://docs.docker.com/config/containers/logging/), Nginx's docker image (which we base on) sets up a symlink from `/var/log/nginx/access.log` to `/dev/stdout`. The log entries will be handled by Docker. Simply setting the rotation in your `docker-compose.yml` should suffice.

**Comment by kapitanov** [comment]
Yes, this would be enough for some simple cases but not for more advanced scenarios.
I have few cons for this:

* Docker stores its logs in JSON format by default, so I'm unable even to grep it properly (usually web server logs are analyzed with various tools so text format is required)
* Docker log rotation is way too simple, it doesn't even support daily log rotation
* Docker stores its logs somewhere in its `/var/lib/docker/containers/...` directory so it's not easy even to find it, and recreating a container would create new log file

My point is - it would be nice to have a self-contained web server with https/LE, automatic routing, basic security (we already have all this and that's just great!), easy-to-configure logging and may be some more features.

**Comment by SteveLTN** [comment]
It does make sense. I’ll be happy to accept a pull-request if it doesn’t
break the current behavior by default. I think many people, myself
included, just use HTTPS-PORTAL for simple personal websites, and want to
keep the logs the way they are.

I guess what you intend to do is to use an external volume for the logs,
and have it rotated by some internal services within the container. Is it
correct?

**Comment by kapitanov** [comment]
Yes, that's correct - logs are stored in `/var/log/nginx/` and are lotated by logrotate tool called by cron.

I'll prepare a pull-request in a few days, need to make sure it won't affect default behaviour.

**Comment by SteveLTN** [comment]
Great. Thanks!

**Comment by SteveLTN** [comment]
1.11.0 is released! Closing this issue.
