### ISSUE TITLE
Enabling Websocket proxying might break POST requests

### ISSUE THREAD

**Issue by kapitanov** [SteveLTN/https-portal#233]
Here' s a case I've spend few hours trying to figure it out:

I have an HTTP-POSTAL with Websocket proxy enabled and I have an ASP.NET Core application serving as a backend. Backend has both REST and Websocket APIs, and REST API has some POST endpoints. Once I've set my application up on a remote server I noticed that POST requests never reach my app code, resulting in meaningless 400 empty-body responses instead.

It turns out than HTTP-POSTAL adds a `Connection: "upgrade"` header to every proxed request, even if this one is not a Websocket request and doesn't need a connection upgrade. Some HTTP servers do not allow this, including Kestrel (ASP.NET Core server engine). You may find more details [here](https://github.com/dotnet/aspnetcore/issues/17081).

I'm not quite sure if Kestrel behaviour is 100% correct but I feel that HTTP-POSTAL should not set `Connection: "upgrade"` unless needed.

It's easy to fix though: just changing line 57 in `fs_overlay/var/lib/nginx-conf/default.ssl.conf.erb` should work:

```
proxy_set_header Connection $connection_upgrade;
```

I'll send a PR fixing this ASAS if it's OK.

**Comment by SteveLTN** [comment]
Someone asked me to put these two lines there:

https://github.com/SteveLTN/https-portal/issues/27
https://github.com/SteveLTN/https-portal/pull/34

I thought they are required to have websocket proxy working according to [Nginx document](http://nginx.org/en/docs/http/websocket.html)?

**Comment by SteveLTN** [comment]
Well according to the following, your solution seems to be correct. And we need the `map $http_upgrade $connection_upgrade` as well. In that case, yes, send a pull-request please. Thank you!

> A more sophisticated example in which a value of the “Connection” header field in a request to the proxied server depends on the presence of the “Upgrade” field in the client request header:

```
http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        ...

        location /chat/ {
            proxy_pass http://backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
    }
```
