### ISSUE TITLE
upstream from LAN

### ISSUE THREAD

**Issue by envake** [SteveLTN/https-portal#240]
Is it possible to pass a service from another machine running in my LAN through https-portal?
And if so, how can I achieve this?

**Comment by SteveLTN** [comment]
Yes, as long as you can access your service from LAN!
For instance, if your server is running on `192.168.1.1`, then do `DOMAINS: example.com -> http://192.168.1.1:80`.

**Comment by envake** [comment]
Ok. I did that and the connection basically works but now im getting ERR_TOO_MANY_REDIRECTS when trying to connect from any browser.
The docker upstreams work as usual.

**Comment by SteveLTN** [comment]
I would start from analyzing each redirections. Most likely there is a redirection loop, and you just need to find out which one is redirecting wrongly.

Just in case, in PORTAL config, `->` means using upstream, and `=>` means redirect.

**Comment by envake** [comment]
Thx for your answer, Im going to try different setups. Right now I have no clue whats the cause of this loop. I tested everything in staging and it worked, but as soon as I switch to production the ERR_TOO_MANY_REDIRECTS occures 😢

**Comment by envake** [comment]
Ok I solved it. It had something to do with the web server of the upstream, which also used SSL with the same domain I set in https-portal now for that machine. If im just using another domain it works flawless. Thank you for your work. 👍

**Comment by SteveLTN** [comment]
Good to hear!
