### ISSUE TITLE
https-portal             standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by SgtErnestBilko** [SteveLTN/https-portal#244]
Steve

I hope you are able to help.  I am using "steveltn/https-portal:1" as part of restreamer.  I have used the docker-compose.yml suggested in the restreamer docs.  I have also tried steveltn/https-portal:latest

In order to troubleshoot I made a new docker-compose.yml with only your "see it work" compose code.

I am running on a Pi4 with the latest buster release.

In all instances I get the following error

standard_init_linux.go:211: exec user process caused "exec format error"

Thank you

**Comment by SgtErnestBilko** [comment]
Looks like I didn't read enough.  Your images are for AMD architecture not ARM.  Sorry to have wasted your time.

**Comment by SteveLTN** [comment]
You can have a look at https://github.com/SteveLTN/https-portal/blob/master/Readme.armhf if it makes any sense to you.

**Comment by SgtErnestBilko** [comment]
Thank you very much.  It does make sense.

I was able to make an armf version myself by editing Steve’s Dockerfile this morning.

I was using a spare Pi4 to act as a local "restreaming server" for my personal website which I also host at home.

 My problem is that my browser won’t accept data from the restreamer player because it has a locally signed certificate.

I am going to try and move the restreamer docker to my web server and try to reverse proxy behind the existing nginx server which has a valid trusted certificate.

Thank for your help.




On 11 Oct 2020, at 19:16, W Shao <notifications@github.com<mailto:notifications@github.com>> wrote:



You can have a look at https://github.com/SteveLTN/https-portal/blob/master/Readme.armhf if it makes any sense to you.
