### ISSUE TITLE
How to set a stream?

### ISSUE THREAD

**Issue by gderaco** [SteveLTN/https-portal#246]
I am using ZNC that exposes on the same port a HTTP server and an IRC server.
Now, reading [the reverse proxy wiki of znc](https://wiki.znc.in/Reverse_Proxy#IRC) it seems I have to declare a _stream_. Is it something I can do through docker-compose or I need to create the Nginx conf myself and mount it? If so, how since I can only inject the `server` block?

Thanks for your help.

**Comment by SteveLTN** [comment]
I'm afraid HTTPS-PORTAL doesn't have support for it. But I imagine it is not too hard to modify it to suit your need. 
Take a look at [nginx.conf](https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/var/lib/nginx-conf/nginx.conf.erb) , and modify it if necessary. You can either use a external volume or simply fork this repo.

**Comment by gderaco** [comment]
>a external volume  

What do you mean by that?

**Comment by SteveLTN** [comment]
To use Docker's volume function to supply your own nginx.conf at runtime.
https://docs.docker.com/storage/volumes/

**Comment by gderaco** [comment]
Thanks a lot. I will look into it.
