### ISSUE TITLE
log rotation doesn't work

### ISSUE THREAD

**Issue by kedama222** [SteveLTN/https-portal#248]
Hello!

I found logrotate doesn't work correctly.

https://github.com/SteveLTN/https-portal/commit/ada778c0759a0536f5758f6dbf4a532fb007537b#diff-0d569d44c262f49774d8bfa6db5529395f2c897ffacc2f7063de1e42d287545cR18

logrotate uses invoke-rc.d to reload nginx but this container doesn't contain /etc/init.d/nginx.

This results nginx continues writing to old log file.

May I send a PR to fix this issue?

**Comment by SteveLTN** [comment]
Hi,

Yes please! Appreciated!
