### ISSUE TITLE
HSTS, redirect to https before redirecting

### ISSUE THREAD

**Issue by mathe42** [SteveLTN/https-portal#250]
When useing https-portal with the config for DOMAINS:

example.de => www.example.de,
www.exampe.de -> docker-container:8080

https://hstspreload.org/ states that:

`http://example.de` (HTTP) should immediately redirect to `https://example.de` (HTTPS) before adding the www subdomain. Right now, the first redirect is to `https://www.example.de/`. The extra redirect is required to ensure that any browser which supports HSTS will record the HSTS entry for the top level domain, not just the subdomain.

Is there a way to get this working as described?

### Summary:
Redirect wanted: http://example.de -> https://example.de -> https://www.example.de
Redirect current: http://example.de -> https://www.example.de

**Comment by SteveLTN** [comment]
Unfortunately there is no easy way for you to make it work.
It is a good point though. I will update the code to make it behave as https://hstspreload.org/ suggests.

**Comment by mathe42** [comment]
Thanks 👍

**Comment by SteveLTN** [comment]
1.15.0 was released to fix this.

**Comment by mathe42** [comment]
Wow that was fast...

**Comment by SteveLTN** [comment]
It wasn't a big modification anyway :-)
