### ISSUE TITLE
Error: Too many redirects 

### ISSUE THREAD

**Issue by pascalandy** [SteveLTN/https-portal#26]
Hi,

I'm running the https://github.com/SteveLTN/https-portal#automatic-container-discovery setup. 

I'm getting this error.

**Chrome**: dockercluster.tk redirected you too many times.
ERR_TOO_MANY_REDIRECTS

**Safari**: Too many redirects occurred trying to open “‎dockercluster.tk”. This might occur if you open a page that is redirected to open another page which then is redirected to open the original page.

Any ideas ?

**Comment by SteveLTN** [comment]
How did you set it up?

**Comment by SteveLTN** [comment]
Closing this issue because it's haven't been active for a month. If you can provide more info about your setup, feel free to reopen it.

**Comment by pascalandy** [comment]
I decided to move on as this feat. is not top priority. Thanks fro asking :)
