### ISSUE TITLE
Getting rid of `if ($host != $server_name) {`

### ISSUE THREAD

**Issue by MarcelWaldvogel** [SteveLTN/https-portal#263]
```nginx
    # Prevent Nginx from leaking other server configurations on the same machine
    if ($host != $server_name) {
        return 444;
    }
```

All configuration files contain this block. `nginx` documentation recommends to avoid `if` blocks whenever possible, [because `if` is evil](https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/).

I guess the same functionality could also be achieved by creating a `server` block which is included before any of the `conf.d/*` files. What do you think?

**Comment by SteveLTN** [comment]
Yes, this can be removed now as later I implemented [this block](https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/var/lib/nginx-conf/nginx.conf.erb#L119-L127). 

(And the self-signed certs are for this block)

**Comment by SteveLTN** [comment]
I deleted this block. Closing this issue and will come in the next release.
