### ISSUE TITLE
OCSP stapling?

### ISSUE THREAD

**Issue by MarcelWaldvogel** [SteveLTN/https-portal#264]
What do you think about providing stapling support?

It seems that just using `ssl_stapling on;` [is prone to OCSP server outages](https://community.letsencrypt.org/t/ocsp-stapling-advantages-and-disadvantages/34465). However, there seems to be a [workaround which is based on managing OCSP responses outside of `nginx`](https://community.letsencrypt.org/t/ocsp-stapling-advantages-and-disadvantages/34465/4).

I think the daily certificate renewal check could also take care of trying to obtain a new OCSP response if more than half of its lifetime has already passed (for Let's Encrypt, [the lifetime is 7d, according to the a Let's Encrypt engineer](https://community.letsencrypt.org/t/ocsp-stapling-advantages-and-disadvantages/34465/2)) and storing it in the `ssl_stapling_file`, if successful.

**Comment by SteveLTN** [comment]
I'm afraid I have no intention of supporting OCSP.

**Comment by MarcelWaldvogel** [comment]
No problem. Anyone interested in basic OCSP stapling support can just add
```nginx
ssl_stapling on;
```
to `CUSTOM_NGINX_SERVER_CONFIG_BLOCK`.

Please note, that this is not safe when the "must_staple" option has been set and the Let's Encrypt OCSP servers have been down at last stapling update. This is a rare combination and should be fixed in `nginx`, anyway, IMHO.
