### ISSUE TITLE
s6-supervise errors in v1.17.4

### ISSUE THREAD

**Issue by vespakoen** [SteveLTN/https-portal#266]
Hi!

I just noticed some error when redeploying (I was using latest), and thought I'd share them.

```
https-portal_1         | s6-supervise (child): fatal: unable to exec run: No such file or directory
https-portal_1         | s6-supervise 00-certs-manager-setup: warning: unable to spawn ./run - waiting 10 seconds
```

I rolled back to an older version for now.

**Comment by SteveLTN** [comment]
Indeed. This is a bug I made in version management. I'll very soon release 1.17.5 to fix it.

**Comment by SteveLTN** [comment]
Hi, I release 1.17.5. There is no real change, but just a higher version number to avoid confusion.

**Comment by vespakoen** [comment]
Thanks!
