### ISSUE TITLE
Request: WebSocket proxy configuration option

### ISSUE THREAD

**Issue by dancek** [SteveLTN/https-portal#27]
I'm running a weechat relay, and had a bit of head-scratching before I got it to work with https-portal. The reason being that nginx needs the following two config options to let WebSocket connections through.

```
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
```

If it's easy to add a configuration option for setting those per service, that would be nice.

**Comment by SteveLTN** [comment]
You can put your per-site nginx config in to `/var/lib/nginx-conf/` and name it as `www.example.com.ssl.conf.erb`. [This](https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/var/lib/nginx-conf/default.ssl.conf.erb) is the default file used by PORTAL, it should be pretty easy to just modify this one.

See https://github.com/SteveLTN/https-portal#override-nginx-configuration-files

**Comment by dancek** [comment]
Yes, I did just that. I found that a bit tedious, and I'm thinking there's probably a lot of services that use WebSocket.

Obviously it would be best to configure nginx so that it Just Works, but I'm not sure if that's possible.

**Comment by SteveLTN** [comment]
I guess `$http_upgrade` is something that you need to set up separately? In that case, that's probably too much uncertainty to make a on/off switch.

**Comment by dancek** [comment]
I didn't add anything else beside the two lines. I just read http://nginx.org/en/docs/http/websocket.html and since the relay only uses WebSocket, I didn't even try the more sophisticated config.

**Comment by SteveLTN** [comment]
Apparently there is no bad to just pass `Upgrade` header by default. I think I'll just put it as the default configuration.

**Comment by 5an1ty** [comment]
Any update on this? I need websocket support as well.
Adding those two headers to the default config should work for everyone.

**Comment by SteveLTN** [comment]
I will add it tonight.

**Comment by SteveLTN** [comment]
@dancek @5an1ty 
I update the code. Can you guys pull the latest image and confirm that it's working?

**Comment by dancek** [comment]
I'm sorry but I won't have the time to test this for at least a couple of days.

I'm also a bit worried about what this might do when the server supports upgrading a connection but the client didn't ask for it.

**Comment by dancek** [comment]
That is, I'd prefer this to be configurable per container (and off by default).

**Comment by SteveLTN** [comment]
@dancek 
As we discussed before, there seems to be no real downside to make it on by default. Correct me if I'm wrong please.

**Comment by 5an1ty** [comment]
Haven't had time to test yet but I think we're missing this in the default config (if you use websockets) as well:
```proxy_http_version 1.1;```

Now I'm not sure if every backend web server in the world supports http version 1.1 so this might cause issues.

I'm starting to think @dancek's argument for a configurable option might have it's merits.

**Comment by SteveLTN** [comment]
@5an1ty 

I think most modern backend servers support HTTP 1.1. Anyway, HTTPS-PORTAL is not targeted to support all scenarios on the world, but just aim to have the most common cases covered with minimum configuration. Adding another per-site configuration layer is probably not what I wanted. 

As @dancek mentioned before, these two lines are the only ones he added.

**Comment by SteveLTN** [comment]
Let's move the change to a pull-request and discuss there. https://github.com/SteveLTN/https-portal/pull/34
