### ISSUE TITLE
Question: is there a possibility to do DNS instead of http based verification

### ISSUE THREAD

**Issue by petrosmm** [SteveLTN/https-portal#279]
Hi,

Love this wonderful docker. Are there any plans in the future to allow DNS based verification instead of http based verification? I know this defeats the purpose of secure. The limitation of only being able to verify by port 80 draws on way too many factors.

**Comment by SteveLTN** [comment]
Hi,

I tried to implement DNS verification. But there are some difficulties:

1. I cannot possibly implement all DNS providers' APIs.
2. Requiring manual setup of DNS records defeats the purpose of being simple to use. It would make the process convoluted. At that point, I believe some other solution might just work better.

So unfortunately the answers is no. Unless Let's Encrypt changes the way how DNS based works, we are not going to support DNS verification.
