### ISSUE TITLE
How can I test https-portal locally

### ISSUE THREAD

**Issue by lukas-schulze** [SteveLTN/https-portal#28]
Is it possible to run https-portal locally?
Whenever I try it, I get

    Chrome: https://example.org    (/etc/hosts: 192.168.99.100  example.org)
    This webpage is not available
    ERR_CONNECTION_REFUSED

Entering docker-machine shows that port 443 and 80 are listening, but curl returns an SSL error:

    docker@default:~$ curl https://127.0.0.1
    curl: (35) Unknown SSL protocol error in connection to 127.0.0.1:443

My docker-compose.yml:

    https-portal:
      image: steveltn/https-portal
      ports:
        - '80:80'
        - '443:443'
      environment:
        DOMAINS: 'example.org'

**Comment by SteveLTN** [comment]
No, you cannot.

Let's Encrypt server needs to verify the domain ownership by actually visiting the site.

-- 
Weiyan Shao

On March 17, 2016 at 7:59:52 PM, Lukas Schulze (notifications@github.com) wrote:

Is it possible to run https-portal locally?
Whenever I try it, I get

Chrome: https://example.org    (/etc/hosts: 192.168.99.100  example.org)
This webpage is not available
ERR_CONNECTION_REFUSED

Entering docker-machine shows that port 443 and 80 are listening, but curl returns an SSL error:

docker@default:~$ curl https://127.0.0.1
curl: (35) Unknown SSL protocol error in connection to 127.0.0.1:443

My docker-compose.yml:

https-portal:
  image: steveltn/https-portal
  ports:
    - '80:80'
    - '443:443'
  environment:
    DOMAINS: 'example.org'

**Comment by lukas-schulze** [comment]
Is it possible to automatically generate a self-signed certificate in such a way to test it locally?

E.g. If the flag PRODUCTION is not set and Let's Encrypt cannot verify domain ownership --> use self-signed certificate

**Comment by SteveLTN** [comment]
Definitely a good thing to have, and shouldn't be too hard. I might find
some time to do it. But unfortunately it's not in place for now.

**Comment by shankiesan** [comment]
+1 for this. I was about to start working on an image based on HTTPS-Portal that did just that.

@SteveLTN can you give me some tips on how you'd like to see this happen? I'll then get to work on it. I'm happy to spend a day or two on it as it would be amazing for my team – the closest that we can possibly replicate prod in local dev.

**Comment by SteveLTN** [comment]
@shankiesan 

I'm thinking adding a "mock mode" in acme.rb, which simply checks if all dependent files are in place, then sign a self-signed certificate.

Of course more things need to be thought through, e.g. the putting the self-signed certs in a separate folder, maybe adding it to `Domain#dir` method. `NAConfig` can handle an additional ENV such as `LOCAL` maybe. 

Please tell me if you decide to start work on it so we don't step on each other. Thank you!

**Comment by shankiesan** [comment]
Hey @SteveLTN – I've had a look at the code and I've decided that I don't know enough Ruby to have a proper go at this. We'll have to wait until you have the time to do it!

Is there any way that we can work around this in the meantime? Like, if we manually generate certificates and put them in `/var/lib/https-portal/`, will the service start? I might have a go at this...

**Comment by SteveLTN** [comment]
@shankiesan 
Yes, you can. If you put a certificate at `/var/lib/https-portal/<domain>-staging/chain.pem` and `domain.key`(literally) then run HTTPS-PORTAL in staging mode, it will not try to get new certs.

However, you are not really testing much though...

**Comment by shankiesan** [comment]
That's cool, I'll try that. I know I'm not testing much in terms of HTTPS-PORTAL, but I just want to be able to run the same docker-compose locally as I do on my server.

I also want to do some other stuff to my `wordpress` container (e.g. remove akismet, install some of our standard plugins etc), so I want to have a nicely working local environment to test this.

**Comment by shankiesan** [comment]
Haven't got around to this yet, but I thought of another use-case where this will be handy: often we're doing a redesign of a site and moving it to a new server (i.e. from another agency's to ours) at the same time. If we have the ability to use self-signed certificates, we can get the new container up and running with a self-signed certificate while we're building/configuring it, and then once the DNS has flipped, switch to production mode.

With the current setup, there's not really a way to spin up the server without having the DNS resolving (i.e. we can't use it just with the IP address or using local DNS spoofing while developing)

**Comment by SteveLTN** [comment]
Hi guys,

I have implemented self-signed certificates. Please pull the latest image and try it out!

Basically, `PRODUCTION=true` are deprecated, and now you can use `STAGE=local/staging/production` to use different stages.

**Comment by shankiesan** [comment]
That's great @SteveLTN. I'll be sure to try it first thing tomorrow morning.

**Comment by kampta** [comment]
`STAGE: local` doesn't work for me. Here is my `docker-compose.yml` file. When I open my dev-server ip, I am again redirected to https://wordpress.example.com
```
https-portal: 
  image: steveltn/https-portal
  ports:
    - '80:80' 
    - '443:443' 
  links:
    - wordpress
  restart: always
  environment:
    # DOMAINS: 'wordpress.example.com -> http://wordpress'
    STAGE: local 

wordpress:
  image: wordpress
  links:
    - db:mysql
  
db: 
  image: mariadb
  environment: 
    MYSQL_ROOT_PASSWORD: password
```

**Comment by SteveLTN** [comment]
@kampta You need to modify our `hosts` so that `wordpress.example.com` resolves to your dev machine.

**Comment by shankiesan** [comment]
That's a good point @SteveLTN . If it's any help @kampta I've set up DNSMasq so that everything that ends in `.private` resolves to my local machine. I followed the instructions [here](https://passingcuriosity.com/2013/dnsmasq-dev-osx/). It's worth noting that he sets up .dev, but Chrome sometimes thinks that this is a reserved TLD, so I use .private instead. Works a treat.

**Comment by SteveLTN** [comment]
I should probably mention it in the documentation. Will do it after work today.

**Comment by shankiesan** [comment]
I guess it's worth mentioning the two options:

1. Simple hosts file entry if you're only going to be developing on application (or want to use the same URL for all local development)
2. DNSMasq approach if you're developing lots of local development where you want each to have a different URL

**Comment by jackweldon** [comment]
@SteveLTN  What would the IP address need to be to resolve to the domain? Is it the containers IP?

**Comment by SteveLTN** [comment]
Host’s public ip.

**Comment by jmayergit** [comment]
> @kampta You need to modify our `hosts` so that `wordpress.example.com` resolves to your dev machine.

Is it possible to serve a web application while running locally ? I am unable to
