### ISSUE TITLE
Different ports

### ISSUE THREAD

**Issue by Amirhasanioox** [SteveLTN/https-portal#284]
Hello
I want to use different ports for example:

example.com -> http://php:80
example.com:8085 -> http://php:8085

but I could not achieve it by editing config files of nginx.

I will be appreciated if someone helps me.

**Comment by SteveLTN** [comment]
Hi,

There are two ports: 80 and 443 used.
Unfortunately, you cannot change 80. Let's Encrypt enforces you to use port 80 to verify domain ownership.
To replace 443 with something else, you can change Nginx config, (see [this section](https://github.com/SteveLTN/https-portal#override-nginx-configuration-files)). But I would probably just do it in Docker's config.

```yaml
    ports:
      - '80:80'
      - '4433:443'
```

**Comment by Amirhasanioox** [comment]
So I will try using another way instead of different ports.
Thanks
