### ISSUE TITLE
Question about multiple ports / protocols per domain

### ISSUE THREAD

**Issue by jakobrosenberg** [SteveLTN/https-portal#286]
Hi, how do you handle domains with multiple ports and protocols?
```
DOMAINS: >
  example-com -> http://example:1234
  example-com -> ws://example:2345
```

Thanks for a great project!

**Comment by SteveLTN** [comment]
It is not supported unless you write your own Nginx configuration. 
Note that port 80 is needed by Let's Encrypt to verify your ownership. You can [customize Nginx config](https://github.com/SteveLTN/https-portal/tree/02591b536993002cec1de2bcd1ece10f71ab0c2c#override-nginx-configuration-files), and extend [the original](https://github.com/SteveLTN/https-portal/blob/02591b536993002cec1de2bcd1ece10f71ab0c2c/fs_overlay/var/lib/nginx-conf/default.ssl.conf.erb) to connect to different upstreams.
