### ISSUE TITLE
nginx server-configuration for automatic container discovery

### ISSUE THREAD

**Issue by lukas-schulze** [SteveLTN/https-portal#29]
In chapter [Automatic Container Discovery](https://github.com/SteveLTN/https-portal#automatic-container-discovery) you describe a way to automatically add new web applications to the https-portal.

Is it also possible to provide an own server configuration for discovered containers like described in the [override chapter](https://github.com/SteveLTN/https-portal#override-nginx-configuration-files)?

**Comment by SteveLTN** [comment]
Yes. Just name your config example.com.ssl.conf.erb

**Comment by lukas-schulze** [comment]
But where do I need to store it?

Is it possible to have the configuration file stored in the discovered container? Or do I have to add it into the container of https-portal?

**Comment by SteveLTN** [comment]
You need to add it to HTTPS-PORTAL.

**Comment by lukas-schulze** [comment]
Thank you.
