### ISSUE TITLE
How to disable strong redirect from http to https

### ISSUE THREAD

**Issue by vshapovalov** [SteveLTN/https-portal#291]
Hi there, i want disable strong redirect from http to https? Is this possible without custom nginx.conf mounting?

i use https-portal:1

Thanks for the answer.

**Comment by SteveLTN** [comment]
Hi!

No, it is not possible without custom `nginx.conf`. And really, you shouldn't do it IMO.

**Comment by vshapovalov** [comment]
> Hi!
> 
> No, it is not possible without custom `nginx.conf`. And really, you shouldn't do it IMO.

Yeah, but sometimes I need to use http (
