### ISSUE TITLE
continues error while trying automatic discovery

### ISSUE THREAD

**Issue by scher200** [SteveLTN/https-portal#3]
Hi Steve,

this is awesome men, i can't wait to fully try this out.
I only get stuck with this bug all the time:
```
Attaching to nginx_acme_1
acme_1 | 2016/01/02 22:42:14 Generated '/var/run/domains' from 11 containers
acme_1 | 2016/01/02 22:42:14 Running 'reconfig'
acme_1 | 2016/01/02 22:42:15 Error running notify command: reconfig, exit status 1
acme_1 | 2016/01/02 22:42:15 2016/01/02 22:42:14 [notice] 27#27: signal process started
acme_1 | 2016/01/02 22:42:14 [emerg] 29#29: invalid number of arguments in "proxy_pass" directive in /etc/nginx/conf.d/asbitesttest.nl.ssl.conf:17
acme_1 | nginx: [emerg] invalid number of arguments in "proxy_pass" directive in /etc/nginx/conf.d/asbitesttest.nl.ssl.conf:17
acme_1 | /opt/certs_manager/lib/nginx.rb:3:in `initialize': No such file or directory @ rb_sysopen - /etc/nginx/conf.d/http://172.17.0.67:80 (Errno::ENOENT)
acme_1 | fotografieline.com.conf
acme_1 | 	from /opt/certs_manager/lib/nginx.rb:3:in `open'
acme_1 | 	from /opt/certs_manager/lib/nginx.rb:3:in `config_http'
acme_1 | 	from /opt/certs_manager/certs_manager.rb:54:in `block in ensure_signed'
acme_1 | 	from /opt/certs_manager/certs_manager.rb:53:in `each'
acme_1 | 	from /opt/certs_manager/certs_manager.rb:53:in `ensure_signed'
acme_1 | 	from /opt/certs_manager/certs_manager.rb:45:in `reconfig'
acme_1 | 	from /bin/reconfig:4:in `<main>'
acme_1 | No need to re-sign certs for asbitesttest.nl, it will not expire in 90 days.
acme_1 | 2016/01/02 22:42:15 Watching docker events
```

could you please point me in the right direction?
my /etc/nginx/conf.d/asbitesttest.nl.ssl.conf:17 lines is like:
```
    location / {
        proxy_pass ;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
```

many thanks already

**Comment by SteveLTN** [comment]
Sorry for the delay, I was flying from Asia to Europe yesterday and was preparing my trip.
I'll look into it a bit later today.

**Comment by SteveLTN** [comment]
It should not look for `/etc/nginx/conf.d/http://172.17.0.67:80` ... Can you show me the configuration of your to-be-discovered container?

**Comment by scher200** [comment]
Thanks for helping Weiyan,

here is my docker inspect of that container:

docker inspect asbtestingnl_website_1
[
{
    "Id":
"92c5fa350724e861c9db4b7715dcd4c723171a9f19a3db97016e1abe2f229f19",
    "Created": "2016-01-02T22:36:38.910770745Z",
    "Path": "/bin/bash",
    "Args": [
        "/start.sh"
    ],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 5553,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2016-01-02T22:36:39.298470959Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image":
"646f4c9df70a1ed6bbfc53457e51cf49c6a7e5adc4d35c87fac15c9b717f9d15",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID":
"2c0cf02bbc70d3ca806b8ce56c4d354552cb3b60526f28809d6fb2a20f08fdb8",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.67",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:43",
        "NetworkID":
"0c50919d499e7bf8ee836714f49e31c137c9b64ec9d13ea5faf0fc6323eea13e",
        "PortMapping": null,
        "Ports": {
            "3306/tcp": null,
            "80/tcp": null
        },
        "SandboxKey": "/var/run/docker/netns/92c5fa350724",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath":
"/var/lib/docker/containers/92c5fa350724e861c9db4b7715dcd4c723171a9f19a3db97016e1abe2f229f19/resolv.conf",
    "HostnamePath":
"/var/lib/docker/containers/92c5fa350724e861c9db4b7715dcd4c723171a9f19a3db97016e1abe2f229f19/hostname",
    "HostsPath":
"/var/lib/docker/containers/92c5fa350724e861c9db4b7715dcd4c723171a9f19a3db97016e1abe2f229f19/hosts",
    "LogPath":
"/var/lib/docker/containers/92c5fa350724e861c9db4b7715dcd4c723171a9f19a3db97016e1abe2f229f19/92c5fa350724e861c9db4b7715dcd4c723171a9f19a3db97016e1abe2f229f19-json.log",
    "Name": "/asbtestingnl_website_1",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/root/websites/asbtesting.nl/data:/usr/share/nginx/www:rw",
            "/root/websites/
asbtesting.nl/sites-enabled:/etc/nginx/sites-enabled:rw",

"/var/lib/docker/volumes/4881b9510cf5b7b55e91f56416c3ec5f53f355e48c32fec62248693226378f26/_data:/var/lib/mysql:rw",
            "/root/websites/asbtesting.nl/log/nginx:/var/log/nginx:rw"
        ],
        "ContainerIDFile": "",
        "LxcConf": null,
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": null,
        "Privileged": false,
        "PortBindings": {},
        "Links": [
            "/root_mysql_1:/asbtestingnl_website_1/mysql"
        ],
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": [],
        "VolumesFrom": [],
        "Devices": null,
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ]
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Mounts": [
        {
            "Source": "/root/websites/asbtesting.nl/data",
            "Destination": "/usr/share/nginx/www",
            "Mode": "rw",
            "RW": true
        },
        {
            "Source": "/root/websites/asbtesting.nl/sites-enabled",
            "Destination": "/etc/nginx/sites-enabled",
            "Mode": "rw",
            "RW": true
        },
        {
            "Source":
"/var/lib/docker/volumes/4881b9510cf5b7b55e91f56416c3ec5f53f355e48c32fec62248693226378f26/_data",
            "Destination": "/var/lib/mysql",
            "Mode": "rw",
            "RW": true
        },
        {
            "Source": "/root/websites/asbtesting.nl/log/nginx",
            "Destination": "/var/log/nginx",
            "Mode": "rw",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "92c5fa350724",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "3306/tcp": {},
            "80/tcp": {}
        },
        "PublishService": "",
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [

"affinity:container==5d81c75f3343e1da19c5c8ffa1f7a8e5b90ff4c888fcf7fa51caf1205cb4a895",
            "VIRTUAL_HOST=www.asbtesting.nl,asbtesting.nl",

"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "DEBIAN_FRONTEND=noninteractive"
        ],
        "Cmd": [
            "/bin/bash",
            "/start.sh"
        ],
        "Image": "eugeneware/docker-wordpress-nginx",
        "Volumes": {
            "/etc/nginx/sites-enabled": {},
            "/usr/share/nginx/www": {},
            "/var/lib/mysql": {},
            "/var/log/nginx": {}
        },
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {
            "com.docker.compose.config-hash":
"1b5a42c1cca0af51bbe7f3bbf35f3ee24b851be3d487c233a3c92246b4590ec7",
            "com.docker.compose.container-number": "1",
            "com.docker.compose.oneoff": "False",
            "com.docker.compose.project": "asbtestingnl",
            "com.docker.compose.service": "website",
            "com.docker.compose.version": "1.4.0"
        }
    }
}
]


2016-01-06 15:50 GMT+01:00 Weiyan Shao <notifications@github.com>:

> It should not look for /etc/nginx/conf.d/http://172.17.0.67:80 ... Can
> you show me the configuration of your to-be-discovered container?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SteveLTN/https-portal/issues/3#issuecomment-169343361>
> .
>



-- 
[image: FreeLaunching - Jeroen Schermer] <http://freelaunching.nl/>

**Comment by SteveLTN** [comment]
Hi,

I guess the problem is here:
```
VIRTUAL_HOST=www.asbtesting.nl,asbtesting.nl
```

It doesn't support multiple domains in automatic container discovery for now. You can probably redirect `www.asbtesting.nl` to `asbtesting.nl` in your DNS config.

And then set 
```
VIRTUAL_HOST=asbtesting.nl
```

**Comment by scher200** [comment]
OK,

thank you, for helping me.
I have this bad hosting company that does not allow me anything else but
redirecting both directly to my server. So sadly this is not gonna work.
Do you think it is hard to make it happen on the server in this container
of yours to auto forward www.**.tld to **.tld

Greets Jeroen

2016-01-07 8:56 GMT+01:00 Weiyan Shao <notifications@github.com>:

> Hi,
>
> I guess the problem is here:
>
> VIRTUAL_HOST=www.asbtesting.nl,asbtesting.nl
>
> It doesn't support multiple domains in automatic container discovery for
> now. You can probably redirect www.asbtesting.nl to asbtesting.nl in your
> DNS config.
>
> And then set
>
> VIRTUAL_HOST=asbtesting.nl
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SteveLTN/https-portal/issues/3#issuecomment-169589476>
> .
>



-- 
[image: FreeLaunching - Jeroen Schermer] <http://freelaunching.nl/>

**Comment by SteveLTN** [comment]
Yes.

In https-portal (in case you wonder, we changed the name):

```
environment:
  DOMAINS: 'www.asbtesting.nl'
volumes:
  - /var/run/docker.sock:/var/run/docker.sock:ro
```

And put a custom config file `www.asbtesting.nl.ssl.conf.erb`

```
#...
location / {
    return    301 https://asbtesting.nl;
}
```

And start your web service with 
```
VIRTUAL_HOST=asbtesting.nl
```

You might want to do some experiments, remember to turn off production flag before everything is ready.

**Comment by scher200** [comment]
Hi Weiyan,

sorry for my late response but I recieve the following errors after
changing my website containers ENV VIRTUAL_HOST: domain.tld :

# docker-compose up -d
Creating root_https-portal_1...
^[[Aroot@v22015052846325478:~# docker-compose logs
Attaching to root_https-portal_1
https-portal_1 | [fix-attrs.d] applying owners & permissions fixes...
https-portal_1 | [fix-attrs.d] 00-runscripts: applying...
https-portal_1 | [fix-attrs.d] 00-runscripts: exited 0.
https-portal_1 | [fix-attrs.d] done.
https-portal_1 | [cont-init.d] executing container initialization scripts...
https-portal_1 | [cont-init.d] 00-setup: executing...
https-portal_1 | Generating DH parameters, 2048 bit long safe prime,
generator 2
https-portal_1 | This is going to take a long time
https-portal_1 |
......+....................................................................................++*++*
https-portal_1 | Generating RSA private key, 4096 bit long modulus
https-portal_1 |
..............................................................................................................................................................................................................................................................................................................................++
https-portal_1 |
................................................................................................................................++
https-portal_1 | e is 65537 (0x10001)
https-portal_1 | 2016/01/13 05:46:04 [notice] 125#125: signal process
started
https-portal_1 | [cont-init.d] 00-setup: exited 0.
https-portal_1 | [cont-init.d] 10-set-docker-gen-status: executing...
https-portal_1 | [cont-init.d] 10-set-docker-gen-status: exited 0.
https-portal_1 | [cont-init.d] done.
https-portal_1 | [services.d] starting services
https-portal_1 | [services.d] done.
https-portal_1 | Starting docker-gen ...
https-portal_1 | Starting crond ...
https-portal_1 | 2016/01/13 05:46:05 Generated '/var/run/domains' from 12
containers
https-portal_1 | 2016/01/13 05:46:05 Running 'reconfig'
https-portal_1 | 172.17.42.1 - - [13/Jan/2016:05:46:09 +0000] "GET
/.well-known/acme-challenge/aBMf9vrA97wIRjOZ9WG-PQeZIYp6C7gcTeL1ChvSWy4
HTTP/1.1" 200 87 "-" "Python-urllib/2.7" "-"
https-portal_1 | 66.133.109.36 - - [13/Jan/2016:05:46:11 +0000] "GET
/.well-known/acme-challenge/aBMf9vrA97wIRjOZ9WG-PQeZIYp6C7gcTeL1ChvSWy4
HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation
server; +https://www.letsencrypt.org)" "-"
https-portal_1 | 2016/01/13 05:46:13 Error running notify command:
reconfig, exit status 1
https-portal_1 | 2016/01/13 05:46:13 2016/01/13 05:46:05 [notice] 166#166:
signal process started
https-portal_1 | Generating RSA private key, 2048 bit long modulus
https-portal_1 |
................................................................................................................................+++
https-portal_1 | .......+++
https-portal_1 | unable to write 'random state'
https-portal_1 | e is 65537 (0x10001)
https-portal_1 | Signing certificates from
https://acme-staging.api.letsencrypt.org ...
https-portal_1 | Parsing account key...
https-portal_1 | Parsing CSR...
https-portal_1 | Registering account...
https-portal_1 | Registered!
https-portal_1 | Verifying .db1960born.freelaunching.nl...
https-portal_1 | Traceback (most recent call last):
https-portal_1 |   File "/bin/acme_tiny", line 198, in <module>
https-portal_1 |     main(sys.argv[1:])
https-portal_1 |   File "/bin/acme_tiny", line 194, in main
https-portal_1 |     signed_crt = get_crt(args.account_key, args.csr,
args.acme_dir, log=LOGGER, CA=args.ca)
https-portal_1 |   File "/bin/acme_tiny", line 104, in get_crt
https-portal_1 |     raise ValueError("Error requesting challenges: {0}
{1}".format(code, result))
https-portal_1 | ValueError: Error requesting challenges: 400
{"type":"urn:acme:error:malformed","detail":"Error creating new authz ::
DNS label is too short","status":400}
https-portal_1 | Failed to obtain certs for .db1960born.freelaunching.nl
https-portal_1 | 2016/01/13 05:46:07 [notice] 179#179: signal process
started
https-portal_1 | Generating RSA private key, 2048 bit long modulus
https-portal_1 | ...............+++
https-portal_1 | ...............................+++
https-portal_1 | unable to write 'random state'
https-portal_1 | e is 65537 (0x10001)
https-portal_1 | Signing certificates from
https://acme-staging.api.letsencrypt.org ...
https-portal_1 | Parsing account key...
https-portal_1 | Parsing CSR...
https-portal_1 | Registering account...
https-portal_1 | Already registered!
https-portal_1 | Verifying asbtesting.nl...
https-portal_1 | asbtesting.nl verified!
https-portal_1 | Signing certificate...
https-portal_1 | Certificate signed!
https-portal_1 | 2016/01/13 05:46:13 [notice] 197#197: signal process
started
https-portal_1 | /opt/certs_manager/lib/nginx.rb:3:in `initialize': No such
file or directory @ rb_sysopen - /etc/nginx/conf.d/http://172.17.0.3:80
(Errno::ENOENT)
https-portal_1 | fotografieline.com.conf
https-portal_1 |     from /opt/certs_manager/lib/nginx.rb:3:in `open'
https-portal_1 |     from /opt/certs_manager/lib/nginx.rb:3:in `config_http'
https-portal_1 |     from /opt/certs_manager/certs_manager.rb:54:in `block
in ensure_signed'
https-portal_1 |     from /opt/certs_manager/certs_manager.rb:53:in `each'
https-portal_1 |     from /opt/certs_manager/certs_manager.rb:53:in
`ensure_signed'
https-portal_1 |     from /opt/certs_manager/certs_manager.rb:45:in
`reconfig'
https-portal_1 |     from /bin/reconfig:4:in `<main>'
https-portal_1 | Signed key for asbtesting.nl
https-portal_1 | 2016/01/13 05:46:13 Watching docker events


Any Idea what this could be?

I started your portal with this docker-compose.yml:

https-portal:
  restart: always
  image: steveltn/https-portal
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"

2016-01-08 17:08 GMT+01:00 Weiyan Shao <notifications@github.com>:

> Yes.
>
> In https-portal (in case you wonder, we changed the name):
>
> environment:
>   DOMAINS: 'www.asbtesting.nl'
> volumes:
>   - /var/run/docker.sock:/var/run/docker.sock:ro
>
> And put a custom config file www.asbtesting.nl.ssl.conf.erb
>
> #...
> location / {
>     return    301 https://asbtesting.nl;
> }
>
> And start your web service with
>
> VIRTUAL_HOST=asbtesting.nl
>
> You might want to do some experiments, remember to turn off production
> flag before everything is ready.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SteveLTN/https-portal/issues/3#issuecomment-170042410>
> .
>



-- 
[image: FreeLaunching - Jeroen Schermer] <http://freelaunching.nl/>

**Comment by scher200** [comment]
Ow yes, and here is my docker inspect of asbtesting.nl container:

docker inspect asbtestingnl_website_1
[
{
    "Id":
"1754011e58559c15b09bdf9c2bc7fc3287b44f89b3ab4b9d54f3ace9eecf523e",
    "Created": "2016-01-10T06:29:28.670298036Z",
    "Path": "/bin/bash",
    "Args": [
        "/start.sh"
    ],
    "State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 18402,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2016-01-10T19:24:44.801573896Z",
        "FinishedAt": "2016-01-10T19:24:03.401949556Z"
    },
    "Image":
"646f4c9df70a1ed6bbfc53457e51cf49c6a7e5adc4d35c87fac15c9b717f9d15",
    "ResolvConfPath":
"/var/lib/docker/containers/1754011e58559c15b09bdf9c2bc7fc3287b44f89b3ab4b9d54f3ace9eecf523e/resolv.conf",
    "HostnamePath":
"/var/lib/docker/containers/1754011e58559c15b09bdf9c2bc7fc3287b44f89b3ab4b9d54f3ace9eecf523e/hostname",
    "HostsPath":
"/var/lib/docker/containers/1754011e58559c15b09bdf9c2bc7fc3287b44f89b3ab4b9d54f3ace9eecf523e/hosts",
    "LogPath":
"/var/lib/docker/containers/1754011e58559c15b09bdf9c2bc7fc3287b44f89b3ab4b9d54f3ace9eecf523e/1754011e58559c15b09bdf9c2bc7fc3287b44f89b3ab4b9d54f3ace9eecf523e-json.log",
    "Name": "/asbtestingnl_website_1",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/root/websites/asbtesting.nl/data:/usr/share/nginx/www:rw",
            "/root/websites/
asbtesting.nl/sites-enabled:/etc/nginx/sites-enabled:rw",

"/var/lib/docker/volumes/4881b9510cf5b7b55e91f56416c3ec5f53f355e48c32fec62248693226378f26/_data:/var/lib/mysql:rw",
            "/root/websites/asbtesting.nl/log/nginx:/var/log/nginx:rw"
        ],
        "ContainerIDFile": "",
        "LxcConf": null,
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "KernelMemory": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": null,
        "Privileged": false,
        "PortBindings": {},
        "Links": null,
        "PublishAllPorts": false,
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": [],
        "VolumesFrom": [],
        "Devices": null,
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "VolumeDriver": ""
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Mounts": [
        {
            "Source":
"/var/lib/docker/volumes/4881b9510cf5b7b55e91f56416c3ec5f53f355e48c32fec62248693226378f26/_data",
            "Destination": "/var/lib/mysql",
            "Mode": "rw",
            "RW": true
        },
        {
            "Source": "/root/websites/asbtesting.nl/log/nginx",
            "Destination": "/var/log/nginx",
            "Mode": "rw",
            "RW": true
        },
        {
            "Source": "/root/websites/asbtesting.nl/sites-enabled",
            "Destination": "/etc/nginx/sites-enabled",
            "Mode": "rw",
            "RW": true
        },
        {
            "Source": "/root/websites/asbtesting.nl/data",
            "Destination": "/usr/share/nginx/www",
            "Mode": "rw",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "1754011e5855",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "3306/tcp": {},
            "80/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [

"affinity:container==92c5fa350724e861c9db4b7715dcd4c723171a9f19a3db97016e1abe2f229f19",
            "VIRTUAL_HOST=asbtesting.nl",

"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "DEBIAN_FRONTEND=noninteractive"
        ],
        "Cmd": [
            "/bin/bash",
            "/start.sh"
        ],
        "Image": "eugeneware/docker-wordpress-nginx",
        "Volumes": {
            "/etc/nginx/sites-enabled": {},
            "/usr/share/nginx/www": {},
            "/var/lib/mysql": {},
            "/var/log/nginx": {}
        },
        "WorkingDir": "",
        "Entrypoint": null,
        "OnBuild": null,
        "Labels": {
            "com.docker.compose.config-hash":
"3cec6f90ab94b97f9a83825ea1330878d2efdb14ad5031520aa11336f3119993",
            "com.docker.compose.container-number": "1",
            "com.docker.compose.oneoff": "False",
            "com.docker.compose.project": "asbtestingnl",
            "com.docker.compose.service": "website",
            "com.docker.compose.version": "1.4.0"
        }
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID":
"817171935a712db900f767d113c9cbaa634066579bea66df4186d54db3e8a629",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "3306/tcp": null,
            "80/tcp": null
        },
        "SandboxKey": "/var/run/docker/netns/817171935a71",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID":
"8260471f80c4bd1481137177cbe7b38347d74b40ab64d8270e8b5d962a7fc328",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.3",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "MacAddress": "02:42:ac:11:00:03",
        "Networks": {
            "bridge": {
                "EndpointID":
"8260471f80c4bd1481137177cbe7b38347d74b40ab64d8270e8b5d962a7fc328",
                "Gateway": "172.17.42.1",
                "IPAddress": "172.17.0.3",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:03"
            }
        }
    }
}
]

2016-01-08 17:08 GMT+01:00 Weiyan Shao <notifications@github.com>:

> Yes.
>
> In https-portal (in case you wonder, we changed the name):
>
> environment:
>   DOMAINS: 'www.asbtesting.nl'
> volumes:
>   - /var/run/docker.sock:/var/run/docker.sock:ro
>
> And put a custom config file www.asbtesting.nl.ssl.conf.erb
>
> #...
> location / {
>     return    301 https://asbtesting.nl;
> }
>
> And start your web service with
>
> VIRTUAL_HOST=asbtesting.nl
>
> You might want to do some experiments, remember to turn off production
> flag before everything is ready.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SteveLTN/https-portal/issues/3#issuecomment-170042410>
> .
>



-- 
[image: FreeLaunching - Jeroen Schermer] <http://freelaunching.nl/>

**Comment by SteveLTN** [comment]
Can you show me the docker-compose difinition of asbtesting.nl?

**Comment by scher200** [comment]
docker-compose asbtesting.nl:

website:
  environment:
    VIRTUAL_HOST: asbtesting.nl
  volumes:
    - ./sites-enabled:/etc/nginx/sites-enabled
    - ./data:/usr/share/nginx/www
    - ./log/nginx:/var/log/nginx
  expose:
    - "80"
  image: eugeneware/docker-wordpress-nginx


and here its config, (I doubt that you need it but here it is)
./sites-enabled/default:
server {
    listen   80; ## listen for ipv4; this line is default and implied
    listen   [::]:80 default ipv6only=on; ## listen for ipv6

    root /usr/share/nginx/www/production/;
    index index.php index.html index.htm;

    server_name localhost;

    sendfile off;

    location / {
        try_files $uri $uri/ /index.php?q=$uri&$args;
    }

    location /doc/ {
        alias /usr/share/doc/;
        autoindex on;
        allow 127.0.0.1;
        allow ::1;
        deny all;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/www/production;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }

}

Greets Jeroen

**Comment by SteveLTN** [comment]
I'll try to run it myself a bit later.

**Comment by SteveLTN** [comment]
It's a bug in docker-gen template, when more than 1 port is expose in the web application, it fails to pick the right one.

In your case, your application's Dockerfile actually exposed 2 ports. You can either use `VIRTUAL_PORT` to specify that, or just pull the latest image, which will default to port 80.

Sorry for that.

**Comment by scher200** [comment]
no worries,

it's awesome you wanted help me out.

Cheers men

2016-01-14 22:10 GMT+01:00 Weiyan Shao <notifications@github.com>:

> It's a bug in docker-gen template, when more than 1 port is expose in the
> web application, it fails to pick the right one.
>
> In your case, your application's Dockerfile actually exposed 2 ports. You
> can either use VIRTUAL_PORT to specify that, or just pull the latest
> image, which will default to port 80.
>
> Sorry for that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SteveLTN/https-portal/issues/3#issuecomment-171780748>
> .
>



-- 
[image: FreeLaunching - Jeroen Schermer] <http://freelaunching.nl/>
