### ISSUE TITLE
Serving insecure content

### ISSUE THREAD

**Issue by vfulco** [SteveLTN/https-portal#30]
Total noob question and nothing to do with an 'issue; with this code.  Is there a way to isolate and serve non-secure content?  I am trying to use a couple of Chinese services i.e. social media sharing button apps but they only serve their functionality/graphics using http://.  TIA.

**Comment by SteveLTN** [comment]
You want to put non-secure content in your secure page? As far as I know,
there is no way.

**Comment by vfulco** [comment]
Thanks.  I thought so.  I will have to petition the vendor to start serving it like the rest of th modern world.
