### ISSUE TITLE
Do forwarded for headers work?

### ISSUE THREAD

**Issue by sr258** [SteveLTN/https-portal#300]
I'm thinking about replacing my current custom NGINX reverse proxy setup with https-portal.

My NGINX config sets these headers:

```
        proxy_set_header X-Real-IP       $proxy_protocol_addr;
        proxy_set_header X-Forwarded-For $proxy_protocol_addr;
        proxy_set_header X-Forwarded-Host XXXX
```

Will https-portal also set these headers? The application behind the reverse proxy relies on them being set.

**Comment by SteveLTN** [comment]
Some of them. [See here](https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/var/lib/nginx-conf/default.ssl.conf.erb#L58-L61).

**Comment by sr258** [comment]
Alright, thanks for pointing me to the information. Turns out the X-Forwarded-Host is not needed when https-portal sets the host.
