### ISSUE TITLE
For your information: German video about the installation of Https-Portal with Ansible

### ISSUE THREAD

**Issue by gerold-penz** [SteveLTN/https-portal#318]
Hello SteveLTN,

I think your work is great and have been using "Https-Portal" for several years. Recently, in a German video series where I explain how to install a web server with Ansible, I also showed how to install "Https-Portal" with Ansible. Throughout the series, I use "Https-Portal" as a proxy for the programs installed with Docker.
Here is the link to the whitepaper: https://halvar.at/linux/cloud_server_installation_hetzner/#docker-https-portal-mit-ansible-installieren
Thanks again for your work.

With kind regards,
Gerold :-)

Translated with www.DeepL.com/Translator (free version)

**Comment by SteveLTN** [comment]
Thank you Gerold! Glad that you like it!
