### ISSUE TITLE
Open question re: default.ssl.conf.erb

### ISSUE THREAD

**Issue by vfulco** [SteveLTN/https-portal#32]
Not terribly facile with nginx, google sitemaps search keeps complaining about a robots.txt file which I can not find after scouring the server.  If I wanted to "allow all" would the following code snippet in the upstream section of default.ssl.conf.erb be enough?  I don't want to add a custom file as I had issues with it in the past and everything is working perfectly the last few weeks ex the search engines complaining.

TIA for entertaining the question.

Designed to be included in any server {} block.

location = /favicon.ico {
	log_not_found off;
	access_log off;
}

location = /robots.txt {
	allow all;
	log_not_found off;
	access_log off;
}

    <% if domain.upstream %>
    location / {
        proxy_pass <%= domain.upstream %>;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
--> place snippet here

    }
    <% else %>
    location / {
        root   <%= domain.www_root %>;
        index  index.html;
--> and here
    }
    <% end %>

**Comment by SteveLTN** [comment]
I'm not familiar with Nginx serving text directly. But adding a location block like this should work.

-- 
Weiyan Shao

On March 23, 2016 at 11:21:32 AM, Vincent C Fulco (notifications@github.com) wrote:

Not terribly facile with nginx, google sitemaps search keeps complaining about a robots.txt file which I can not find after scouring the server. If I wanted to "allow all" would the following code snippet in the upstream section of default.ssl.conf.erb be enough? I don't want to add a custom file as I had issues with it in the past and everything is working perfectly the last few weeks ex the search engines complaining.

TIA for entertaining the question.

Designed to be included in any server {} block.

location = /favicon.ico {
log_not_found off;
access_log off;
}

location = /robots.txt {
allow all;
log_not_found off;
access_log off;
}

<% if domain.upstream %>
location / {
    proxy_pass <%= domain.upstream %>;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

--> place snippet here

}
<% else %>
location / {
    root   <%= domain.www_root %>;
    index  index.html;

--> and here
}
<% end %>
