### ISSUE TITLE
Feature request: Healthcheck.

### ISSUE THREAD

**Issue by jupegarnica** [SteveLTN/https-portal#333]
@SteveLTN, have you considered implementing a healthcheck in order to know if the proxy is working as expected?

I mean,  I just implemented a custom healthcheck with curl to ensure the trafic is hitting my api-rest.  But it would be nicer to have a https-portal healthcheck implemented in the Dockerfile.

**Comment by jupegarnica** [comment]
Btw.  Great work. I just found it, and I feel in love :D.  If i can help I will.

**Comment by jupegarnica** [comment]
I just open a PR:  #334

**Comment by SteveLTN** [comment]
Hi! Thanks for the PR! I will have a test tomorrow!

**Comment by jupegarnica** [comment]
Version 1.23.0 closes the issue
