### ISSUE TITLE
links is not needed in docker-compose.yml

### ISSUE THREAD

**Issue by bburtin** [SteveLTN/https-portal#340]
I believe that the `links` sections in your **docker-compose.yml** samples are not necessary:

```yaml
  links:
    - wordpress
```

According to the [Docker docs](https://docs.docker.com/network/links/), the links feature is deprecated and has been replaced by [Docker networks](https://docs.docker.com/network/).  The way I understand it, if you have a single **docker-compose.yml** file and don't define a network, all of the containers will implicitly be put on the same network and will be able to talk to each other.  My https-portal container was able to talk to my web server without specifying `network` or `links`.

Also, thank you for making this container available!  It has saved me countless hours dealing with configuring HTTP certificates.

**Comment by SteveLTN** [comment]
You are right. Tested to work. I'm removing the `links` from the README. Thanks!
