### ISSUE TITLE
Update nginx version?

### ISSUE THREAD

**Issue by datWeazel** [SteveLTN/https-portal#356]
Hi, thank you for your work. We are often using your Dockerimage and it works great. We want to bring to your attention that there are [some vulnerabilities](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&isCpeNameSearch=false&cpe_vendor=cpe%3A%2F%3Af5&cpe_product=cpe%3A%2F%3A%3Anginx&cpe_version=cpe%3A%2F%3Af5%3Anginx%3A1.23.1) with the nginx version 1.23.1 that is currently used. Are you planning to release a new build with an updated nginx version?

I already forked the project and I'm trying to update the nginx version but currently there seem to be some minor things that prevent the image from being build successfully. If I can manage to update everything I could open a PR but since I can't make any promises I wanted to ask if you are maybe working on an update yourself.

**Comment by datWeazel** [comment]
Opened a PR #357

**Comment by SteveLTN** [comment]
Hi, thanks for the PR! I will have a look!

**Comment by SteveLTN** [comment]
@datWeazel Hi! After two days of testing, the cert renewal works fine. And I released 1.24.0.  I'm closing this ticket.
Thanks for the help!

**Comment by datWeazel** [comment]
Glad everything works now even tho it wasn't that straight forward and the changes were quite substantial.
