### ISSUE TITLE
The execlineb is missing in version 1.24.1 - certificates are not getting renewed

### ISSUE THREAD

**Issue by viktorsmari** [SteveLTN/https-portal#361]
Docker log:

web_1      | s6-rc: info: service s6rc-oneshot-runner: starting
web_1      | s6-rc: info: service s6rc-oneshot-runner successfully started
web_1      | s6-rc: info: service fix-attrs: starting
web_1      | s6-rc: info: service fix-attrs successfully started
web_1      | s6-rc: info: service legacy-cont-init: starting
web_1      | cont-init: info: running /etc/cont-init.d/00-welcome
web_1      |
web_1      | ========================================
web_1      | HTTPS-PORTAL v1.24.1
web_1      | ========================================
web_1      | cont-init: info: /etc/cont-init.d/20-setup exited 0
web_1      | cont-init: info: running /etc/cont-init.d/20-setup
web_1      | DH parameters appear to be ok.
web_1      | -----BEGIN DH PARAMETERS-----
...
web_1      | cont-init: info: running /etc/cont-init.d/30-set-docker-gen-status
web_1      | cont-init: info: /etc/cont-init.d/30-set-docker-gen-status exited 0
web_1      | s6-rc: info: service legacy-cont-init successfully started
web_1      | s6-rc: info: service legacy-services: starting
web_1      | services-up: info: copying legacy longrun 00-nginx (no readiness notification)
web_1      | services-up: info: copying legacy longrun 10-docker-gen (no readiness notification)
web_1      | services-up: info: copying legacy longrun 20-crond (no readiness notification)
web_1      | services-up: info: copying legacy longrun 30-dynamic-env (no readiness notification)
web_1      | s6-rc: info: service legacy-services successfully started
web_1      | execlineb: fatal: unable to exec ifelse: No such file or directory
web_1      | execlineb: fatal: unable to exec ifelse: No such file or directory
web_1      | execlineb: fatal: unable to exec ifelse: No such file or directory
web_1      | execlineb: fatal: unable to exec ifelse: No such file or directory

```bash
root@e36e39d1fc27:~# which execlineb
root@e36e39d1fc27:~#
```

However execlineb can be found in earlier versions.

**Comment by SteveLTN** [comment]
We call `/command/execlineb` explicitly. It is okay for `execlineb` being not found in the PATH. 

The error message isn't for not finding `execlineb`, rather for not being able to find `ifelse`. 

I tried a few times, and unfortunately I wasn't able to reproduce the issue. Could you provide more details about your setup and in which case you see such an error message?

**Comment by viktorsmari** [comment]
We have 4 almost identical servers (production, staging, 2 feature servers), and we use docker-compose and have been using this successfully for many years! :+1: 

**Now only 1** of those 4 server, the only one with version 1.24.1 is **not renewing** it's certificate.
The other 3 servers (running different versions of https-portal) are renewing without issues.

We have not changed any config in years, we only did a `docker pull` which updated the image, causing this error and stopped the certificate renewal.

What other information can I give you that is relevant?

**Comment by SteveLTN** [comment]
I managed to reproduce it just now. I previously called `/bin/renew_certs` directly, which isn't the command directly called by the cron job.

Running the following command does produce the error message you provided:
```
/command/with-contenv /command/s6-envdir -I /var/lib/https-portal/dynamic-env /bin/renew_certs
```

Seems to have something to do with `PATH` not containing `/command`.

**Comment by SteveLTN** [comment]
1.24.2 should have fixed the issue.

**Comment by viktorsmari** [comment]
Issue solved, thanks! :rocket:
