### ISSUE TITLE
Amendment to documentation for overriding just one single site's config

### ISSUE THREAD

**Issue by rogervdf** [SteveLTN/https-portal#363]
In your documentation you say, to override one site's config:

`https-portal:`
`  # ...`
`  volumes:`
`    - https-portal-data:/var/lib/https-portal`
`    - /path/to/http_config:/var/lib/nginx-conf/my.example.com.conf.erb:ro`
*->*`   ` - **/path/to/https_config:/var/lib/nginx-conf/my.example.com.ssl.conf.erb:ro**

Doing it that way generates the following error: `(Errno::EISDIR)`. The solution is to point to the file both on the left and right.

When you do that, there is another problem: nginx asphyxiates on the `http2 on` directive in the original .erb . Removing that, all works

**Comment by SteveLTN** [comment]
I believe `path` means a file or a dir.  

I'd make it more clear. Instead of `/path/to/http_config`, I'll say `path/to/http_config_file`.
