### ISSUE TITLE
Set STAGE env on a application container (rather than HTTPS-PORTAL)

### ISSUE THREAD

**Issue by shankiesan** [SteveLTN/https-portal#38]
Hi @SteveLTN 

I'm loving the project so much that I keep finding other little things that would make it even more amazing.

I was thinking that it would be good to be able to set the `STAGE` on a container independently of the `STAGE` on HTTPS-PORTAL. For instance, I have a staging server where I regularly bring up additional applications behind HTTPS-PORTAL. I'd like to be able be able to have HTTPS-PORTAL in `STAGE: "production"`, while bringing an individual container up like:

`wordpress:
  image: wordpress
  environment:
    STAGE: 'local'
  links:
    - db:mysqlz`

By doing this, we could do two things:

- Have an escape hatch for when you've done too many certificate requests on a domain, but you want to bring it up to have a play around with it, and, more importantly,
- Work on a container in a pre-live environment before flipping the DNS. This is my big issues at the moment – I have a legacy Apache server with multiple virtualhosts that I want to migrate to my new server using HTTPS-PORTAL. But at the moment, I have to ensure that the DNS resolves to my new server *before* I can spin up the application. If I could spin this container up as `local`, I could use local host spoofing to get my application set up, before flipping the DNS at the last stage

I thought I had seen the ability to do this in the docs somewhere, but I can't find it again – and I can't seem to get it to work.

What do you think?

**Comment by shankiesan** [comment]
Hey @SteveLTN. Any thoughts on this? I've site I'd like to bring live in this setup, but an existing prod site so I need to be able to bring a single site up as staging (without flipping the entire network to staging)

It's quite likely that I've just missed an easy way to so this... :)

**Comment by SteveLTN** [comment]
Unfortunately reading the environment variables from other containers are getting harder with the introduction of compose v2 format. I can see the trend of Docker isolating the environment access across containers. 

I'm afraid this would be quite hard.

**Comment by shankiesan** [comment]
Hmm ok. Understand how that would be difficult.

I can imagine that a solution to #37 might work as a workaround – if HTTPS-PORTAL will still bring the site up but without a certificate or an unsigned certificate if the ACME fails, then I could bring up an unverified site (as the domain doesn't resolve, but I have my local hostfile entry), migrate everything I need to, and then once the domain resolves, bring it up again with `docker-compose up` – at which point HTTPS-PORTAL will go get a validated certificate for it.

Does that make sense? Would that work? This would be a massive help to us as it would allow us to kill our old creaking Apache virtualhost-based setup and move all our client sites to HTTPS-PORTAL. Am happy to pay for some of your time if you do any freelance work...

**Comment by SteveLTN** [comment]
I will find some time to prevent ACME failure to bring down the container.

As for you problem, I think you can run all your sites in a local stage first, and then put all of it to production. That's the purpose of Docker right? Knowing that the local setup is exactly the same as the remote one.

HTTPS-PORTAL is not really meant to do such a complex task as you need to do. It's more for one-time simple setup. If your mission is that complex, you should probably have a look at [acme-tiny](https://github.com/diafygi/acme-tiny), which is used by PORTAL internally. With that you can have much more flexibility.

**Comment by shankiesan** [comment]
Thanks @SteveLTN . 

You're right in that I could do some of the work locally, and the environment would be the same, but there are still URLs in the DB that need to be swapped etc. So I can get close to as-live, but not exact.

Hmm acme-tiny looks good, but it's a long ways off the wonderful prod-ready solution that you've made! I'll wait for your resolution to #37 – that'll let me do what I want to.

**Comment by SteveLTN** [comment]
Well if you connect to the same DB, modify your local `/etc/hosts`, and run everything locally, and use a local stage to get a self-signed certificate. your application should not see anything different.

**Comment by shankiesan** [comment]
Yes, you're right. It's just doubles up the amount of file-copying that I have to do as I've got to go from old server to local and then local to prod once everything is good.

**Comment by SteveLTN** [comment]
OK. I guess you are not using a full-dockerized deploy setup then. 

Anyway, I'll have a look at #37 in the weekend and hopefully come up with a good solution of your problem.

**Comment by shankiesan** [comment]
I am *mostly* dockerised in deploy. But there's the non-app assets (in this case, medial files that the users have uploaded) that need to be migrated across.

Anyways, thanks for #37. That will help greatly.

**Comment by SteveLTN** [comment]
#37 is fixed.

And also, checkout the new functionality [here](https://github.com/SteveLTN/https-portal#multiple-domains).

You can now use different stage for individual domains by doing this in the ENVIRONMENTS:
```yaml
DOMAINS: 'wordpress.example.com -> http://wordpress #local, gitlab.example.com #production'
```

Don't forget to pull the latest image. Reopen the issue if you encounter any bugs.

**Comment by shankiesan** [comment]
Oooh that's a really elegant solution!

Thanks so much @SteveLTN – I've got one to test this on straight away. Thanks again, you're the best 😃

**Comment by shankiesan** [comment]
I've had a good chance to test this now @SteveLTN and it works a treat. I was a bit tripped up by having to link it to a container, so rather than just using the `VIRTUAL_HOST` env and then:

`DOMAINS : "mynewdomain.com -> http://mynewdomain"

I also had to add an external link to the running container, e.g. 

```
external_links:
    - mynewdomain
```

Works a treat 😄

**Comment by SteveLTN** [comment]
Good to hear that!

**Comment by shankiesan** [comment]
Really, truly thank you @SteveLTN . This is really helping us moving away from a terrible apache virtualhost setup to proper docker containers for our myriad of WordPress client sites. It looks like it's going to be a bit more memory-intensive, but otherwise seems to be working really well 😀
