### ISSUE TITLE
Serving static files with nginx, in a flask application

### ISSUE THREAD

**Issue by kampta** [SteveLTN/https-portal#41]
First of all, a big thanks for creating this. This will really save a lot of trouble for noob developers like me :).

I am creating a vanilla flask+gunicorn application, where static files are served by nginx. Here is a link to my current repo - https://github.com/kampta/https-portal-example

While nginx seems to be working alright, I keep getting this error

```
https-portal_1 | 2016/04/27 17:33:44 [error] 155#155: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 122.166.166.183, server: staging.example.com, request: "GET / HTTP/2.0", upstream: "http://172.17.0.2:80/", host: "staging.example.com"
https-portal_1 | 122.166.166.183 - - [27/Apr/2016:17:33:44 +0000] "GET / HTTP/2.0" 502 626 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36" "-"
https-portal_1 | 2016/04/27 17:33:44 [error] 155#155: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 122.166.166.183, server: staging.example.com, request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.17.0.2:80/favicon.ico", host: "staging.example.com", referrer: "https://staging.example.com/"
```

Would you please be able to point me in the right direction?
Thanks again!

**Comment by SteveLTN** [comment]
Hi,

You overwrote `default.conf.erb`, I guess that's because you want to serve your content on HTTP instead of doing HTTPS-only.

But you didn't overwrite `default.ssl.conf.erb`, so the SSL config for your site is still the default one, which reads `DOMAINS` variable. I saw you used `http://web` as the upstream, but you didn't specify the port!

**Comment by kampta** [comment]
I overwrote `default.conf.erb` so as to specify the location of static content of the flask application

```
location /static {
        alias /usr/src/app/static;
    }
```
Since you have pointed out, I guess it is possible to do it from `docker-compose.yml` itself. Is it?

**Comment by kampta** [comment]
And thanks for the port bug! That was stupid of me

**Comment by kampta** [comment]
I fixed port of the `docker-compose.yml` and the error I was getting vanished. (Updated repo - https://github.com/kampta/https-portal-example) However nginx is still not able to see the static folder. Suggestions?

**Comment by SteveLTN** [comment]
@kampta No. The default Nginx configs are for drop-in HTTPS support. It is opinionated and I don't encourage to do this kind of shared-folder setup. 

Per your problem, why do you think Nginx in the container will see the `/usr/src/app/static` folder of your web container at all?

**Comment by kampta** [comment]
I thought 

```
  volumes_from:
    - web
```
serves the purpose. And I would just need to edit nginx.conf files in order for nginx to see the static folders

**Comment by kampta** [comment]
I was able to serve static files by modifying `app.py`

```
app = Flask(__name__, static_folder='static')
```

Final code (https://github.com/kampta/https-portal-example). However I am confused as who is serving static content (here `bootstrap.min.css`). It is not recommended to serve static content with flask - http://stackoverflow.com/questions/20646822/how-to-serve-static-files-in-flask,

**Comment by kampta** [comment]
Sorry closed the issue accidentally, from the `docker-compose logs`
```
https-portal_1 | 2016/04/27 19:17:01 [warn] 155#155: *2 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 122.166.166.183, server: staging.example.com, request: "GET /static/bootstrap.min.css HTTP/2.0", upstream: "http://172.17.0.2:8000/static/bootstrap.min.css", host: "staging.example.com", referrer: "https://staging.example.com/"
```
I  am guessing static content is served by flask, and not nginx.

What in your opinion would be the right way to do it.

Thanks a ton

**Comment by SteveLTN** [comment]
OK, I didn't notice the `volumes_from` part.

In your latest setup, static files are definitely served by Flask.

Whether to use Nginx or Flask to serve your static files are your choice. 

* It makes sense to serve static assets by your app. HTTPS-PORTAL just does what it says, transfer a fully-functional HTTP site into a HTTPS site. Nothing more. This way each part does it's own job, is cleaner.
* If you want absolute performance, probably you will use a CDN anyway, so weather to serve from Nginx or Flash doesn't make any difference on performance.

**Comment by SteveLTN** [comment]
If you want to serve static assets by Nginx, I believe the right way is

```
location /assets/ {
    root /your/static/assets/folder;
}
```
alias is to make a url alias, right? It doesn't read files.

**Comment by kampta** [comment]
Ahh!! `docker-compose logs` now show
```
https-portal_1 | 122.166.166.183 - - [28/Apr/2016:02:18:22 +0000] "GET /static/bootstrap.min.css HTTP/2.0" 304 83 "https://staging.example.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36" "-"
```

Are the static files now being served from nginx? (Updated code at - https://github.com/kampta/https-portal-example)

**Comment by SteveLTN** [comment]
Having the log entry doesn't say anything. Even if it's served by Flask, it will be proxied through Nginx, so the log will be there anyway. I guess you can check Flask log to make sure no assets are served by Flask.

According to your code though, it should be served by Nginx directly by now.

**Comment by kampta** [comment]
Thanks again @SteveLTN  for the awesome repo and help :)
