### ISSUE TITLE
https-portal and cloudflare?

### ISSUE THREAD

**Issue by ddulic** [SteveLTN/https-portal#42]
If I add my website to Cloudflare and enable their certification, the website works fine but Let's Encrypts Cert is disabled and replaced with Cloudflares. As can be seen at the moment on my website: https://damir.tech

If I disabled this Certification in their control panel the website ceases to work and a redirect loop occurs, this didn't seem to be the issue with my previous Let's Encrypt setup. 

Any clarification? 

 ![youngertv-tv-land-younger-sutton-foster-3o6ozpK4HCj42txQxG](https://media2.giphy.com/media/3o6ozpK4HCj42txQxG/giphy.gif)

**Comment by SteveLTN** [comment]
If you use cloudflare's certificate, why do you need Let's Encrypt?

**Comment by ddulic** [comment]
I don't wanna use their Certificate. I wanna use Let's Encrypt, but if I disable cloudflare's certificate, Let's Encrypt breaks.

**Comment by SteveLTN** [comment]
Ask cloudflare to fetch content from HTTPS then?

**Comment by ddulic** [comment]
So its a cloudflare issue? Wasn't aware of this. Thanks.

**Comment by SteveLTN** [comment]
HTTPS-PORTAL needs to listen to your domain. Therefore you must resolve your domain to HTTPS-PORTAL. I guess that means you cannot use it with CloudFlare.

**Comment by vespakoen** [comment]
I am using https-portal together with cloudflare (for easy ipv6, looking to migrate away from it, but anyways)

Make sure you remove the page rules

The go to "Firewall" -> Switch the tab to "Web Application Firewall" -> Disable "Browser Integrity Check"

Now https-portal should be able to fetch the .well-known stuff over http.
