### ISSUE TITLE
Wordpress with Static Files?

### ISSUE THREAD

**Issue by ddulic** [SteveLTN/https-portal#43]
Possible to add a subdomain with static files along with the standard wordpress image? 
Trying to combine static files alongside wordpress via [https://github.com/SteveLTN/https-portal#serving-static-sites](url) doesn't seem to work for me. Keeps throwing me a `Unsupported config option for https-portal: 'valumes'`

Is this even possible?

**Comment by SteveLTN** [comment]
It should be volumes instead of valumes. And it is not possible to combine
static files with upstream websites.

**Comment by ddulic** [comment]
Ah, my bad, didn't notice that typo.
Any tip on how to make this work? One that does not require having a second server?

**Comment by SteveLTN** [comment]
I recommend you to look at the angina configuration file customization and
make your tweaks to it. It should not be hard.

**Comment by SteveLTN** [comment]
Oh wait, if you mean setting up two domains, one is connected to Wordpress
and the other serves to static files, this should work out of the box. Just
separate the domains with comma in DOMAINS env.

**Comment by ddulic** [comment]
Like this?

`https-portal:
  image: steveltn/https-portal
  ports:
    - '80:80'
    - '443:443'
  links:
    - web
  restart: always
  environment:
    DOMAINS: 'cv.damir.tech -> http://cv, damir.tech -> http://web'
    CLIENT_MAX_BODY_SIZE: '10M'
    STAGE: 'production'
   # FORCE_RENEW: 'true'
cv:
  volumes:
    - /data/https-portal/vhosts:/var/www/vhosts
...`

How do I link a domain to a volume if its inside the "https-portal" block?

**Comment by SteveLTN** [comment]
You don't need -> and everything after it for static files. Just '
example.com -> http://wordpress, cv.example.com'

**Comment by SteveLTN** [comment]
The volumes are in https-portal, not another container.

**Comment by ddulic** [comment]
Cheers. Works :) Successfully pinged :) Now I just need to sort out the DNS. Thank you.
