### ISSUE TITLE
Fails to come back up due to domain.rb error

### ISSUE THREAD

**Issue by shankiesan** [SteveLTN/https-portal#47]
Hi @SteveLTN 

Me again!

I've had to bring HTTPS-PORTAL down on one of my servers. On that server, I've got the certificates mapped out to the host using `- /data/ssl_certs:/var/lib/https-portal`. When I've tried to `docker-compose up -d` again, it's not come back up and has the following errors in the logs:

```
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-setup: executing...
/opt/certs_manager/models/domain.rb:65:in `name': undefined method `strip' for nil:NilClass (NoMethodError)
	from /opt/certs_manager/lib/na_config.rb:3:in `uniq'
	from /opt/certs_manager/lib/na_config.rb:3:in `domains'
	from /opt/certs_manager/certs_manager.rb:11:in `setup'
	from /etc/cont-init.d/00-setup:4:in `<main>'
[cont-init.d] 00-setup: exited 1.
[cont-init.d] 10-set-docker-gen-status: executing...
[cont-init.d] 10-set-docker-gen-status: exited 0.
[cont-init.d] done.
```

If I remove the stored certs and bring it back up, it appears to work. I say "appears" because I've tried on a clone of my VPS and it fails because DNS doesn't resolve (rightly), but it seems to get further than with the stored certificates.

I can probably regenerate, but this server had 10-ish subdomains of my main domain, so I'm reluctant to try to regenerate in case I bump into the LE rate limit.

Any idea what might be going on?

Cheers

**Comment by SteveLTN** [comment]
If you look at that line, it's

```ruby
      @name = descriptor.split('->').first.split(' ').first.strip
```

strip is called on `nil`, which means it returned an empty string for the domain name. 

Now, a domain name is deducted from a domain descriptor, like `example.com -> http://upstream #staging`. The can be fetched either from the `DOMAINS` env, or using automatic container discovery. 

So, any chance that the `DOMAINS` variable are not correct?

**Comment by shankiesan** [comment]
So I was wrong – it still isn't working even with binning the existing certs. Which makes sense given what you've said is wrong 😄 

Your advice was absolutely correct – the problem was that I had tried to bring on of my virtual hosts back up with `VIRTUAL_HOST` as a blank string (due to a bug in my install script it didn't get set). 

Couldn't have done it without your help as I didn't know that @name ~= VIRTUAL_HOST

Thanks ever so much!

**Comment by SteveLTN** [comment]
Hey, since you probably need to set the the STAGE in the `DOMAINS` anyway, you probably don't need to use the discovery function. I would personally think that is less reliable.

**Comment by shankiesan** [comment]
On my live servers, when I'm not migrating (and hence no resolving DNS), I am using discovery as most of the time (especially for new sites), it works a treat. I'll close!

A funky adventure 😀

**Comment by SteveLTN** [comment]
All right.

**Comment by shankiesan** [comment]
Hey @SteveLTN – long time no speak! It's because I'm a very happy developer 😄 

I've bumped up against this issue where a VIRTUAL_HOST was set to a zero-length string again (due to operator error); however, it pulls down all sites being hosted by HTTPS-PORTAL.

Would you either be open to doing some work to make it so that it only brings down one site, or failing that, open to me making a pull request to do it? I don't know much Ruby, but it looks pretty straightforward.

**Comment by SteveLTN** [comment]
Hi,

I'm going on vacation for about three weeks. I'm afraid I don't time to do
any work on that. Feel free to make a pull-request.

**Comment by SteveLTN** [comment]
Modify `NAConfig.domains`, make sure it only returns valid domain should do
the trick.

**Comment by shankiesan** [comment]
Cool, I'll have a look and do a pull request. If it doesn't return a valid domain name, will it just not bring up that container, or will it take the entire network down?

I might also consider adding some logging – e.g. The VIRTUAL_HOST env var for CONTAINER_NAME is invalid (or something to that effect).

Enjoy your holiday 😄

**Comment by SteveLTN** [comment]
If you simply exclude it in NAConfig, it will not be registered as a domain
this will be ignored. You can add some logging there too.
