### ISSUE TITLE
Multiple domains for the same upstream container

### ISSUE THREAD

**Issue by shankiesan** [SteveLTN/https-portal#48]
Hi @SteveLTN – me again, exploring the edge-cases of HTTPS-PORTAL!

I've got a multilingual site where I run the Welsh and English versions on separate domains.

I've tried the following environment variable for HTTPS-PORTAL:

`DOMAINS: 'mysite.wales -> http://mysite, mysite.cymru -> http://mysite'`

If I do this, domain verification fails on mysite.cymru with the following in the logs:

```
Traceback (most recent call last):
  File "/bin/acme_tiny", line 198, in <module>
    main(sys.argv[1:])
  File "/bin/acme_tiny", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/bin/acme_tiny", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to /var/www/default/challenges/eA04PB7RP4KR9GqyVpE3pnM_k_cW7Zmjdqc_JXRcJu0, but couldn't download http://mysite.cymru/.well-known/acme-challenge/eA04PB7RP4KR9GqyVpE3pnM_k_cW7Zmjdqc_JXRcJu0
Failed to obtain certs for mysite.cymru
```

Any idea how to do multiple domains for the same container? Ideally, `VIRTUAL_HOST` would allow comma-separated domains so that it can be encapsulated in the web server rather than the RP, but I'll take anything that works!

Of course, it's also possible that I've just done something really stupid.

**Comment by shankiesan** [comment]
Oops! So, ignore the above. There was a typo in my domain now. However, the problem still stands: having multiple domains pointing to the same upstream container fails, but now with a different error (now that certificate signing succeeded). 

I get:

`2016/05/23 11:23:50 [emerg] 143#143: host not found in upstream "mysite" in /etc/nginx/conf.d/mysite.wales.ssl.conf:18
nginx: [emerg] host not found in upstream "garden" in /etc/nginx/conf.d/mysite.wales.ssl.conf:18`

Note that I get the `host not found in upstream "mysite"` on the *first* domain in the domain list – even though it's adding the second domain that causes it to fail.

**Comment by SteveLTN** [comment]
Hi, having multiple domains using the same upstream should not require any changes in the configuration files. Just do `DOMAINS: a.site -> http://upstream, b.site -> http://upstrea` should work.

The container complains about not being able to find the host. Meaning `garden` is not listed in `/etc/hosts` of the PORTAL container. You can add it by adding a `links` section:

```
links:
  - garden:your-service-name
```

**Comment by shankiesan** [comment]
Oh! Of course! I've bumped into that problem before.

Thanks so much man, got it working.

As you can see, I didn't fully obscure the project I was working on. In case you'd like to see what we're up to, https://botanicgarden.wales/ and https://garddfotaneg.cymru/ are now proudly served using HTTPS-PORTAL 😄 

If I can ever do you a favour @SteveLTN , don't hesitate to ask. You and this project have been a great help to us.

**Comment by SteveLTN** [comment]
You're welcome. 

-- 
Weiyan Shao

On May 23, 2016 at 3:04:23 PM, shankiesan (notifications@github.com) wrote:

Oh! Of course! I've bumped into that problem before.

Thanks so much man, got it working.

As you can see, I didn't fully obscure the project I was working on. In case you'd like to see what we're up to, https://botanicgarden.wales/ and https://garddfotaneg.cymru/ are now proudly served using HTTPS-PORTAL 😄

If I can ever do you a favour @SteveLTN , don't hesitate to ask. You and this project have been a great help to us.
