### ISSUE TITLE
host not found in upstream "etherpad" in /etc/nginx/conf.d/pads.domain.org.ssl.conf:18

### ISSUE THREAD

**Issue by berzas** [SteveLTN/https-portal#50]
Hi,

I'm trying to add multiple domains on https-portal but on some I'm getting:
'host not found in upstream'
I've mounted: 
`./config/docker/nginx/:/etc/nginx/conf.d/:rw`
And checked the file `pads.domain.org.ssl.conf` I can see is exactly the same as other domains that are working. I added domains as explained here https://github.com/SteveLTN/https-portal and also specified VIRTUAL_HOST on the containers pointing to those domains on https-portal docker-compose.yml

I made that working with wordpress and ethercalc, containers failing are rocket chat and etherpad.

What should I do?

[Uploading docker_compose.txt…]()

**Comment by berzas** [comment]
[docker_compose.txt](https://github.com/SteveLTN/https-portal/files/299365/docker_compose.txt)

**Comment by SteveLTN** [comment]
`etherpad` and `app` are not in the `links:`.

If you specify upstreams in `DOMAINS`, you don't need `VIRTUAL_HOST` on each container.

**Comment by berzas** [comment]
Thanks SteveLTN, even putting ´etherpad´ and ´app´ on ´links´ I've got the same issues. Instead if I just use f`VIRTUAL_HOST` on each containers is working fine.

**Comment by SteveLTN** [comment]
OK then. Closing the issue.
