### ISSUE TITLE
Advised to mount certs folder?

### ISSUE THREAD

**Issue by vespakoen** [SteveLTN/https-portal#54]
Hey there!

I am super happy with this project, it makes SSL easy as it should be =)
However, I hit the rate limit, I have a CI/CD tool setup that will build docker containers and deploy them to production once a push happens on some branch, the way it works is it pulls my new images, stops / removes the running containers, then starts them again.

I guess in this process my certificates are lost, and they will get re-requested.
I now mount the certs folder to my host VM, hoping they will be "picked up" by https-portal on a new startup, avoiding the (rate limited) API calls to letsencrypt.
Do you know if this will work? (I cannot really test right now because of the rate limit).

If so, I'd be happy to update the readme on that.

**Comment by SteveLTN** [comment]
Hi, by default this container creates an anonymous data volume, and will pick-up the previous certificate if the data volume is still available. That means on production, it will usually NOT re-request the certificate. You can mount `/var/lib/https-portal` to a host folder to make it more explicit.

However, I'm suspecting your CI/CD tool will build a new isolated environment for each build. If that's the case, you might need to find another way to keep the certificate across builds, or use `local` mode which self-signs a dummy certificate. 

I have this in the document, but if you can rephrase it in a better way, please send a pull-request.

```
HTTPS-PORTAL stores your certificates in a data volume and will not re-sign certificates until 30 days before expiration if a valid certificate is found
```

Feel free to contact me if you have more problems.

**Comment by vespakoen** [comment]
Ah I see, cool, my "auto deploy" script will remove containers with the --all flag (containers + data containers) every time I run it it tells me that --all is going to be the default soon, so maybe your anonymous container is not going to work / people will run into my issue more likely soon.

So perhaps we should update the docs and advice to mount the certificates to the host.

**Comment by rossdargan** [comment]
I think with the new swarm stuff coming out it would be really useful to have the volumes mounted. You could have multiple containers spun up across several boxes and if the certs aren't shared the limits will be very quickly hit! I suppose this could hit further issues with multiple tasks trying to renew the same certs :/.

**Comment by vespakoen** [comment]
With swarm, you would need something like "flocker" to mount a path "across" servers?
Didn't use it yet but I am wondering how one share such a folder

**Comment by SteveLTN** [comment]
@rossdargan @vespakoen Personally I haven't used swarm yet. But I imagine you can use some cross-server data volume drivers to share the certs.
