### ISSUE TITLE
[Question]: Exclude one of docker containers from SSL

### ISSUE THREAD

**Issue by WebDucer** [SteveLTN/https-portal#75]
We use your image to run our docker with lets encrypt certificates. This works fine. Now we have one docker container, that should be excluded from HTTPS (but still use subdomain resolution of https-portal). Is it possible?

The problem that we actually have, is that some clients, that consume this docker container, are not able to handle letsencrypt certificates (mono on macOS). Until the client problem is solved, we have to use unsecured connection. But we don't want to turn off SSL for all other containers.

**Comment by SteveLTN** [comment]
It's not possible to turn off SSL without customizing your nginx config. 
However you can customize `your.domain.conf.erb` and `your.domain.ssl.conf.erb`, see [the document](https://github.com/SteveLTN/https-portal#override-nginx-configuration-files). Make it not use SSL, but you want to keep the acme-challenge path so the container would work.

**Comment by WebDucer** [comment]
Thanks for the info.

It works for me.
