### ISSUE TITLE
Fat arrow for domain 301 redirection

### ISSUE THREAD

**Issue by darwin** [SteveLTN/https-portal#77]
I'd like to add ability to specify 301 redirections instead of proxying. The goal is to redirect https requests from naked domains to www CNAME.

My current idea is to allow fat arrows in `DOMAINS` var.

For example DOMAINS="mydomain.com => www.mydomain.com" would generate 
`return 301 https://www.mydomain.com$request_uri;` nginx config instead of normal proxy config[1].

Assuming certificate would get properly generated for the naked domain. This way I could properly setup https-enabled redirect from naked domains to my www domains.

I looked briefly at the code and it seems to be an easy change. I would teach domain model how to parse fat arrows and add conditional logic to generate redirect config into `default.ssl.conf.erb`.

Suggestions? Ideas?

[1] https://github.com/SteveLTN/https-portal/blob/6d13d85b14e23e72db2f0d177b2146586aa9ac7c/fs_overlay/var/lib/nginx-conf/default.ssl.conf.erb#L17

**Comment by SteveLTN** [comment]
Hi, thank you for the interest.

However I feel this is a complex enough feature that I would personally not merge into the codebase. The environment variable configuration is primitive, I don't think putting more and more complexity into it is a good idea. If you want to do more customized setup, you can always supply your own Nginx config.

But if you want to fork the project and add the feature for your own, I recommend you to start by extending `domain.rb`, make it aware of the fat arrow statement, and then use it in the nginx configuration.

**Comment by darwin** [comment]
Thanks for your answer. I will do the fork.

> you can always supply your own Nginx config
This does not work in this case, because I need portal to manage SSL certs for naked domains for me. There does not seem to be a way how tell portal to manage SSL certs for a domain without proxying or doing a static site for it.

Maybe I could somehow setup DOMAINS to point to a static site and then override nginx configs to inject 301 redirect config to proper place to override static site config. But that seems even more hacky than simply extending `domain.rb` and generating clean nginx configuration.

**Comment by darwin** [comment]
Actually you were right. I can build my own overlay image built on top of your docker image and provide my own `default.ssl.conf.erb` which can have some special logic handling my domains.

Thanks!
