### ISSUE TITLE
2 domains, 1 static sites, any way to do it?

### ISSUE THREAD

**Issue by MadsRC** [SteveLTN/https-portal#78]
Say I have site.com and www.site.com. Say I also have 1 index.html that I want both domains to serve.

How is this achieved (If possible)?
Doesn't seem like "DOMAINS: site.com, www.site.com" works.
The only way that I can think of is to have 2 nginx containers running, which both points to the same index.html file and have https-portal redirect to that.

That seems like quite a lot of overhead for just serving static files.

**Comment by darwin** [comment]
Static sites via DOMAINS env var work for me as documented. You have to put your static content to vhost folders as [documented in the readme](https://github.com/SteveLTN/https-portal#serving-static-sites).

If you want the same content in multiple sites, I think symlinks should work (not tested).

But based on your description, I think you want to setup a 301 redirect from the naked domain to your www domain. You probably don't want that content to be indexed by search engines twice.
This would need a tweak in the https-portal ngingx config templates as discussed in https://github.com/SteveLTN/https-portal/issues/77.

**Comment by MadsRC** [comment]
Unfortunately symlinks doesn't work - Already tried it (Though forgot to save the error).

I'm aware of the posibility of editing the nginx config, though I hoped it had been a build-in feature.

Guess I'll sit down and see if I can fix it in a fork and commit it back :dancing_men:

**Comment by darwin** [comment]
Interesting, have you done the symlink between folders on the host machine and then attach the folders as a volume or did you try to do a symlink directly inside the container? Or was it a problem for nginx for security reasons?

Anyways, you don't have to fork in this case. You can create an overlay docker image:
https://gist.github.com/darwin/df67df4e21518372d0a4aa77bb4273df

in fs_overlay I replaced `default.ssl.conf.erb` with my own version

**Comment by SteveLTN** [comment]
@MadsRC Hmm, I don't understand why symlinks would not work. Besides symlink, I think you can mount the same folder twice into docker containers. I'll give you an example later.

**Comment by SteveLTN** [comment]
@MadsRC My bad, you can't mount the same folder twice because the container use subfolders to differentiate `index.html` for different domains. I'm still trying symlinks.

**Comment by SteveLTN** [comment]
This works for me:

Symlink:
```
localhost
localhost2 -> localhost
```

```yml
version: '2'

services:
  https-portal:
    image: steveltn/https-portal
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAINS: 'localhost, localhost2'
      STAGE: local
    volumes:
      - ./vhosts:/var/www/vhosts
```

**Comment by MadsRC** [comment]
Thanks Steve, that looks like its working.

However, I might be in need of doing a permanent redirect - Right now I'm adding it to the nginx config, however I'd like for it to be more "smooth" - I'll see if I can implement a way to do it with environment variables and send you a PR

**Comment by SteveLTN** [comment]
Okay. You are not the first one who wants redirection. If you make a PR I
will accept it.

Before you start working probably you can tell me how you want to design
the config ends.
