### ISSUE TITLE
nginx error message when using multiple domains

### ISSUE THREAD

**Issue by dennisgermany** [SteveLTN/https-portal#8]
Hi, thank you very much for this great docker image!
I just tried to use it for one domain and it worked perfectly.
Afterwards I used the described way to include multiple domains, but nginx does not want to start anymore.

Error message:
2016/01/08 23:14:11 [emerg] 129#129: could not build server_names_hash, you should increase server_names_hash_bucket_size: 32
nginx: [emerg] could not build server_names_hash, you should increase server_names_hash_bucket_size: 32

Is there a way to specify something like this:

server_names_hash_bucket_size 64;

?

Thanks!

**Comment by SteveLTN** [comment]
Hi, can you show me your compose file? Apparently your `server_name` is longer than 32 characters?

I will update the Nginx config and make it 64.

**Comment by SteveLTN** [comment]
I'll look into making this configuration through environment variables.

In the mean time, you can override `/etc/nginx/nginx.conf` in the container to work around it.

**Comment by SteveLTN** [comment]
Hi, check out the new section [Configure Nginx through Environment Variables](https://github.com/SteveLTN/https-portal#configure-nginx-through-environment-variables)!

When you run HTTPS-PORTAL, just say:

```yaml
https-portal
  # ...
  environment:
    SERVER_NAMES_HASH_BUCKET_SIZE: 64
```

Don't forget to pull the latest image!

**Comment by dennisgermany** [comment]
Hey,
it works like a charm!
Great work! Thanks.

**Comment by SteveLTN** [comment]
Good to hear that! So I just close the issue.
