### ISSUE TITLE
SSL_CTX_use_PrivateKey_file error

### ISSUE THREAD

**Issue by ddulic** [SteveLTN/https-portal#85]
`https-portal_1  | 2017/01/22 17:23:29 [emerg] 119#119: SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/dipl.damir.tech/production/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)`

I fixed the MariaDB error from a while back I posted. Next error in line is this.

**Comment by SteveLTN** [comment]
I cannot reproduce this problem. Could it be that you have some other files in the volume? 

I tried obtaining the certs and force renewing them. Please pull the latest image and clear the volume, then try again.

**Comment by ddulic** [comment]
I recreated everything which fixed the issue, I have a backup which I will bring up today/tomorrow and post if there is anything else in the volume.

**Comment by ddulic** [comment]
And now the backup works... I have no idea what is happening :O

**Comment by npjonath** [comment]
Hi,

I got similar problem with this running.

OS : ubuntu 16.04 LTS + docker 1.13.
Provider : VPS on OVH.com (fresh ubuntu 16.04 LTS + docker 1.13 + docker-compose 1.10.0)

I try multiple time to cleanup all my docker image. (force recreate, rmi all docker image, ...) with always the same error.


> https-portal:
>   image: steveltn/https-portal:1.0.0
>   container_name: httpsportal
>   ports:
>     - '80:80'
>     - '443:443'
>   restart: always
>   links:
>     - myapache
>   environment:
>     DOMAINS: 'www.mywebsite.com -> http://myapache'  ## I also try using only mywebsite.com
>     STAGE: 'staging'
>     FORCE_RENEW: 'true'
> myapachedb:
>   image: mysql:5.5
>   container_name: myapachedb
>   restart: always
>   volumes:
>    ...
>   environment:
>    MYSQL_ROOT_PASSWORD: '-----'
>    MYSQL_DATABASE: 'myapachedb'
>    MYSQL_USER: 'userdb'
>    MYSQL_PASSWORD: '-----'
> 
> \\\ official php:5.6-apache with graphviz library addition. listen by default on 80
> myapache:
>   build: site   
>   container_name: myapache
>   restart: always
>   links:
>    -myapachedb:mysql
>   volumes:
>    -./volumes/src:/var/www/html/
> 
> 

I got result : 
> Parsing account key...
> Parsing CSR...
> Registering account...
> Registered!
> Verifying www.mywebsite.com...
> Traceback (most recent call last):
>   File "/bin/acme_tiny", line 198, in <module>
>     main(sys.argv[1:])
>   File "/bin/acme_tiny", line 194, in main
>     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
>   File "/bin/acme_tiny", line 123, in get_crt
>     wellknown_path, wellknown_url))
> ValueError: Wrote file to /var/www/default/challenges/72AdroQVwQCRsPX1gFxrBf_N0RfD77OZm2W5Lo0CHfM, but couldn't download http://www.mywebsite.com/.well-known/acme-challenge/72AdroQVwQCRsPX1gFxrBf_N0RfD77OZm2W5Lo0CHfM
> 2017/02/05 14:34:25 [emerg] 140#140: SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL:
> error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> 2017/02/05 14:34:25 [emerg] 141#141: SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL:
> error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> 2017/02/05 14:34:26 [emerg] 169#169: SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL:
> error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> 2017/02/05 14:34:26 [emerg] 122#122: SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> 2017/02/05 14:34:30 [emerg] 119#119: SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL:
> error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> 2017/02/05 14:34:30 [emerg] 120#120: SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL:
> error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> Parsing account key...
> Parsing CSR...
> Registering account...
> Already registered!
> Verifying www.mywebsite.com...
> Traceback (most recent call last):
>   File "/bin/acme_tiny", line 198, in <module>
>     main(sys.argv[1:])
>   File "/bin/acme_tiny", line 194, in main
>     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
>   File "/bin/acme_tiny", line 117, in get_crt
>     resp = urlopen(wellknown_url)
>   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 437, in open
>     response = meth(req, response)
>   File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python2.7/urllib2.py", line 469, in error
>     result = self._call_chain(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 656, in http_error_302
>     return self.parent.open(new, timeout=req.timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 431, in open
>     response = self._open(req, data)
>   File "/usr/lib/python2.7/urllib2.py", line 449, in _open
>     '_open', req)
>   File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
>     return self.do_open(httplib.HTTPConnection, req)
>   File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
>     r = h.getresponse(buffering=True)
>   File "/usr/lib/python2.7/httplib.py", line 1111, in getresponse
>     response.begin()
>   File "/usr/lib/python2.7/httplib.py", line 444, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python2.7/httplib.py", line 408, in _read_status
>     raise BadStatusLine(line)
> httplib.BadStatusLine: ''
> 2017/02/05 14:34:31 [emerg] 133#133: SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL:
> error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> 2017/02/05 14:34:31 [emerg] 134#134: SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL:
> error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> 2017/02/05 14:34:32 [emerg] 162#162: SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mywebsite.com/staging/domain.key") failed (SSL:
> error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
> ubuntu@mywebsite:~/mywebsite-docker-site-v1$ cat logd.txt
> [fix-attrs.d] applying owners & permissions fixes...
> [fix-attrs.d] 00-runscripts: applying...
> [fix-attrs.d] 00-runscripts: exited 0.
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 00-setup: executing...
> Signing certificates from https://acme-staging.api.letsencrypt.org ...
> Signed key for www.mywebsite.com
> [cont-init.d] 00-setup: exited 0.
> [cont-init.d] 10-set-docker-gen-status: executing...
> [cont-init.d] 10-set-docker-gen-status: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done. 

Of course, mywebsite.com is a real domain available through HTTP 80 when i disable http_portal.

**Comment by SteveLTN** [comment]
@npjonath thanks. I'll have a look this weekend. Finally I notice that there is a signing failure before the mismatch error message. Looks like your DNS is not configured properly. But I'll see what is going on.

**Comment by npjonath** [comment]
@SteveLTN indeed it's DNS issue from my provider.

`dig mydomain.com` with "1&1 IP redirection" option give me the 1&1 DNS IP. (don't know if it's something like iframe redirection or something else) and https_portal got the errors above. 

`dig mydomain.com` with A Record give me the target host IP and https_portal works fine then.

In both case, if i don't use https_portal, I got my website workings.

**Comment by SteveLTN** [comment]
I don't know what "1&1 IP redirection" is, but if you want SSL certificate, you can't use HTTP redirection. CNAME or A record is the correct way to set up DNS.

**Comment by medom** [comment]
I just ran into the same problem. all I did was shutdown the docker container after ~30days of uptime, and after adding a new host I couldn't start it up again. tried to fiddle around, modify config, delete all the certificates, nothing helped. I ended up deleting the whole container & redownloaded the image. same version tho. now everything is fine again, including the new host. strange

**Comment by kakakaya** [comment]
I got same error.
At first https-portal worked well. But, I changed a subdomain in DOMAINS section by mistake, and from then my https-portal starts getting error.

I tried deleting container and image, but nothing fixed. https-portal continues to error.

**Comment by MadsRC** [comment]
I'm getting the same error:
`2017/03/19 21:08:45 [emerg] 138#138: SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/cloud.v42.dk/staging/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)`

However, it's in a slightly different context - The full output is:

```
[root@proxy proxy]# /var/usrlocal/bin/docker-compose logs -f
Attaching to proxy_https-portal_1
https-portal_1  | [fix-attrs.d] applying owners & permissions fixes...
https-portal_1  | [fix-attrs.d] 00-runscripts: applying... 
https-portal_1  | [fix-attrs.d] 00-runscripts: exited 0.
https-portal_1  | [fix-attrs.d] done.
https-portal_1  | [cont-init.d] executing container initialization scripts...
https-portal_1  | [cont-init.d] 00-setup: executing... 
https-portal_1  | Generating DH parameters, 2048 bit long safe prime, generator 2
https-portal_1  | This is going to take a long time
https-portal_1  | .......................+...............................................................................................................................................................+................................................................................................................................................................................................................................................................................................+.............................+.+................................................................................................................................................+..........+.........................................................................................................................................+...................+...+................................................................................................................+..............................+.....................................................+.+...........+..................+..............................................................................................+................................................+....................................................+........................................................+.......................................................+.....................................................................................................................................................................................................................................+........................+.....................+......................................+.......+..............................................+.........................................................................+..............++*++*
https-portal_1  | Generating RSA private key, 4096 bit long modulus
https-portal_1  | ........................................++
https-portal_1  | ....................................................++
https-portal_1  | e is 65537 (0x10001)
https-portal_1  | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
https-portal_1  | 2017/03/19 21:08:44 [emerg] 121#121: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
https-portal_1  | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
https-portal_1  | 2017/03/19 21:08:44 [notice] 122#122: signal process started
https-portal_1  | 2017/03/19 21:08:44 [error] 122#122: open() "/var/run/nginx.pid" failed (2: No such file or directory)
https-portal_1  | Generating RSA private key, 2048 bit long modulus
https-portal_1  | .........................+++
https-portal_1  | .............+++
https-portal_1  | e is 65537 (0x10001)
https-portal_1  | Signing certificates from https://acme-staging.api.letsencrypt.org ...
https-portal_1  | Parsing account key...
https-portal_1  | Parsing CSR...
https-portal_1  | Registering account...
https-portal_1  | Registered!
https-portal_1  | Verifying cloud.v42.dk...
https-portal_1  | Traceback (most recent call last):
https-portal_1  |   File "/bin/acme_tiny", line 198, in <module>
https-portal_1  |     main(sys.argv[1:])
https-portal_1  |   File "/bin/acme_tiny", line 194, in main
https-portal_1  |     signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
https-portal_1  |   File "/bin/acme_tiny", line 117, in get_crt
https-portal_1  |     resp = urlopen(wellknown_url)
https-portal_1  |   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
https-portal_1  |     return opener.open(url, data, timeout)
https-portal_1  |   File "/usr/lib/python2.7/urllib2.py", line 431, in open
https-portal_1  |     response = self._open(req, data)
https-portal_1  |   File "/usr/lib/python2.7/urllib2.py", line 449, in _open
https-portal_1  |     '_open', req)
https-portal_1  |   File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
https-portal_1  |     result = func(*args)
https-portal_1  |   File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
https-portal_1  |     return self.do_open(httplib.HTTPConnection, req)
https-portal_1  |   File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
https-portal_1  |     r = h.getresponse(buffering=True)
https-portal_1  |   File "/usr/lib/python2.7/httplib.py", line 1111, in getresponse
https-portal_1  |     response.begin()
https-portal_1  |   File "/usr/lib/python2.7/httplib.py", line 444, in begin
https-portal_1  |     version, status, reason = self._read_status()
https-portal_1  |   File "/usr/lib/python2.7/httplib.py", line 408, in _read_status
https-portal_1  |     raise BadStatusLine(line)
https-portal_1  | httplib.BadStatusLine: ''
https-portal_1  | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
https-portal_1  | Signed key for cloud.v42.dk
https-portal_1  | 2017/03/19 21:08:45 [emerg] 137#137: SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/cloud.v42.dk/staging/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
https-portal_1  | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
https-portal_1  | 2017/03/19 21:08:45 [emerg] 138#138: SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/cloud.v42.dk/staging/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
https-portal_1  | [cont-init.d] 00-setup: exited 0.
https-portal_1  | [cont-init.d] 10-set-docker-gen-status: executing... 
https-portal_1  | [cont-init.d] 10-set-docker-gen-status: exited 0.
https-portal_1  | [cont-init.d] done.
https-portal_1  | [services.d] starting services
https-portal_1  | [services.d] done.
https-portal_1  | Starting crond ...
https-portal_1  | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
https-portal_1  | 2017/03/19 21:08:46 [emerg] 165#165: SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/cloud.v42.dk/staging/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
https-portal_1  | [cont-finish.d] executing container finish scripts...
https-portal_1  | [cont-finish.d] done.
https-portal_1  | [s6-finish] syncing disks.
https-portal_1  | [s6-finish] sending all processes the TERM signal.
https-portal_1  | [s6-finish] sending all processes the KILL signal and exiting.
proxy_https-portal_1 exited with code 0
```

DNS and firewall is configured correctly as checked with:
```
[root@proxy proxy]# nc -l 80
GET / HTTP/1.1
User-Agent: curl/7.29.0
Host: cloud.v42.dk
Accept: */*
```
```
[root@webmail ~]# curl cloud.v42.dk
curl: (52) Empty reply from server
```

My compose file is:
```
https-portal:
  image: steveltn/https-portal:1.0.0
  ports:
    - '80:80'
    - '443:443'
  environment:
    DOMAINS: 'cloud.v42.dk'
    # STAGE: 'production'
```

Operating system is a fully updated CentOS 7 Atomic Host, SELinux enabled (and tried disabling it)

Tried deleting and redownloading the image, still no problem.

Seems to be a bug in the ACME-tiny script maybe?

I've got some time tonight so I'll try to see if I can fix it.

**Comment by SteveLTN** [comment]
I'll have a look when I get home. @MadsRC I would first update the script to the latest version.

**Comment by MadsRC** [comment]
Thanks a bunch :)  

I rebuilt the image yesterday night, to make sure I had the latest version of the script (it does)  

Weird thing is, running acne-tiny manually on the host systems works perfectly.

--  
Med venlig hilsen | Best regards
Mads R. Havmand

**Comment by SteveLTN** [comment]
Hi all, I found if acme.sh fails to obtain certificate, PORTAL will replace the working but old certificate nonetheless. I fixed it. Please pull `1.0.1` or simple `latest` to get the update.

However, I don't have a way to tell you if an attempt to sign a cert fails.

**Comment by SteveLTN** [comment]
Closing due to no response for a while. Feel free to reopen.
