### ISSUE TITLE
Troubles with changing redirections

### ISSUE THREAD

**Issue by geelenbert** [SteveLTN/https-portal#90]
Hi,

I have an issue with changing the parameters of the containter. 
I need to change the forwarding ports and ip's. I changed the DOMAINS line:

`cloud.domain.com -> http://192.168.1.178:8888 , couchpotato.domain.com -> http://192.168.1.176:5050 `
To:
cloud.domain.com -> http://192.168.1.178:80 , couchpotato.domain.com -> http://192.168.1.180:5050  

But when restarting the container, the old forwarding adresses are stil there.

When i enter the console of the conatiner and check on the config files in /etc/nginx/conf.d/ 
The config files are adapting to the changes. What's going wrong ... ?

**Comment by SteveLTN** [comment]
If the Nginx config files are changed, it shouldn't be like this. Nginx is
stopped and restarted every time. Can you try to reload Nginx in the
container to see if it works?

**Comment by SteveLTN** [comment]
Closing due to no response for a while. Feel free to reopen.
