### ISSUE TITLE
Be able to change the access_log format

### ISSUE THREAD

**Issue by Dermah** [SteveLTN/https-portal#91]
I would like to be able to change the default `log_format` value (I just want to add `$request_time` to the end of the log line).

What's the best way to do that with the configuration options available? I haven't been able to do it using the [Override Nginx Configuration Files](https://github.com/SteveLTN/https-portal#override-nginx-configuration-files) suggestions, I'm assuming because those conf files are folded in to  the [main conf file which already has `access_log` defined](https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/var/lib/nginx-conf/nginx.conf.erb#L16).

**Comment by SteveLTN** [comment]
On Mon, Apr 3, 2017 at 7:26 AM, Sputnik <notifications@github.com> wrote:

> log_format


I would recommend fork the repo, make log_format a configurable ENV like
other Nginx config options. Don't forget to send a pull-request if you do
it :-)
