### ISSUE TITLE
Default vhost

### ISSUE THREAD

**Issue by jamesjjk** [SteveLTN/https-portal#93]
Hi any ideas how to implement a default vhost not to leak first TLS config. Thanks!

**Comment by jamesjjk** [comment]
Mayne consider in ssl default conf

```
if ($host != $server_name) {
        return       444;
    }
```

**Comment by SteveLTN** [comment]
I'll think about it and push a new release.

**Comment by SteveLTN** [comment]
Sorry, I haven't got time till now. But v1.1.0 is released! Thank you for your feedback!
